SeExpr: /disk1/scratch/aselle/projects/seexpr/SeExpr/src/demos/asciiCalculator.cpp File Reference
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/demos/asciiCalculator.cpp File Reference
#include <SeExpression.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
Defines
#define STACK_DEPTH 256
Functions
void quit (const std::string &str)
int main ()
Detailed Description
Definition in file asciiCalculator.cpp.
Define Documentation
#define STACK_DEPTH 256
Definition at line 15 of file asciiCalculator.cpp.
Function Documentation
int main ()
Definition at line 99 of file asciiCalculator.cpp.
References expr(), and quit().
void quit (const std::string & str)
Definition at line 92 of file asciiCalculator.cpp.
Referenced by main().