SeExpr: /jobs2/soft/users/aselle/src/seexpr-to-push/src/demos/asciiGraph.cpp File Reference
/jobs2/soft/users/aselle/src/seexpr-to-push/src/demos/asciiGraph.cpp File Reference
#include <SeExpression.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
Classes
class GrapherExpr
Simple expression class to support our function grapher.
struct GrapherExpr::SimpleVar
Simple variable that just returns its internal value.
Functions
int main (int argc, char *argv[])
Detailed Description
Definition in file asciiGraph.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 77 of file asciiGraph.cpp.
References SeExpression::evaluate(), expr(), SeExpression::isValid(), one_over_samples_per_pixel, SeExpression::parseError(), GrapherExpr::setX(), x, and y.