SeExpr: ExprDialog Class Reference
ExprDialog Class Reference
#include <ExprDialog.h>
Public Slots
void applyExpression ()
void clearExpression ()
void reject ()
Signals
void preview ()
void expressionApplied ()
void dialogClosed ()
Public Member Functions
ExprDialog (QWidget *parent)
std::string getExpressionString ()
void setExpressionString (const std::string &str)
void show ()
int exec ()
void showEditor (int idx)
Public Attributes
ExprEditor * editor
ExprBrowser * browser
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void findHelper (QTextDocument::FindFlags flags)
void closeEvent (QCloseEvent *event)
Private Slots
void previewExpression ()
void verifiedApply ()
void verifiedAccept ()
void findNextInHelp ()
void findPrevInHelp ()
void _showEditor ()
Private Member Functions
void setupHelp (QTabWidget *tab)
Private Attributes
ExprGrapherWidget * grapher
QLabel * previewCommentLabel
QPushButton * acceptButton
QPushButton * cancelButton
ExprControlCollection * controls
QPushButton * applyButton
QPushButton * previewButton
QPushButton * saveButton
QPushButton * saveAsButton
QPushButton * saveLocalButton
QPushButton * clearButton
QLineEdit * helpFindBox
QTimer * showEditorTimer
QTextBrowser * helpBrowser
QTextCursor cursor
QString prevFind
int _currentEditorIdx
Detailed Description
Definition at line 45 of file ExprDialog.h.
Constructor & Destructor Documentation
ExprDialog::ExprDialog (QWidget * parent)
Definition at line 36 of file ExprDialog.cpp.
References _showEditor(), acceptButton, applyButton, browser, cancelButton, clearButton, clearExpression(), controls, editor, grapher, preview(), previewButton, previewCommentLabel, previewExpression(), reject(), saveAsButton, saveButton, saveLocalButton, setupHelp(), showEditorTimer, verifiedAccept(), and verifiedApply().
Member Function Documentation
void ExprDialog::_showEditor () private slot
Definition at line 151 of file ExprDialog.cpp.
References _currentEditorIdx, controls, and ExprControlCollection::showEditor().
Referenced by ExprDialog().
void ExprDialog::applyExpression () slot
Definition at line 311 of file ExprDialog.cpp.
References ExprEditor::addError(), ExprEditor::clearErrors(), editor, ExprGrapherWidget::expr, BasicExpression::funcmap, SeExpr2::Expression::getErrors(), ExprEditor::getExpr(), grapher, SeExpr2::Expression::isValid(), ExprEditor::nextError(), previewCommentLabel, BasicExpression::setExpr(), ExprGrapherWidget::update(), and BasicExpression::varmap.
Referenced by previewExpression(), verifiedAccept(), and verifiedApply().
void ExprDialog::clearExpression () slot
Definition at line 360 of file ExprDialog.cpp.
References browser, ExprBrowser::clearSelection(), editor, ExprGrapherWidget::expr, grapher, BasicExpression::setExpr(), ExprEditor::setExpr(), and ExprGrapherWidget::update().
Referenced by ExprDialog(), and setExpressionString().
void ExprDialog::closeEvent (QCloseEvent * event) protected
Definition at line 178 of file ExprDialog.cpp.
References dialogClosed().
void ExprDialog::dialogClosed () signal
Referenced by closeEvent(), reject(), and verifiedAccept().
int ExprDialog::exec ()
Definition at line 164 of file ExprDialog.cpp.
References browser, ExprBrowser::expandAll(), and ExprBrowser::getExpressionDirs().
Referenced by main().
void ExprDialog::expressionApplied () signal
Referenced by verifiedAccept(), and verifiedApply().
void ExprDialog::findHelper (QTextDocument::FindFlags flags) protected
Definition at line 286 of file ExprDialog.cpp.
References helpBrowser, helpFindBox, and prevFind.
Referenced by findNextInHelp(), and findPrevInHelp().
void ExprDialog::findNextInHelp () private slot
Definition at line 296 of file ExprDialog.cpp.
References findHelper().
Referenced by setupHelp().
void ExprDialog::findPrevInHelp () private slot
Definition at line 301 of file ExprDialog.cpp.
References findHelper().
Referenced by setupHelp().
std::string ExprDialog::getExpressionString () inline
Definition at line 70 of file ExprDialog.h.
References editor, and ExprEditor::getExpr().
Referenced by ExprShortEdit::expressionApplied(), and main().
void ExprDialog::keyPressEvent (QKeyEvent * event) protected
Definition at line 172 of file ExprDialog.cpp.
void ExprDialog::preview () signal
Referenced by ExprDialog(), and previewExpression().
void ExprDialog::previewExpression () private slot
Definition at line 305 of file ExprDialog.cpp.
References applyExpression(), and preview().
Referenced by ExprDialog().
void ExprDialog::reject () slot
Definition at line 184 of file ExprDialog.cpp.
References dialogClosed().
Referenced by ExprDialog().
void ExprDialog::setExpressionString (const std::string & str) inline
Definition at line 75 of file ExprDialog.h.
References clearExpression(), editor, and ExprEditor::setExpr().
Referenced by main(), and ExprShortEdit::showDetails().
void ExprDialog::setupHelp (QTabWidget * tab) private
Definition at line 234 of file ExprDialog.cpp.
References findNextInHelp(), findPrevInHelp(), helpBrowser, and helpFindBox.
Referenced by ExprDialog().
void ExprDialog::show ()
Definition at line 156 of file ExprDialog.cpp.
References browser, ExprBrowser::expandAll(), and ExprBrowser::getExpressionDirs().
Referenced by main(), and ExprShortEdit::showDetails().
void ExprDialog::showEditor (int idx)
Definition at line 144 of file ExprDialog.cpp.
References _currentEditorIdx, and showEditorTimer.
Referenced by ExprShortEdit::showDetails().
void ExprDialog::verifiedAccept () private slot
Definition at line 211 of file ExprDialog.cpp.
References applyExpression(), dialogClosed(), ExprGrapherWidget::expr, expressionApplied(), grapher, and SeExpr2::Expression::isValid().
Referenced by ExprDialog().
void ExprDialog::verifiedApply () private slot
Definition at line 190 of file ExprDialog.cpp.
References applyExpression(), ExprGrapherWidget::expr, expressionApplied(), grapher, and SeExpr2::Expression::isValid().
Referenced by ExprDialog().
Member Data Documentation
int ExprDialog::_currentEditorIdx private
Definition at line 66 of file ExprDialog.h.
Referenced by _showEditor(), and showEditor().
QPushButton* ExprDialog::acceptButton private
Definition at line 55 of file ExprDialog.h.
Referenced by ExprDialog().
QPushButton* ExprDialog::applyButton private
Definition at line 59 of file ExprDialog.h.
Referenced by ExprDialog().
ExprBrowser* ExprDialog::browser
Definition at line 51 of file ExprDialog.h.
Referenced by clearExpression(), exec(), ExprDialog(), show(), and ExprShortEdit::showDetails().
QPushButton* ExprDialog::cancelButton private
Definition at line 56 of file ExprDialog.h.
Referenced by ExprDialog().
QPushButton * ExprDialog::clearButton private
Definition at line 60 of file ExprDialog.h.
Referenced by ExprDialog().
ExprControlCollection* ExprDialog::controls private
Definition at line 57 of file ExprDialog.h.
Referenced by _showEditor(), and ExprDialog().
QTextCursor ExprDialog::cursor private
Definition at line 64 of file ExprDialog.h.
ExprEditor* ExprDialog::editor
Definition at line 50 of file ExprDialog.h.
Referenced by applyExpression(), clearExpression(), ExprDialog(), getExpressionString(), setExpressionString(), and ExprShortEdit::showDetails().
ExprGrapherWidget* ExprDialog::grapher private
Definition at line 53 of file ExprDialog.h.
Referenced by applyExpression(), clearExpression(), ExprDialog(), verifiedAccept(), and verifiedApply().
QTextBrowser* ExprDialog::helpBrowser private
Definition at line 63 of file ExprDialog.h.
Referenced by findHelper(), and setupHelp().
QLineEdit* ExprDialog::helpFindBox private
Definition at line 61 of file ExprDialog.h.
Referenced by findHelper(), and setupHelp().
QString ExprDialog::prevFind private
Definition at line 65 of file ExprDialog.h.
Referenced by findHelper().
QPushButton * ExprDialog::previewButton private
Definition at line 59 of file ExprDialog.h.
Referenced by ExprDialog().
QLabel* ExprDialog::previewCommentLabel private
Definition at line 54 of file ExprDialog.h.
Referenced by applyExpression(), and ExprDialog().
QPushButton * ExprDialog::saveAsButton private
Definition at line 59 of file ExprDialog.h.
Referenced by ExprDialog().
QPushButton * ExprDialog::saveButton private
Definition at line 59 of file ExprDialog.h.
Referenced by ExprDialog().
QPushButton* ExprDialog::saveLocalButton private
Definition at line 60 of file ExprDialog.h.
Referenced by ExprDialog().
QTimer* ExprDialog::showEditorTimer private
Definition at line 62 of file ExprDialog.h.
Referenced by ExprDialog(), and showEditor().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDialog.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDialog.cpp