SeExpr: SeExprEdExpressionTextEdit Class Reference
SeExprEdExpressionTextEdit Class Reference
#include <SeExprEditor.h>
Signals
void applyShortcut ()
void nextError ()
Public Member Functions
SeExprEdExpressionTextEdit (QWidget *parent=0)
~SeExprEdExpressionTextEdit ()
void updateStyle ()
Public Attributes
QCompleter * completer
SeExprEdCompletionModel * completionModel
Protected Member Functions
void showTip (const QString &string)
void hideTip ()
virtual void keyPressEvent (QKeyEvent *e)
void focusInEvent (QFocusEvent *e)
void focusOutEvent (QFocusEvent *e)
void mousePressEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *e)
void wheelEvent (QWheelEvent *e)
void contextMenuEvent (QContextMenuEvent *event)
Private Slots
void insertCompletion (const QString &completion)
Private Attributes
QToolTip * functionTip
std::map< std::string,
std::string > functionTooltips
SeExprEdHighlighter * highlighter
QStyle * lastStyleForHighlighter
SeExprEdPopupDocumentation * _tip
QAction * _popupEnabledAction
Detailed Description
Definition at line 48 of file SeExprEditor.h.
Constructor & Destructor Documentation
SeExprEdExpressionTextEdit::SeExprEdExpressionTextEdit (QWidget * parent = 0)
Definition at line 192 of file SeExprEditor.cpp.
References _popupEnabledAction, completer, completionModel, highlighter, and insertCompletion().
SeExprEdExpressionTextEdit::~SeExprEdExpressionTextEdit ()
Definition at line 89 of file SeExprEditor.cpp.
Member Function Documentation
void SeExprEdExpressionTextEdit::applyShortcut () [signal]
Referenced by keyPressEvent().
void SeExprEdExpressionTextEdit::contextMenuEvent (QContextMenuEvent * event) [protected]
Definition at line 347 of file SeExprEditor.cpp.
References _popupEnabledAction.
void SeExprEdExpressionTextEdit::focusInEvent (QFocusEvent * e) [protected]
Definition at line 219 of file SeExprEditor.cpp.
References completer.
Referenced by focusOutEvent().
void SeExprEdExpressionTextEdit::focusOutEvent (QFocusEvent * e) [protected]
Definition at line 225 of file SeExprEditor.cpp.
References focusInEvent(), and hideTip().
void SeExprEdExpressionTextEdit::hideTip () [protected]
Definition at line 376 of file SeExprEditor.cpp.
References _tip.
Referenced by focusOutEvent(), keyPressEvent(), mouseDoubleClickEvent(), and mousePressEvent().
void SeExprEdExpressionTextEdit::insertCompletion (const QString & completion) [private, slot]
Definition at line 381 of file SeExprEditor.cpp.
References completer.
Referenced by SeExprEdExpressionTextEdit().
void SeExprEdExpressionTextEdit::keyPressEvent (QKeyEvent * e) [protected, virtual]
Definition at line 262 of file SeExprEditor.cpp.
References _popupEnabledAction, applyShortcut(), completer, completionModel, SeExprEdCompletionModel::getDocString(), hideTip(), index(), nextError(), and showTip().
void SeExprEdExpressionTextEdit::mouseDoubleClickEvent (QMouseEvent * event) [protected]
Definition at line 237 of file SeExprEditor.cpp.
References hideTip().
void SeExprEdExpressionTextEdit::mousePressEvent (QMouseEvent * event) [protected]
Definition at line 231 of file SeExprEditor.cpp.
References hideTip().
void SeExprEdExpressionTextEdit::nextError () [signal]
Referenced by keyPressEvent().
void SeExprEdExpressionTextEdit::paintEvent (QPaintEvent * e) [protected]
Definition at line 243 of file SeExprEditor.cpp.
References SeExprEdHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
void SeExprEdExpressionTextEdit::showTip (const QString & string) [protected]
Definition at line 362 of file SeExprEditor.cpp.
References _tip, and SeExprEdPopupDocumentation::label.
Referenced by keyPressEvent().
void SeExprEdExpressionTextEdit::updateStyle ()
Definition at line 184 of file SeExprEditor.cpp.
References SeExprEdHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
Referenced by SeExprEditor::updateStyle().
void SeExprEdExpressionTextEdit::wheelEvent (QWheelEvent * e) [protected]
Definition at line 253 of file SeExprEditor.cpp.
Member Data Documentation
QAction* SeExprEdExpressionTextEdit::_popupEnabledAction [private]
Definition at line 57 of file SeExprEditor.h.
Referenced by contextMenuEvent(), keyPressEvent(), and SeExprEdExpressionTextEdit().
SeExprEdPopupDocumentation* SeExprEdExpressionTextEdit::_tip [private]
Definition at line 56 of file SeExprEditor.h.
Referenced by hideTip(), and showTip().
QCompleter* SeExprEdExpressionTextEdit::completer
Definition at line 59 of file SeExprEditor.h.
Referenced by focusInEvent(), insertCompletion(), keyPressEvent(), SeExprEditor::rebuildControls(), SeExprEdExpressionTextEdit(), and SeExprEditor::updateCompleter().
SeExprEdCompletionModel* SeExprEdExpressionTextEdit::completionModel
Definition at line 60 of file SeExprEditor.h.
Referenced by SeExprEditor::clearExtraCompleters(), keyPressEvent(), SeExprEditor::rebuildControls(), SeExprEditor::registerExtraFunction(), SeExprEditor::registerExtraVariable(), SeExprEditor::replaceExtras(), SeExprEdExpressionTextEdit(), and SeExprEditor::updateCompleter().
QToolTip* SeExprEdExpressionTextEdit::functionTip [private]
Definition at line 52 of file SeExprEditor.h.
std::map<std::string,std::string> SeExprEdExpressionTextEdit::functionTooltips [private]
Definition at line 53 of file SeExprEditor.h.
SeExprEdHighlighter* SeExprEdExpressionTextEdit::highlighter [private]
Definition at line 54 of file SeExprEditor.h.
Referenced by paintEvent(), SeExprEdExpressionTextEdit(), and updateStyle().
QStyle* SeExprEdExpressionTextEdit::lastStyleForHighlighter [private]
Definition at line 55 of file SeExprEditor.h.
Referenced by paintEvent(), and updateStyle().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEditor.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEditor.cpp