SeExpr: SeExpr::PrintFuncX Class Reference
SeExpr::PrintFuncX Class Reference
Classes
struct Data
Public Member Functions
PrintFuncX ()
Private Member Functions
virtual bool prep (SeExprFuncNode *node, bool wantVec, std::string &error)
virtual void eval (const SeExprFuncNode *node, SeVec3d &result) const
Detailed Description
Definition at line 1438 of file SeExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr::PrintFuncX::PrintFuncX () [inline]
Definition at line 1540 of file SeExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr::PrintFuncX::eval (const SeExprFuncNode * node, SeVec3d & result) const [inline, private, virtual]
evaluate the expression. the given node is where in the parse tree the evaluation is for
Implements SeExprFuncX.
Definition at line 1514 of file SeExprBuiltins.cpp.
References SeExprNode::child(), data, SeExprNode::eval(), SeExpr::PrintFuncX::Data::format, SeExprFuncNode::getData(), and SeExpr::PrintFuncX::Data::ranges.
virtual bool SeExpr::PrintFuncX::prep (SeExprFuncNode * node, bool wantVec, std::string & error) [inline, private, virtual]
prep the expression by doing all type checking argument checking, etc. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprFuncX.
Definition at line 1446 of file SeExprBuiltins.cpp.
References SeExprNode::addError(), SeExprNode::child(), data, SeExpr::PrintFuncX::Data::format, SeExprFuncNode::getStrArg(), SeExprFuncNode::isStrArg(), SeExprFuncNode::nargs(), SeExprNode::prep(), SeExpr::PrintFuncX::Data::ranges, and SeExprFuncNode::setData().
The documentation for this class was generated from the following file:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprBuiltins.cpp