SeExpr: ExprColorFrame Class Reference
ExprColorFrame Class Reference
#include <ExprColorSwatch.h>
Signals
void selValChangedSignal (SeExpr2::Vec3d value)
void swatchChanged (QColor color)
void deleteSwatch (ExprColorFrame *swatch)
Public Member Functions
ExprColorFrame (SeExpr2::Vec3d value, QWidget *parent=0)
~ExprColorFrame ()
void setValue (const SeExpr2::Vec3d &value)
SeExpr2::Vec3d getValue () const
bool selected ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
Private Slots
void deleteSwatchMenu (const QPoint &pos)
Private Attributes
SeExpr2::Vec3d _value
QColor _color
bool _selected
Detailed Description
Definition at line 12 of file ExprColorSwatch.h.
Constructor & Destructor Documentation
ExprColorFrame::ExprColorFrame (SeExpr2::Vec3d value, QWidget * parent = 0)
Definition at line 26 of file ExprColorSwatch.cpp.
References _value, and setValue().
ExprColorFrame::~ExprColorFrame () inline
Definition at line 17 of file ExprColorSwatch.h.
Member Function Documentation
void ExprColorFrame::deleteSwatch (ExprColorFrame * swatch) signal
Referenced by deleteSwatchMenu().
void ExprColorFrame::deleteSwatchMenu (const QPoint & pos) private slot
Definition at line 82 of file ExprColorSwatch.cpp.
References deleteSwatch().
Referenced by mouseReleaseEvent().
SeExpr2::Vec3d ExprColorFrame::getValue () const
Definition at line 46 of file ExprColorSwatch.cpp.
References _value.
Referenced by ExprColorSwatchWidget::getSwatchColor(), and ExprColorSwatchWidget::internalSwatchChanged().
void ExprColorFrame::mouseReleaseEvent (QMouseEvent * event) protected virtual
Definition at line 58 of file ExprColorSwatch.cpp.
References _color, _value, deleteSwatchMenu(), selValChangedSignal(), and swatchChanged().
void ExprColorFrame::paintEvent (QPaintEvent * event) protected virtual
Definition at line 51 of file ExprColorSwatch.cpp.
References _color, and p.
bool ExprColorFrame::selected () inline
Definition at line 21 of file ExprColorSwatch.h.
References _selected.
void ExprColorFrame::selValChangedSignal (SeExpr2::Vec3d value) signal
Referenced by mouseReleaseEvent().
void ExprColorFrame::setValue (const SeExpr2::Vec3d & value)
Definition at line 37 of file ExprColorSwatch.cpp.
References _color, _value, and value().
Referenced by ExprColorFrame(), and ExprColorSwatchWidget::setSwatchColor().
void ExprColorFrame::swatchChanged (QColor color) signal
Referenced by mouseReleaseEvent().
Member Data Documentation
QColor ExprColorFrame::_color private
Definition at line 37 of file ExprColorSwatch.h.
Referenced by mouseReleaseEvent(), paintEvent(), and setValue().
bool ExprColorFrame::_selected private
Definition at line 38 of file ExprColorSwatch.h.
Referenced by selected().
SeExpr2::Vec3d ExprColorFrame::_value private
Definition at line 36 of file ExprColorSwatch.h.
Referenced by ExprColorFrame(), getValue(), mouseReleaseEvent(), and setValue().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorSwatch.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorSwatch.cpp