SeExpr: SeExprEdAnimCurveControl Class Reference
SeExprEdAnimCurveControl Class Reference
#include <SeExprEdControl.h>
Public Types
typedef void(* AnimCurveCallback)(const std::string &, animlib::AnimCurve &curve)
Public Slots
void editGraphClicked ()
Public Member Functions
SeExprEdAnimCurveControl (int id, SeExprEdAnimCurveEditable *curveEditable)
Static Public Member Functions
static void setAnimCurveCallback (AnimCurveCallback callback)
Private Slots
void refreshClicked ()
Private Attributes
SeExprEdAnimCurveEditable * _editable
SeExprEdGraphPreview * _preview
Static Private Attributes
static AnimCurveCallback callback = 0
Detailed Description
Definition at line 257 of file SeExprEdControl.h.
Member Typedef Documentation
typedef void(* SeExprEdAnimCurveControl::AnimCurveCallback)(const std::string &, animlib::AnimCurve &curve)
Definition at line 265 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdAnimCurveControl::SeExprEdAnimCurveControl (int id, SeExprEdAnimCurveEditable * curveEditable)
Definition at line 730 of file SeExprEdControl.cpp.
References _editable, _preview, editGraphClicked(), graphXPM, SeExprEdControl::hbox, SeExprEdAnimCurveEditable::link, refreshClicked(), and refreshXPM.
Member Function Documentation
void SeExprEdAnimCurveControl::editGraphClicked () [slot]
Definition at line 776 of file SeExprEdControl.cpp.
References _editable, SeExprEdControl::_id, _preview, and SeExprEdControl::controlChanged().
Referenced by SeExprEdAnimCurveControl(), and SeExprEdControlCollection::showEditor().
void SeExprEdAnimCurveControl::refreshClicked () [private, slot]
Definition at line 764 of file SeExprEdControl.cpp.
References _editable, SeExprEdControl::_id, _preview, callback, SeExprEdControl::controlChanged(), and SeExprEdAnimCurveEditable::link.
Referenced by SeExprEdAnimCurveControl().
void SeExprEdAnimCurveControl::setAnimCurveCallback (AnimCurveCallback callback) [static]
Definition at line 808 of file SeExprEdControl.cpp.
References callback.
Member Data Documentation
SeExprEdAnimCurveEditable* SeExprEdAnimCurveControl::_editable [private]
Reimplemented from SeExprEdControl.
Definition at line 259 of file SeExprEdControl.h.
Referenced by editGraphClicked(), refreshClicked(), and SeExprEdAnimCurveControl().
SeExprEdGraphPreview* SeExprEdAnimCurveControl::_preview [private]
Definition at line 262 of file SeExprEdControl.h.
Referenced by editGraphClicked(), refreshClicked(), and SeExprEdAnimCurveControl().
SeExprEdAnimCurveControl::AnimCurveCallback SeExprEdAnimCurveControl::callback = 0 [static, private]
Definition at line 275 of file SeExprEdControl.h.
Referenced by refreshClicked(), and setAnimCurveCallback().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp