SeExpr: SeExprEdChannelSlider Class Reference
SeExprEdChannelSlider Class Reference
Channel Slider (i.e. for colors).
#include <SeExprEdControl.h>
Public Slots
void setValue (float value)
Signals
void valueChanged (int id, float value)
Public Member Functions
SeExprEdChannelSlider (int id, QWidget *parent)
virtual void paintEvent (QPaintEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void wheelEvent (QWheelEvent *e)
float value () const
void setDisplayColor (QColor c)
Private Attributes
int _id
float _value
QColor _col
Detailed Description
Channel Slider (i.e. for colors).
Definition at line 130 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdChannelSlider::SeExprEdChannelSlider (int id, QWidget * parent)
Definition at line 223 of file SeExprEdControl.cpp.
Member Function Documentation
void SeExprEdChannelSlider::mouseMoveEvent (QMouseEvent * e) [virtual]
Definition at line 244 of file SeExprEdControl.cpp.
References SeExpr::clamp(), and setValue().
Referenced by mousePressEvent().
void SeExprEdChannelSlider::mousePressEvent (QMouseEvent * e) [virtual]
Definition at line 238 of file SeExprEdControl.cpp.
References mouseMoveEvent().
void SeExprEdChannelSlider::paintEvent (QPaintEvent * e) [virtual]
Definition at line 228 of file SeExprEdControl.cpp.
References _col, _value, p, and x.
void SeExprEdChannelSlider::setDisplayColor (QColor c) [inline]
Definition at line 140 of file SeExprEdControl.h.
References _col.
Referenced by SeExprEdVectorControl::SeExprEdVectorControl().
void SeExprEdChannelSlider::setValue (float value) [slot]
Definition at line 250 of file SeExprEdControl.cpp.
References _id, _value, and valueChanged().
Referenced by mouseMoveEvent(), and SeExprEdVectorControl::updateControl().
float SeExprEdChannelSlider::value () const [inline]
Definition at line 139 of file SeExprEdControl.h.
References _value.
void SeExprEdChannelSlider::valueChanged (int id, float value) [signal]
Referenced by setValue().
virtual void SeExprEdChannelSlider::wheelEvent (QWheelEvent * e) [inline, virtual]
Definition at line 138 of file SeExprEdControl.h.
Member Data Documentation
QColor SeExprEdChannelSlider::_col [private]
Definition at line 150 of file SeExprEdControl.h.
Referenced by paintEvent(), and setDisplayColor().
int SeExprEdChannelSlider::_id [private]
Definition at line 148 of file SeExprEdControl.h.
Referenced by setValue().
float SeExprEdChannelSlider::_value [private]
Definition at line 149 of file SeExprEdControl.h.
Referenced by paintEvent(), setValue(), and value().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp