SeExpr: SeExpr2::Context Class Reference
SeExpr2::Context Class Reference
#include <Context.h>
Public Member Functions
bool lookupParameter (const std::string &parameterName, std::string &value) const
Lookup a Context parameter by name.
void setParameter (const std::string &parameterName, const std::string &value)
Set a parameter. NOTE: this must be done when no threads are accessing lookupParameter for safety.
Context * createChildContext () const
Create a context that is a child of this context.
void setParent (const Context *context)
const Context * getParent () const
bool hasContext (const Context *context) const
Static Public Member Functions
static Context & global ()
The global default context of the seexpr.
Private Types
typedef std::map< std::string,
std::string > ParameterMap
Private Member Functions
Context (const Context &)
Context & operator= (const Context &)
Context (const Context *parent)
Private Attributes
const Context * _parent
The parent scope.
ParameterMap _parameters
Attribute/value pairs.
Detailed Description
Definition at line 24 of file Context.h.
Member Typedef Documentation
typedef std::map<std::string, std::string> SeExpr2::Context::ParameterMap private
Definition at line 66 of file Context.h.
Constructor & Destructor Documentation
SeExpr2::Context::Context (const Context &) private
Private constructor and un-implemented default/copy/assignment (it is required that we derive from the global context via createChildContext)
Referenced by createChildContext().
Context::Context (const Context * parent) private
Definition at line 21 of file Context.cpp.
Member Function Documentation
Context * Context::createChildContext () const
Create a context that is a child of this context.
Definition at line 27 of file Context.cpp.
References Context().
const Context* SeExpr2::Context::getParent () const inline
Definition at line 44 of file Context.h.
References _parent.
Context & Context::global () static
The global default context of the seexpr.
Definition at line 29 of file Context.cpp.
References context.
bool SeExpr2::Context::hasContext (const Context * context) const inline
Definition at line 46 of file Context.h.
References _parent, and hasContext().
Referenced by hasContext().
bool SeExpr2::Context::lookupParameter (const std::string & parameterName, std::string & value) const inline
Lookup a Context parameter by name.
Definition at line 27 of file Context.h.
References _parameters, _parent, it, and lookupParameter().
Referenced by SeExpr2::ContextUtils::IsThreading(), and lookupParameter().
Context& SeExpr2::Context::operator= (const Context &) private
void Context::setParameter (const std::string & parameterName, const std::string & value)
Set a parameter. NOTE: this must be done when no threads are accessing lookupParameter for safety.
Definition at line 23 of file Context.cpp.
References _parameters, and value().
Referenced by SeExpr2::ContextUtils::DisableThreading().
void SeExpr2::Context::setParent (const Context * context) inline
Definition at line 43 of file Context.h.
References _parent, and context.
Member Data Documentation
ParameterMap SeExpr2::Context::_parameters private
Attribute/value pairs.
Definition at line 68 of file Context.h.
Referenced by lookupParameter(), and setParameter().
const Context* SeExpr2::Context::_parent private
The parent scope.
Definition at line 63 of file Context.h.
Referenced by getParent(), hasContext(), lookupParameter(), and setParent().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Context.h
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Context.cpp