SeExpr: SeExprEdGrapherView Class Reference
SeExprEdGrapherView Class Reference
#include <SeExprEdGrapher2d.h>
Signals
void scaleValueManipulated ()
void clicked ()
Public Member Functions
SeExprEdGrapherView (SeExprEdGrapherWidget &widget, QWidget *parent, int width, int height)
virtual ~SeExprEdGrapherView ()
void update ()
void setWindow (float xmin, float xmax, float ymin, float ymax, float z)
void getWindow (float &xmin, float &xmax, float &ymin, float &ymax, float &z)
Protected Member Functions
void clear ()
void paintGL ()
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Protected Attributes
int event_oldx
int event_oldy
Private Attributes
SeExprEdGrapherWidget & widget
float * _image
int _width
int _height
float xmin
float xmax
float ymin
float ymax
float z
float dx
float dy
bool scaling
bool translating
Detailed Description
Definition at line 27 of file SeExprEdGrapher2d.h.
Constructor & Destructor Documentation
SeExprEdGrapherView::SeExprEdGrapherView (SeExprEdGrapherWidget & widget, QWidget * parent, int width, int height)
Definition at line 90 of file SeExprEdGrapher2d.cpp.
References _height, _image, _width, clear(), and setWindow().
SeExprEdGrapherView::~SeExprEdGrapherView () [virtual]
Definition at line 104 of file SeExprEdGrapher2d.cpp.
References _image.
Member Function Documentation
void SeExprEdGrapherView::clear () [protected]
Definition at line 130 of file SeExprEdGrapher2d.cpp.
References _height, _image, _width, and index().
Referenced by SeExprEdGrapherView(), and update().
void SeExprEdGrapherView::clicked () [signal]
Referenced by mouseReleaseEvent().
void SeExprEdGrapherView::getWindow (float & xmin, float & xmax, float & ymin, float & ymax, float & z)
Definition at line 121 of file SeExprEdGrapher2d.cpp.
Referenced by SeExprEdGrapherWidget::scaleValueEdited(), SeExprEdGrapherWidget::scaleValueManipulated(), and SeExprEdGrapherWidget::SeExprEdGrapherWidget().
void SeExprEdGrapherView::mouseMoveEvent (QMouseEvent * event) [protected]
Definition at line 163 of file SeExprEdGrapher2d.cpp.
References dx, dy, event_oldx, event_oldy, pow(), scaleValueManipulated(), scaling, setWindow(), translating, update(), x, xmax, xmin, y, ymax, ymin, and z.
void SeExprEdGrapherView::mousePressEvent (QMouseEvent * event) [protected]
Definition at line 142 of file SeExprEdGrapher2d.cpp.
References event_oldx, event_oldy, scaling, and translating.
void SeExprEdGrapherView::mouseReleaseEvent (QMouseEvent * event) [protected]
Definition at line 156 of file SeExprEdGrapher2d.cpp.
References clicked(), scaling, and translating.
void SeExprEdGrapherView::paintGL () [protected]
Definition at line 228 of file SeExprEdGrapher2d.cpp.
References _height, _image, and _width.
void SeExprEdGrapherView::scaleValueManipulated () [signal]
Referenced by mouseMoveEvent().
void SeExprEdGrapherView::setWindow (float xmin, float xmax, float ymin, float ymax, float z)
Definition at line 109 of file SeExprEdGrapher2d.cpp.
References _height, _width, dx, and dy.
Referenced by mouseMoveEvent(), SeExprEdGrapherWidget::scaleValueEdited(), and SeExprEdGrapherView().
void SeExprEdGrapherView::update ()
Definition at line 194 of file SeExprEdGrapher2d.cpp.
References _height, _image, _width, clear(), dx, dy, SeExpression::evaluate(), SeExprEdGrapherWidget::expr, index(), SeExpression::isValid(), SeExprEdExpression::P, SeExprEdExpression::u, SeExprEdExpression::v, value(), widget, x, xmin, y, ymin, and z.
Referenced by mouseMoveEvent(), and SeExprEdGrapherWidget::update().
Member Data Documentation
int SeExprEdGrapherView::_height [private]
Definition at line 54 of file SeExprEdGrapher2d.h.
Referenced by clear(), paintGL(), SeExprEdGrapherView(), setWindow(), and update().
float* SeExprEdGrapherView::_image [private]
Definition at line 52 of file SeExprEdGrapher2d.h.
Referenced by clear(), paintGL(), SeExprEdGrapherView(), update(), and ~SeExprEdGrapherView().
int SeExprEdGrapherView::_width [private]
Definition at line 53 of file SeExprEdGrapher2d.h.
Referenced by clear(), paintGL(), SeExprEdGrapherView(), setWindow(), and update().
float SeExprEdGrapherView::dx [private]
Definition at line 57 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), setWindow(), and update().
float SeExprEdGrapherView::dy [private]
Definition at line 57 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), setWindow(), and update().
int SeExprEdGrapherView::event_oldx [protected]
Definition at line 45 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
int SeExprEdGrapherView::event_oldy [protected]
Definition at line 45 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
bool SeExprEdGrapherView::scaling [private]
Definition at line 60 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool SeExprEdGrapherView::translating [private]
Definition at line 60 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
SeExprEdGrapherWidget& SeExprEdGrapherView::widget [private]
Definition at line 29 of file SeExprEdGrapher2d.h.
Referenced by update().
float SeExprEdGrapherView::xmax [private]
Definition at line 56 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent().
float SeExprEdGrapherView::xmin [private]
Definition at line 56 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), and update().
float SeExprEdGrapherView::ymax [private]
Definition at line 56 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent().
float SeExprEdGrapherView::ymin [private]
Definition at line 56 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), and update().
float SeExprEdGrapherView::z [private]
Definition at line 56 of file SeExprEdGrapher2d.h.
Referenced by mouseMoveEvent(), and update().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdGrapher2d.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdGrapher2d.cpp