SeExpr: SeExpr2::ExprVarRef Class Reference
SeExpr2::ExprVarRef Class Reference abstract
abstract class for implementing variable references
#include <Expression.h>
Public Member Functions
ExprVarRef (const ExprType &type)
virtual ~ExprVarRef ()
virtual void setType (const ExprType &type)
sets (current) type to given type
virtual ExprType type () const
returns (current) type
virtual void eval (double *result)=0
returns this variable's value by setting result
virtual void eval (const char **resultStr)=0
Private Member Functions
ExprVarRef ()
Private Attributes
ExprType _type
Detailed Description
abstract class for implementing variable references
Definition at line 45 of file Expression.h.
Constructor & Destructor Documentation
SeExpr2::ExprVarRef::ExprVarRef () inline private
Definition at line 46 of file Expression.h.
SeExpr2::ExprVarRef::ExprVarRef (const ExprType & type) inline
Definition at line 49 of file Expression.h.
virtual SeExpr2::ExprVarRef::~ExprVarRef () inline virtual
Definition at line 51 of file Expression.h.
Member Function Documentation
virtual void SeExpr2::ExprVarRef::eval (double * result) pure virtual
returns this variable's value by setting result
Implemented in SeExpr2::VarBlockCreator::Ref, SeExpr2::GlobalStr, BasicExpression::VectorRef, BasicExpression::ScalarRef, and SeExpr2::GlobalFP.
virtual void SeExpr2::ExprVarRef::eval (const char ** resultStr) pure virtual
Implemented in SeExpr2::VarBlockCreator::Ref, SeExpr2::GlobalStr, BasicExpression::VectorRef, SeExpr2::GlobalFP, and BasicExpression::ScalarRef.
virtual void SeExpr2::ExprVarRef::setType (const ExprType & type) inline virtual
sets (current) type to given type
Definition at line 54 of file Expression.h.
References _type, and type().
virtual ExprType SeExpr2::ExprVarRef::type () const inline virtual
returns (current) type
Definition at line 59 of file Expression.h.
References _type.
Referenced by SeExpr2::ExprVarNode::buildInterpreter(), SeExpr2::GlobalFP::eval(), SeExpr2::GlobalFP::isVec(), SeExpr2::ExprVarNode::prep(), and setType().
Member Data Documentation
ExprType SeExpr2::ExprVarRef::_type private
Definition at line 68 of file Expression.h.
Referenced by setType(), and type().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Expression.h