SeExpr: ExprGrapherWidget Class Reference
ExprGrapherWidget Class Reference
#include <ExprGrapher2d.h>
Signals
void preview ()
Public Member Functions
ExprGrapherWidget (QWidget *parent, int width, int height)
void update ()
Public Attributes
ExprGrapherView * view
BasicExpression expr
Private Slots
void scaleValueEdited ()
void scaleValueManipulated ()
void forwardPreview ()
Private Attributes
QLineEdit * scale
Detailed Description
Definition at line 71 of file ExprGrapher2d.h.
Constructor & Destructor Documentation
ExprGrapherWidget::ExprGrapherWidget (QWidget * parent, int width, int height)
Definition at line 30 of file ExprGrapher2d.cpp.
References forwardPreview(), ExprGrapherView::getWindow(), scale, scaleValueEdited(), scaleValueManipulated(), view, and z.
Member Function Documentation
void ExprGrapherWidget::forwardPreview () private slot
Definition at line 92 of file ExprGrapher2d.cpp.
References preview().
Referenced by ExprGrapherWidget().
void ExprGrapherWidget::preview () signal
Referenced by forwardPreview().
void ExprGrapherWidget::scaleValueEdited () private slot
Definition at line 61 of file ExprGrapher2d.cpp.
References ExprGrapherView::getWindow(), scale, ExprGrapherView::setWindow(), view, and z.
Referenced by ExprGrapherWidget().
void ExprGrapherWidget::scaleValueManipulated () private slot
Definition at line 78 of file ExprGrapher2d.cpp.
References ExprGrapherView::getWindow(), scale, view, and z.
Referenced by ExprGrapherWidget().
void ExprGrapherWidget::update ()
Definition at line 85 of file ExprGrapher2d.cpp.
References expr, SeExpr2::Expression::setDesiredReturnType(), ExprGrapherView::update(), and view.
Referenced by ExprDialog::applyExpression(), and ExprDialog::clearExpression().
Member Data Documentation
BasicExpression ExprGrapherWidget::expr
Definition at line 78 of file ExprGrapher2d.h.
Referenced by ExprDialog::applyExpression(), ExprDialog::clearExpression(), ExprGrapherView::update(), update(), ExprDialog::verifiedAccept(), and ExprDialog::verifiedApply().
QLineEdit* ExprGrapherWidget::scale private
Definition at line 74 of file ExprGrapher2d.h.
Referenced by ExprGrapherWidget(), scaleValueEdited(), and scaleValueManipulated().
ExprGrapherView* ExprGrapherWidget::view
Definition at line 77 of file ExprGrapher2d.h.
Referenced by ExprGrapherWidget(), scaleValueEdited(), scaleValueManipulated(), and update().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprGrapher2d.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprGrapher2d.cpp