SeExpr: ExprChannelSlider Class Reference
ExprChannelSlider Class Reference
Channel Slider (i.e. for colors)
#include <ExprControl.h>
Public Slots
void setValue (float value)
Signals
void valueChanged (int id, float value)
Public Member Functions
ExprChannelSlider (int id, QWidget *parent)
virtual void paintEvent (QPaintEvent *e)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void wheelEvent (QWheelEvent *e)
float value () const
void setDisplayColor (QColor c)
Private Attributes
int _id
float _value
QColor _col
Detailed Description
Channel Slider (i.e. for colors)
Definition at line 140 of file ExprControl.h.
Constructor & Destructor Documentation
ExprChannelSlider::ExprChannelSlider (int id, QWidget * parent)
Definition at line 227 of file ExprControl.cpp.
Member Function Documentation
void ExprChannelSlider::mouseMoveEvent (QMouseEvent * e) virtual
Definition at line 248 of file ExprControl.cpp.
References SeExpr2::clamp(), and setValue().
Referenced by mousePressEvent().
void ExprChannelSlider::mousePressEvent (QMouseEvent * e) virtual
Definition at line 242 of file ExprControl.cpp.
References mouseMoveEvent().
void ExprChannelSlider::paintEvent (QPaintEvent * e) virtual
Definition at line 232 of file ExprControl.cpp.
References _col, _value, p, and x.
void ExprChannelSlider::setDisplayColor (QColor c) inline
Definition at line 150 of file ExprControl.h.
References _col.
Referenced by VectorControl::VectorControl().
void ExprChannelSlider::setValue (float value) slot
Definition at line 254 of file ExprControl.cpp.
References _id, _value, value(), and valueChanged().
Referenced by mouseMoveEvent(), and VectorControl::updateControl().
float ExprChannelSlider::value () const inline
Definition at line 149 of file ExprControl.h.
References _value.
Referenced by setValue().
void ExprChannelSlider::valueChanged (int id, float value) signal
Referenced by setValue().
virtual void ExprChannelSlider::wheelEvent (QWheelEvent * e) inline virtual
Definition at line 148 of file ExprControl.h.
Member Data Documentation
QColor ExprChannelSlider::_col private
Definition at line 160 of file ExprControl.h.
Referenced by paintEvent(), and setDisplayColor().
int ExprChannelSlider::_id private
Definition at line 158 of file ExprControl.h.
Referenced by setValue().
float ExprChannelSlider::_value private
Definition at line 159 of file ExprControl.h.
Referenced by paintEvent(), setValue(), and value().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp