SeExpr: SeExprInternal::DebugLock< T > Class Template Reference
SeExprInternal::DebugLock< T > Class Template Reference
#include <SeMutex.h>
Public Member Functions
DebugLock ()
void lock ()
void unlock ()
bool locked ()
Private Attributes
int _locked
Detailed Description
template<class T>
class SeExprInternal::DebugLock< T >
Definition at line 47 of file SeMutex.h.
Constructor & Destructor Documentation
template<class T > SeExprInternal::DebugLock< T >::DebugLock () [inline]
Definition at line 49 of file SeMutex.h.
Member Function Documentation
template<class T > void SeExprInternal::DebugLock< T >::lock () [inline]
Definition at line 50 of file SeMutex.h.
References SeExprInternal::DebugLock< T >::_locked.
Referenced by SeExprFunc::define(), SeExprFunc::getDocString(), SeExprFunc::getFunctionNames(), and SeExprFunc::lookup().
template<class T > bool SeExprInternal::DebugLock< T >::locked () [inline]
Definition at line 52 of file SeMutex.h.
References SeExprInternal::DebugLock< T >::_locked.
template<class T > void SeExprInternal::DebugLock< T >::unlock () [inline]
Definition at line 51 of file SeMutex.h.
References SeExprInternal::DebugLock< T >::_locked.
Referenced by SeExprFunc::define(), SeExprFunc::getDocString(), SeExprFunc::getFunctionNames(), and SeExprFunc::lookup().
Member Data Documentation
template<class T > int SeExprInternal::DebugLock< T >::_locked [private]
Definition at line 54 of file SeMutex.h.
Referenced by SeExprInternal::DebugLock< T >::lock(), SeExprInternal::DebugLock< T >::locked(), and SeExprInternal::DebugLock< T >::unlock().
The documentation for this class was generated from the following file:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeMutex.h