SeExpr: SeExprVarNode Class Reference
SeExprVarNode Class Reference
Node that references a variable.
#include <SeExprNode.h>
Classes
struct Data
base class for custom instance data
Public Member Functions
SeExprVarNode (const SeExpression *expr, const char *name)
virtual bool prep (bool wantVec, std::string &error)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
const char * name () const
void setData (Data *data) const
Data * getData () const
Private Attributes
std::string _name
SeExprVarRef * _var
Data * _data
Detailed Description
Node that references a variable.
Definition at line 404 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprVarNode::SeExprVarNode (const SeExpression * expr, const char * name) [inline]
Definition at line 407 of file SeExprNode.h.
References SeExpression::addVar().
Member Function Documentation
void SeExprVarNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 691 of file SeExprNode.cpp.
References _var, and SeExprVarRef::eval().
Data* SeExprVarNode::getData () const [inline]
Definition at line 418 of file SeExprNode.h.
References _data.
const char* SeExprVarNode::name () const [inline]
Definition at line 413 of file SeExprNode.h.
References _name.
Referenced by prep().
bool SeExprVarNode::prep (bool wantVec, std::string & error) [virtual]
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprNode.
Definition at line 676 of file SeExprNode.cpp.
References SeExprNode::_expr, SeExprNode::_isVec, _var, SeExprNode::addError(), SeExprVarRef::isVec(), name(), SeExpression::resolveLocalVar(), and SeExpression::resolveVar().
void SeExprVarNode::setData (Data * data) const [inline]
Definition at line 417 of file SeExprNode.h.
References _data.
Member Data Documentation
Data* SeExprVarNode::_data [mutable, private]
Definition at line 423 of file SeExprNode.h.
Referenced by getData(), and setData().
std::string SeExprVarNode::_name [private]
Definition at line 421 of file SeExprNode.h.
Referenced by name().
SeExprVarRef* SeExprVarNode::_var [private]
Definition at line 422 of file SeExprNode.h.
Referenced by eval(), and prep().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp