SeExpr: SeExprSubNode Class Reference
SeExprSubNode Class Reference
Node that implements an arithmetic operator.
#include <SeExprNode.h>
Public Member Functions
SeExprSubNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that implements an arithmetic operator.
Definition at line 321 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprSubNode::SeExprSubNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 324 of file SeExprNode.h.
Member Function Documentation
void SeExprSubNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 535 of file SeExprNode.cpp.
References SeExprNode::_isVec, a, b, SeExprNode::child(), SeExprNode::eval(), and SeExprNode::isVec().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.cpp