SeExpr: ExprHighlighter Class Reference
ExprHighlighter Class Reference
#include <ExprHighlighter.h>
Classes
struct HighlightingRule
Public Member Functions
ExprHighlighter (QTextDocument *parent)
ExprHighlighter (QTextEdit *edit)
void fixStyle (const QPalette &palette)
void init ()
void highlightBlock (const QString &text)
Private Attributes
QVector< HighlightingRule > highlightingRules
QTextCharFormat singleLineCommentFormat
QTextCharFormat variableFormat
QTextCharFormat numberFormat
QTextCharFormat operatorFormat
int lightness
Detailed Description
Definition at line 27 of file ExprHighlighter.h.
Constructor & Destructor Documentation
ExprHighlighter::ExprHighlighter (QTextDocument * parent) inline
Definition at line 42 of file ExprHighlighter.h.
References init().
ExprHighlighter::ExprHighlighter (QTextEdit * edit) inline
Definition at line 48 of file ExprHighlighter.h.
References init().
Member Function Documentation
void ExprHighlighter::fixStyle (const QPalette & palette) inline
Definition at line 54 of file ExprHighlighter.h.
References init(), and lightness.
Referenced by ExprShortTextEdit::ExprShortTextEdit(), ExprTextEdit::paintEvent(), ExprShortTextEdit::paintEvent(), and ExprTextEdit::updateStyle().
void ExprHighlighter::highlightBlock (const QString & text) inline
Definition at line 93 of file ExprHighlighter.h.
References expression, ExprHighlighter::HighlightingRule::format, highlightingRules, index(), SeExpr2::length(), and ExprHighlighter::HighlightingRule::pattern.
void ExprHighlighter::init () inline
Definition at line 60 of file ExprHighlighter.h.
References ExprHighlighter::HighlightingRule::format, highlightingRules, lightness, numberFormat, ExprHighlighter::HighlightingRule::pattern, singleLineCommentFormat, and variableFormat.
Referenced by ExprHighlighter(), and fixStyle().
Member Data Documentation
QVector<HighlightingRule> ExprHighlighter::highlightingRules private
Definition at line 33 of file ExprHighlighter.h.
Referenced by highlightBlock(), and init().
int ExprHighlighter::lightness private
Definition at line 39 of file ExprHighlighter.h.
Referenced by fixStyle(), and init().
QTextCharFormat ExprHighlighter::numberFormat private
Definition at line 36 of file ExprHighlighter.h.
Referenced by init().
QTextCharFormat ExprHighlighter::operatorFormat private
Definition at line 37 of file ExprHighlighter.h.
QTextCharFormat ExprHighlighter::singleLineCommentFormat private
Definition at line 34 of file ExprHighlighter.h.
Referenced by init().
QTextCharFormat ExprHighlighter::variableFormat private
Definition at line 35 of file ExprHighlighter.h.
Referenced by init().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprHighlighter.h