SeExpr: CurveControl Class Reference
CurveControl Class Reference
Control for editing a normal curve ramp.
#include <ExprControl.h>
Public Member Functions
CurveControl (int id, CurveEditable *stringEditable)
Public Member Functions inherited from ExprControl
ExprControl (int id, Editable *editable, bool showColorLink)
virtual ~ExprControl ()
virtual QColor getColor ()
Interface for getting the color (used for linked color picking)
virtual void setColor (QColor color)
Interface for setting the color (used for linked color picking)
void linkDisconnect (int newId)
Private Slots
void curveChanged ()
Private Attributes
CurveEditable * _curveEditable
curve model
ExprCurve * _curve
curve edit widget
Additional Inherited Members
Public Slots inherited from ExprControl
void linkStateChange (int state)
Signals inherited from ExprControl
void controlChanged (int id)
void linkColorEdited (int id, QColor color)
void linkColorLink (int id)
Protected Attributes inherited from ExprControl
int _id
bool _updating
QHBoxLayout * hbox
QCheckBox * _colorLinkCB
QLabel * _label
Editable * _editable
Detailed Description
Control for editing a normal curve ramp.
Definition at line 234 of file ExprControl.h.
Constructor & Destructor Documentation
CurveControl::CurveControl (int id, CurveEditable * stringEditable)
Definition at line 554 of file ExprControl.cpp.
References _curve, _curveEditable, SeExpr2::Curve< T >::CV::_interp, SeExpr2::Curve< T >::CV::_pos, ExprCurve::_scene, SeExpr2::Curve< T >::CV::_val, ExprCurve::addPoint(), curveChanged(), GenericCurveEditable< TVAL >::cvs, and ExprControl::hbox.
Member Function Documentation
void CurveControl::curveChanged () private slot
Definition at line 570 of file ExprControl.cpp.
References _curve, _curveEditable, CurveScene::_cvs, ExprControl::_id, ExprCurve::_scene, ExprControl::controlChanged(), and GenericCurveEditable< TVAL >::cvs.
Referenced by CurveControl().
Member Data Documentation
ExprCurve* CurveControl::_curve private
curve edit widget
Definition at line 241 of file ExprControl.h.
Referenced by curveChanged(), and CurveControl().
CurveEditable* CurveControl::_curveEditable private
curve model
Definition at line 239 of file ExprControl.h.
Referenced by curveChanged(), and CurveControl().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp