SeExpr: ExprFileDialog Class Reference
ExprFileDialog Class Reference
#include <ExprFileDialog.h>
Public Member Functions
ExprFileDialog (QWidget *parent=0)
void addLookInEntries (QStringList paths)
void saveLookInEntries ()
void restoreLookInEntries ()
QString getOpenFileName (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getExistingDirectory (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getExistingOrNewDirectory (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QStringList getOpenFileNames (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getSaveFileName (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
void setPreview ()
void resetPreview ()
void addCheckBox (QString s)
void addFavoritesButton (QString dirname, QString linkname, QString linkdir)
bool checkBoxStatus ()
void showCheckBox ()
void hideCheckBox ()
void addComboBox (QString s, QStringList sl)
void showComboBox ()
void hideComboBox ()
QComboBox * getComboBox ()
void setButtonName (const QString &str)
void addSidebarShortcut (const QString &s)
Private Slots
void handleOk ()
void editReturnPress ()
void gotoFavorites ()
void selChanged (const QString &path)
void resetDir ()
Private Attributes
QString _workingDirectory
QString _favDir
QString _temppath
QStringList _lookInList
QLineEdit * _nameEdit
QPushButton * _okButton
bool _createDir
ExprPreviewWidget * _pw
QCheckBox * _cb
QLabel * _combolabel
QComboBox * _combo
Detailed Description
Definition at line 45 of file ExprFileDialog.h.
Constructor & Destructor Documentation
ExprFileDialog::ExprFileDialog (QWidget * parent = 0)
Definition at line 97 of file ExprFileDialog.cpp.
References _cb, _combo, _combolabel, _createDir, _favDir, _nameEdit, _okButton, _pw, _temppath, editReturnPress(), handleOk(), and selChanged().
Member Function Documentation
void ExprFileDialog::addCheckBox (QString s)
Definition at line 409 of file ExprFileDialog.cpp.
References _cb, and _combo.
void ExprFileDialog::addComboBox (QString s, QStringList sl)
Definition at line 436 of file ExprFileDialog.cpp.
References _combo, _combolabel, and it.
void ExprFileDialog::addFavoritesButton (QString dirname, QString linkname, QString linkdir)
Definition at line 199 of file ExprFileDialog.cpp.
References _favDir, folder_fav, and gotoFavorites().
void ExprFileDialog::addLookInEntries (QStringList paths)
Definition at line 239 of file ExprFileDialog.cpp.
References it.
void ExprFileDialog::addSidebarShortcut (const QString & s)
Definition at line 476 of file ExprFileDialog.cpp.
bool ExprFileDialog::checkBoxStatus ()
Definition at line 420 of file ExprFileDialog.cpp.
References _cb.
void ExprFileDialog::editReturnPress () private slot
Definition at line 161 of file ExprFileDialog.cpp.
References _nameEdit, and handleOk().
Referenced by ExprFileDialog().
QComboBox* ExprFileDialog::getComboBox () inline
Definition at line 78 of file ExprFileDialog.h.
References _combo.
QString ExprFileDialog::getExistingDirectory (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 331 of file ExprFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
Referenced by StringControl::directoryBrowse(), and getExistingOrNewDirectory().
QString ExprFileDialog::getExistingOrNewDirectory (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 356 of file ExprFileDialog.cpp.
References _createDir, getExistingDirectory(), and resetPreview().
QString ExprFileDialog::getOpenFileName (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 278 of file ExprFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
Referenced by StringControl::fileBrowse().
QStringList ExprFileDialog::getOpenFileNames (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 304 of file ExprFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
QString ExprFileDialog::getSaveFileName (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 366 of file ExprFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
void ExprFileDialog::gotoFavorites () private slot
Definition at line 234 of file ExprFileDialog.cpp.
References _favDir.
Referenced by addFavoritesButton().
void ExprFileDialog::handleOk () private slot
Definition at line 138 of file ExprFileDialog.cpp.
References _createDir, _nameEdit, _okButton, _temppath, and resetDir().
Referenced by editReturnPress(), and ExprFileDialog().
void ExprFileDialog::hideCheckBox ()
Definition at line 431 of file ExprFileDialog.cpp.
References _cb.
void ExprFileDialog::hideComboBox ()
Definition at line 460 of file ExprFileDialog.cpp.
References _combo, and _combolabel.
void ExprFileDialog::resetDir () inline private slot
Definition at line 87 of file ExprFileDialog.h.
References _temppath.
Referenced by handleOk().
void ExprFileDialog::resetPreview ()
Definition at line 404 of file ExprFileDialog.cpp.
References _pw, and ExprPreviewWidget::reset().
Referenced by getExistingDirectory(), getExistingOrNewDirectory(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
void ExprFileDialog::restoreLookInEntries ()
Definition at line 256 of file ExprFileDialog.cpp.
References _lookInList.
void ExprFileDialog::saveLookInEntries ()
Definition at line 251 of file ExprFileDialog.cpp.
References _lookInList.
void ExprFileDialog::selChanged (const QString & path) private slot
Definition at line 466 of file ExprFileDialog.cpp.
References _pw, and ExprPreviewWidget::makePreview().
Referenced by ExprFileDialog().
void ExprFileDialog::setButtonName (const QString & str)
Definition at line 471 of file ExprFileDialog.cpp.
References _okButton.
void ExprFileDialog::setPreview ()
Definition at line 393 of file ExprFileDialog.cpp.
References _pw.
Referenced by StringControl::directoryBrowse(), and StringControl::fileBrowse().
void ExprFileDialog::showCheckBox ()
Definition at line 426 of file ExprFileDialog.cpp.
References _cb.
void ExprFileDialog::showComboBox ()
Definition at line 454 of file ExprFileDialog.cpp.
References _combo, and _combolabel.
Member Data Documentation
QCheckBox* ExprFileDialog::_cb private
Definition at line 98 of file ExprFileDialog.h.
Referenced by addCheckBox(), checkBoxStatus(), ExprFileDialog(), hideCheckBox(), and showCheckBox().
QComboBox* ExprFileDialog::_combo private
Definition at line 100 of file ExprFileDialog.h.
Referenced by addCheckBox(), addComboBox(), ExprFileDialog(), getComboBox(), hideComboBox(), and showComboBox().
QLabel* ExprFileDialog::_combolabel private
Definition at line 99 of file ExprFileDialog.h.
Referenced by addComboBox(), ExprFileDialog(), hideComboBox(), and showComboBox().
bool ExprFileDialog::_createDir private
Definition at line 96 of file ExprFileDialog.h.
Referenced by ExprFileDialog(), getExistingOrNewDirectory(), and handleOk().
QString ExprFileDialog::_favDir private
Definition at line 91 of file ExprFileDialog.h.
Referenced by addFavoritesButton(), ExprFileDialog(), and gotoFavorites().
QStringList ExprFileDialog::_lookInList private
Definition at line 93 of file ExprFileDialog.h.
Referenced by restoreLookInEntries(), and saveLookInEntries().
QLineEdit* ExprFileDialog::_nameEdit private
Definition at line 94 of file ExprFileDialog.h.
Referenced by editReturnPress(), ExprFileDialog(), and handleOk().
QPushButton* ExprFileDialog::_okButton private
Definition at line 95 of file ExprFileDialog.h.
Referenced by ExprFileDialog(), handleOk(), and setButtonName().
ExprPreviewWidget* ExprFileDialog::_pw private
Definition at line 97 of file ExprFileDialog.h.
Referenced by ExprFileDialog(), resetPreview(), selChanged(), and setPreview().
QString ExprFileDialog::_temppath private
Definition at line 92 of file ExprFileDialog.h.
Referenced by ExprFileDialog(), handleOk(), and resetDir().
QString ExprFileDialog::_workingDirectory private
Definition at line 91 of file ExprFileDialog.h.
Referenced by getExistingDirectory(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprFileDialog.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprFileDialog.cpp