SeExpr: ExprCurve Class Reference
ExprCurve Class Reference
#include <ExprCurve.h>
Public Slots
void cvSelectedSlot (double pos, double val, T_INTERP interp)
void selPosChanged ()
void selValChanged ()
void openDetail ()
Signals
void selPosChangedSignal (double pos)
void selValChangedSignal (double val)
Public Member Functions
ExprCurve (QWidget *parent=0, QString pLabel="", QString vLabel="", QString iLabel="", bool expandable=true)
~ExprCurve ()
void addPoint (const double x, const double y, const T_INTERP interp, bool select=false)
Public Attributes
CurveScene * _scene
Private Types
typedef SeExpr2::Curve< double > T_CURVE
typedef T_CURVE::InterpType T_INTERP
Private Attributes
QLineEdit * _selPosEdit
QLineEdit * _selValEdit
QComboBox * _interpComboBox
Detailed Description
Definition at line 118 of file ExprCurve.h.
Member Typedef Documentation
typedef SeExpr2::Curve<double> ExprCurve::T_CURVE private
Definition at line 122 of file ExprCurve.h.
typedef T_CURVE::InterpType ExprCurve::T_INTERP private
Definition at line 123 of file ExprCurve.h.
Constructor & Destructor Documentation
ExprCurve::ExprCurve (QWidget * parent = 0, QString pLabel = "", QString vLabel = "", QString iLabel = "", bool expandable = true)
Definition at line 295 of file ExprCurve.cpp.
References _interpComboBox, _scene, _selPosEdit, _selValEdit, cvSelectedSlot(), openDetail(), selPosChanged(), selPosChangedSignal(), selValChanged(), and selValChangedSignal().
Referenced by openDetail().
ExprCurve::~ExprCurve () inline
Definition at line 128 of file ExprCurve.h.
Member Function Documentation
void ExprCurve::addPoint (const double x, const double y, const T_INTERP interp, bool select = false)
Definition at line 491 of file ExprCurve.cpp.
References _scene, and CurveScene::addPoint().
Referenced by CurveControl::CurveControl(), and openDetail().
void ExprCurve::cvSelectedSlot (double pos, double val, T_INTERP interp) slot
Definition at line 417 of file ExprCurve.cpp.
References _interpComboBox, _selPosEdit, and _selValEdit.
Referenced by ExprCurve().
void ExprCurve::openDetail () slot
Definition at line 447 of file ExprCurve.cpp.
References CurveScene::_cvs, _scene, addPoint(), SeExpr2::curve, CurveScene::emitCurveChanged(), ExprCurve(), and CurveScene::removeAll().
Referenced by ExprCurve().
void ExprCurve::selPosChanged () slot
Definition at line 430 of file ExprCurve.cpp.
References _selPosEdit, and selPosChangedSignal().
Referenced by ExprCurve().
void ExprCurve::selPosChangedSignal (double pos) signal
Referenced by ExprCurve(), and selPosChanged().
void ExprCurve::selValChanged () slot
Definition at line 439 of file ExprCurve.cpp.
References _selValEdit, SeExpr2::clamp(), and selValChangedSignal().
Referenced by ExprCurve().
void ExprCurve::selValChangedSignal (double val) signal
Referenced by ExprCurve(), and selValChanged().
Member Data Documentation
QComboBox* ExprCurve::_interpComboBox private
Definition at line 148 of file ExprCurve.h.
Referenced by cvSelectedSlot(), and ExprCurve().
CurveScene* ExprCurve::_scene
Definition at line 133 of file ExprCurve.h.
Referenced by addPoint(), CurveControl::curveChanged(), CurveControl::CurveControl(), ExprCurve(), and openDetail().
QLineEdit* ExprCurve::_selPosEdit private
Definition at line 146 of file ExprCurve.h.
Referenced by cvSelectedSlot(), ExprCurve(), and selPosChanged().
QLineEdit* ExprCurve::_selValEdit private
Definition at line 147 of file ExprCurve.h.
Referenced by cvSelectedSlot(), ExprCurve(), and selValChanged().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprCurve.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprCurve.cpp