SeExpr: SeExpr2::ExprLocalVar Class Reference
SeExpr2::ExprLocalVar Class Reference
ExprLocalVar reference, all local variables in seexpr are subclasses of this or this itself.
#include <ExprEnv.h>
Public Member Functions
ExprLocalVar (const ExprType &type)
virtual ~ExprLocalVar ()
const ExprLocalVar * getPhi () const
get the primary representative phi node (i.e. the global parent of a dependent phi node)
ExprType type () const
returns type of the variable
virtual void setPhi (ExprLocalVar *phi)
sets the representative phi node (like a brute force set unioning operation) phi is the set representative
virtual LLVM_VALUE codegen (LLVM_BUILDER, const std::string &name, LLVM_VALUE referenceType) LLVM_BODY
LLVM value that has been allocated.
virtual LLVM_VALUE varPtr ()
LLVM value that has been pre-done.
int buildInterpreter (Interpreter *interpreter) const
Allocates variable for interpreter.
Protected Attributes
ExprType _type
ExprLocalVar * _phi
LLVM_VALUE _varPtr
Detailed Description
ExprLocalVar reference, all local variables in seexpr are subclasses of this or this itself.
Definition at line 38 of file ExprEnv.h.
Constructor & Destructor Documentation
SeExpr2::ExprLocalVar::ExprLocalVar (const ExprType & type) inline
Definition at line 44 of file ExprEnv.h.
virtual SeExpr2::ExprLocalVar::~ExprLocalVar () inline virtual
Definition at line 46 of file ExprEnv.h.
Member Function Documentation
int SeExpr2::ExprLocalVar::buildInterpreter (Interpreter * interpreter) const
Allocates variable for interpreter.
Definition at line 641 of file Interpreter.cpp.
References _type, SeExpr2::Interpreter::allocFP(), SeExpr2::Interpreter::allocPtr(), SeExpr2::ExprType::dim(), SeExpr2::ExprType::isFP(), SeExpr2::ExprType::isString(), and SeExpr2::Interpreter::varToLoc.
Referenced by SeExpr2::ExprIfThenElseNode::buildInterpreter(), and SeExpr2::ExprAssignNode::buildInterpreter().
virtual LLVM_VALUE SeExpr2::ExprLocalVar::codegen (LLVM_BUILDER , const std::string & name, LLVM_VALUE referenceType) virtual
LLVM value that has been allocated.
const ExprLocalVar* SeExpr2::ExprLocalVar::getPhi () const inline
get the primary representative phi node (i.e. the global parent of a dependent phi node)
Definition at line 49 of file ExprEnv.h.
References _phi.
Referenced by SeExpr2::ExprPrototypeNode::prep().
virtual void SeExpr2::ExprLocalVar::setPhi (ExprLocalVar * phi) inline virtual
sets the representative phi node (like a brute force set unioning operation) phi is the set representative
Reimplemented in SeExpr2::ExprLocalVarPhi.
Definition at line 53 of file ExprEnv.h.
References _phi.
Referenced by SeExpr2::ExprLocalVarPhi::setPhi().
ExprType SeExpr2::ExprLocalVar::type () const inline
returns type of the variable
Definition at line 51 of file ExprEnv.h.
References _type.
Referenced by SeExpr2::copyVarToPromotedPosition(), SeExpr2::ExprLocalVarPhi::ExprLocalVarPhi(), and SeExpr2::ExprVarNode::prep().
virtual LLVM_VALUE SeExpr2::ExprLocalVar::varPtr () inline virtual
LLVM value that has been pre-done.
Definition at line 59 of file ExprEnv.h.
References _varPtr.
Member Data Documentation
ExprLocalVar* SeExpr2::ExprLocalVar::_phi protected
Definition at line 41 of file ExprEnv.h.
Referenced by getPhi(), setPhi(), and SeExpr2::ExprLocalVarPhi::setPhi().
ExprType SeExpr2::ExprLocalVar::_type protected
Definition at line 40 of file ExprEnv.h.
Referenced by buildInterpreter(), SeExpr2::ExprLocalVarPhi::ExprLocalVarPhi(), type(), and SeExpr2::ExprLocalVarPhi::valid().
LLVM_VALUE SeExpr2::ExprLocalVar::_varPtr mutable protected
Definition at line 42 of file ExprEnv.h.
Referenced by varPtr().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprEnv.h
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Interpreter.cpp