SeExpr: ExprColorSwatchWidget Class Reference
ExprColorSwatchWidget Class Reference
#include <ExprColorSwatch.h>
Signals
void selValChangedSignal (SeExpr2::Vec3d val)
void swatchChanged (int index, SeExpr2::Vec3d val)
void swatchAdded (int index, SeExpr2::Vec3d val)
void swatchRemoved (int index)
Public Member Functions
ExprColorSwatchWidget (bool indexLabel, QWidget *parent=0)
~ExprColorSwatchWidget ()
void addSwatch (SeExpr2::Vec3d &val, int index=-1)
void setSwatchColor (int index, QColor color)
QColor getSwatchColor (int index)
Private Slots
void addNewColor ()
void removeSwatch (ExprColorFrame *)
void internalSwatchChanged (QColor color)
Private Attributes
QGridLayout * _gridLayout
int _columns
bool _indexLabel
Detailed Description
Definition at line 53 of file ExprColorSwatch.h.
Constructor & Destructor Documentation
ExprColorSwatchWidget::ExprColorSwatchWidget (bool indexLabel, QWidget * parent = 0)
Definition at line 123 of file ExprColorSwatch.cpp.
References _gridLayout, and addNewColor().
ExprColorSwatchWidget::~ExprColorSwatchWidget () inline
Definition at line 59 of file ExprColorSwatch.h.
Member Function Documentation
void ExprColorSwatchWidget::addNewColor () private slot
Definition at line 161 of file ExprColorSwatch.cpp.
References addSwatch().
Referenced by ExprColorSwatchWidget().
void ExprColorSwatchWidget::addSwatch (SeExpr2::Vec3d & val, int index = -1)
Definition at line 167 of file ExprColorSwatch.cpp.
References _columns, _gridLayout, _indexLabel, ExprColorWidget::getColorFrame(), internalSwatchChanged(), removeSwatch(), swatchAdded(), and swatchChanged().
Referenced by addNewColor(), and ColorSwatchControl::buildSwatchWidget().
QColor ExprColorSwatchWidget::getSwatchColor (int index)
Definition at line 218 of file ExprColorSwatch.cpp.
References _gridLayout, and ExprColorFrame::getValue().
void ExprColorSwatchWidget::internalSwatchChanged (QColor color) private slot
Definition at line 182 of file ExprColorSwatch.cpp.
References _gridLayout, ExprColorFrame::getValue(), index(), swatchChanged(), and value().
Referenced by addSwatch().
void ExprColorSwatchWidget::removeSwatch (ExprColorFrame * widget) private slot
Definition at line 191 of file ExprColorSwatch.cpp.
References _gridLayout, and swatchRemoved().
Referenced by addSwatch().
void ExprColorSwatchWidget::selValChangedSignal (SeExpr2::Vec3d val) signal
void ExprColorSwatchWidget::setSwatchColor (int index, QColor color)
Definition at line 205 of file ExprColorSwatch.cpp.
References _gridLayout, and ExprColorFrame::setValue().
void ExprColorSwatchWidget::swatchAdded (int index, SeExpr2::Vec3d val) signal
Referenced by addSwatch().
void ExprColorSwatchWidget::swatchChanged (int index, SeExpr2::Vec3d val) signal
Referenced by addSwatch(), and internalSwatchChanged().
void ExprColorSwatchWidget::swatchRemoved (int index) signal
Referenced by removeSwatch().
Member Data Documentation
int ExprColorSwatchWidget::_columns private
Definition at line 79 of file ExprColorSwatch.h.
Referenced by addSwatch().
QGridLayout* ExprColorSwatchWidget::_gridLayout private
Definition at line 78 of file ExprColorSwatch.h.
Referenced by addSwatch(), ExprColorSwatchWidget(), getSwatchColor(), internalSwatchChanged(), removeSwatch(), and setSwatchColor().
bool ExprColorSwatchWidget::_indexLabel private
Definition at line 80 of file ExprColorSwatch.h.
Referenced by addSwatch().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorSwatch.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorSwatch.cpp