SeExpr: SeExprEdControl Class Reference
SeExprEdControl Class Reference
Base class for all controls for SeExpressions.
#include <SeExprEdControl.h>
Public Slots
void linkStateChange (int state)
Signals
void controlChanged (int id)
void linkColorEdited (int id, QColor color)
void linkColorLink (int id)
Public Member Functions
SeExprEdControl (int id, SeExprEdEditable *editable, bool showColorLink)
virtual ~SeExprEdControl ()
virtual QColor getColor ()
Interface for getting the color (used for linked color picking).
virtual void setColor (QColor color)
Interface for setting the color (used for linked color picking).
void linkDisconnect (int newId)
Protected Attributes
int _id
bool _updating
QHBoxLayout * hbox
QCheckBox * _colorLinkCB
QLabel * _label
SeExprEdEditable * _editable
Detailed Description
Base class for all controls for SeExpressions.
Definition at line 43 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdControl::SeExprEdControl (int id, SeExprEdEditable * editable, bool showColorLink)
Definition at line 259 of file SeExprEdControl.cpp.
References _colorLinkCB, _label, hbox, linkStateChange(), and SeExprEdEditable::name.
virtual SeExprEdControl::~SeExprEdControl () [inline, virtual]
Definition at line 58 of file SeExprEdControl.h.
Member Function Documentation
void SeExprEdControl::controlChanged (int id) [signal]
Referenced by SeExprEdCCurveControl::curveChanged(), SeExprEdCurveControl::curveChanged(), SeExprEdAnimCurveControl::editGraphClicked(), SeExprEdAnimCurveControl::refreshClicked(), SeExprEdVectorControl::setValue(), SeExprEdNumberControl::setValue(), and SeExprEdStringControl::textChanged().
virtual QColor SeExprEdControl::getColor () [inline, virtual]
Interface for getting the color (used for linked color picking).
Reimplemented in SeExprEdVectorControl, and SeExprEdCCurveControl.
Definition at line 61 of file SeExprEdControl.h.
Referenced by linkStateChange().
void SeExprEdControl::linkColorEdited (int id, QColor color) [signal]
Referenced by linkStateChange(), and SeExprEdVectorControl::sliderChanged().
void SeExprEdControl::linkColorLink (int id) [signal]
Referenced by linkStateChange().
void SeExprEdControl::linkDisconnect (int newId)
Definition at line 301 of file SeExprEdControl.cpp.
References _colorLinkCB, _id, and _updating.
void SeExprEdControl::linkStateChange (int state) [slot]
Definition at line 289 of file SeExprEdControl.cpp.
References _id, _updating, getColor(), linkColorEdited(), and linkColorLink().
Referenced by SeExprEdControl().
virtual void SeExprEdControl::setColor (QColor color) [inline, virtual]
Interface for setting the color (used for linked color picking).
Reimplemented in SeExprEdVectorControl, and SeExprEdCCurveControl.
Definition at line 63 of file SeExprEdControl.h.
Member Data Documentation
QCheckBox* SeExprEdControl::_colorLinkCB [protected]
Definition at line 51 of file SeExprEdControl.h.
Referenced by linkDisconnect(), and SeExprEdControl().
SeExprEdEditable* SeExprEdControl::_editable [protected]
Reimplemented in SeExprEdAnimCurveControl.
Definition at line 54 of file SeExprEdControl.h.
int SeExprEdControl::_id [protected]
Definition at line 45 of file SeExprEdControl.h.
Referenced by SeExprEdCCurveControl::curveChanged(), SeExprEdCurveControl::curveChanged(), SeExprEdAnimCurveControl::editGraphClicked(), linkDisconnect(), linkStateChange(), SeExprEdAnimCurveControl::refreshClicked(), SeExprEdVectorControl::setValue(), SeExprEdNumberControl::setValue(), SeExprEdVectorControl::sliderChanged(), and SeExprEdStringControl::textChanged().
QLabel* SeExprEdControl::_label [protected]
Definition at line 52 of file SeExprEdControl.h.
Referenced by SeExprEdControl(), and SeExprEdVectorControl::updateControl().
bool SeExprEdControl::_updating [protected]
Definition at line 49 of file SeExprEdControl.h.
Referenced by SeExprEdVectorControl::editChanged(), SeExprEdNumberControl::editChanged(), linkDisconnect(), linkStateChange(), SeExprEdVectorControl::sliderChanged(), SeExprEdNumberControl::sliderChanged(), SeExprEdStringControl::textChanged(), SeExprEdVectorControl::updateControl(), and SeExprEdNumberControl::updateControl().
QHBoxLayout* SeExprEdControl::hbox [protected]
Definition at line 50 of file SeExprEdControl.h.
Referenced by SeExprEdAnimCurveControl::SeExprEdAnimCurveControl(), SeExprEdCCurveControl::SeExprEdCCurveControl(), SeExprEdControl(), SeExprEdCurveControl::SeExprEdCurveControl(), SeExprEdNumberControl::SeExprEdNumberControl(), SeExprEdStringControl::SeExprEdStringControl(), and SeExprEdVectorControl::SeExprEdVectorControl().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp