SeExpr: ExprCSwatchFrame Class Reference
ExprCSwatchFrame Class Reference
#include <ExprColorCurve.h>
Signals
void selValChangedSignal (SeExpr2::Vec3d value)
void swatchChanged (QColor color)
Public Member Functions
ExprCSwatchFrame (SeExpr2::Vec3d value, QWidget *parent=0)
~ExprCSwatchFrame ()
void setValue (const SeExpr2::Vec3d &value)
SeExpr2::Vec3d getValue () const
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
Private Attributes
SeExpr2::Vec3d _value
QColor _color
Detailed Description
Definition at line 120 of file ExprColorCurve.h.
Constructor & Destructor Documentation
ExprCSwatchFrame::ExprCSwatchFrame (SeExpr2::Vec3d value, QWidget * parent = 0)
Definition at line 346 of file ExprColorCurve.cpp.
References _color, and _value.
ExprCSwatchFrame::~ExprCSwatchFrame () inline
Definition at line 125 of file ExprColorCurve.h.
Member Function Documentation
SeExpr2::Vec3d ExprCSwatchFrame::getValue () const
Definition at line 360 of file ExprColorCurve.cpp.
References _value.
Referenced by ExprColorCurve::getSwatchColor(), and VectorControl::swatchChanged().
void ExprCSwatchFrame::mousePressEvent (QMouseEvent * event) protected virtual
Definition at line 366 of file ExprColorCurve.cpp.
References _color, _value, selValChangedSignal(), and swatchChanged().
void ExprCSwatchFrame::paintEvent (QPaintEvent * event) protected virtual
Definition at line 338 of file ExprColorCurve.cpp.
References _color, and p.
void ExprCSwatchFrame::selValChangedSignal (SeExpr2::Vec3d value) signal
Referenced by mousePressEvent().
void ExprCSwatchFrame::setValue (const SeExpr2::Vec3d & value)
Definition at line 352 of file ExprColorCurve.cpp.
References _color, _value, and value().
Referenced by ExprColorCurve::cvSelectedSlot(), ExprColorCurve::setSwatchColor(), and VectorControl::setValue().
void ExprCSwatchFrame::swatchChanged (QColor color) signal
Referenced by mousePressEvent().
Member Data Documentation
QColor ExprCSwatchFrame::_color private
Definition at line 140 of file ExprColorCurve.h.
Referenced by ExprCSwatchFrame(), mousePressEvent(), paintEvent(), and setValue().
SeExpr2::Vec3d ExprCSwatchFrame::_value private
Definition at line 139 of file ExprColorCurve.h.
Referenced by ExprCSwatchFrame(), getValue(), mousePressEvent(), and setValue().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorCurve.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorCurve.cpp