SeExpr: SeExpr2::RandFuncX Class Reference
SeExpr2::RandFuncX Class Reference
Classes
struct Data
Public Member Functions
RandFuncX ()
virtual ~RandFuncX ()
Public Member Functions inherited from SeExpr2::ExprFuncSimple
ExprFuncSimple (const bool threadSafe)
virtual int buildInterpreter (const ExprFuncNode *node, Interpreter *interpreter) const
Build an interpreter to evaluate the expression.
Public Member Functions inherited from SeExpr2::ExprFuncX
ExprFuncX (const bool threadSafe)
virtual ExprType type () const
virtual ~ExprFuncX ()
bool isThreadSafe () const
virtual size_t sizeInBytes () const
Return memory usage of a funcX in bytes.
virtual void statistics (Statistics &) const
Give this function a chance to populate its statistics.
Private Member Functions
virtual ExprType prep (ExprFuncNode *node, bool wantScalar, ExprVarEnvBuilder &envBuilder) const
virtual ExprFuncNode::Data * evalConstant (const ExprFuncNode *node, ArgHandle args) const
virtual void eval (ArgHandle args)
Additional Inherited Members
Protected Attributes inherited from SeExpr2::ExprFuncX
bool _isScalar
ExprType _type
Detailed Description
Definition at line 34 of file imageSynthForPaint3d.cpp.
Constructor & Destructor Documentation
SeExpr2::RandFuncX::RandFuncX () inline
Definition at line 57 of file imageSynthForPaint3d.cpp.
virtual SeExpr2::RandFuncX::~RandFuncX () inline virtual
Definition at line 58 of file imageSynthForPaint3d.cpp.
Member Function Documentation
virtual void SeExpr2::RandFuncX::eval (ArgHandle args) inline private virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 49 of file imageSynthForPaint3d.cpp.
References SeExpr2::ExprFuncSimple::ArgHandle::inFp(), SeExpr2::ExprFuncSimple::ArgHandle::nargs(), and SeExpr2::ExprFuncSimple::ArgHandle::outFp.
virtual ExprFuncNode::Data* SeExpr2::RandFuncX::evalConstant (const ExprFuncNode * node, ArgHandle args) const inline private virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 47 of file imageSynthForPaint3d.cpp.
virtual ExprType SeExpr2::RandFuncX::prep (ExprFuncNode * node, bool scalarWanted, ExprVarEnvBuilder & env) const inline private virtual
prep the expression by doing all type checking argument checking, etc.
Implements SeExpr2::ExprFuncSimple.
Definition at line 41 of file imageSynthForPaint3d.cpp.
References SeExpr2::ExprFuncNode::checkArg(), SeExpr2::ExprType::Error(), SeExpr2::ExprType::FP(), SeExpr2::ExprNode::numChildren(), and SeExpr2::ExprType::Varying().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/demos/imageSynth/imageSynthForPaint3d.cpp