SeExpr: SeExpr::CachedVoronoiFunc Class Reference
SeExpr::CachedVoronoiFunc Class Reference
Public Types
typedef SeVec3d VoronoiFunc (VoronoiPointData &data, int n, const SeVec3d *args)
Public Member Functions
CachedVoronoiFunc (VoronoiFunc *vfunc)
virtual bool prep (SeExprFuncNode *node, bool wantVec, std::string &error)
virtual void eval (const SeExprFuncNode *node, SeVec3d &result) const
Private Attributes
VoronoiFunc * _vfunc
Detailed Description
Definition at line 1004 of file SeExprBuiltins.cpp.
Member Typedef Documentation
typedef SeVec3d SeExpr::CachedVoronoiFunc::VoronoiFunc(VoronoiPointData &data, int n, const SeVec3d *args)
Definition at line 1007 of file SeExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr::CachedVoronoiFunc::CachedVoronoiFunc (VoronoiFunc * vfunc) [inline]
Definition at line 1008 of file SeExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr::CachedVoronoiFunc::eval (const SeExprFuncNode * node, SeVec3d & result) const [inline, virtual]
evaluate the expression. the given node is where in the parse tree the evaluation is for
Implements SeExprFuncX.
Definition at line 1017 of file SeExprBuiltins.cpp.
References _vfunc, SeExprNode::child(), data, SeExprNode::eval(), SeExprFuncNode::getData(), and SeExprNode::numChildren().
virtual bool SeExpr::CachedVoronoiFunc::prep (SeExprFuncNode * node, bool wantVec, std::string & error) [inline, virtual]
prep the expression by doing all type checking argument checking, etc. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprFuncX.
Definition at line 1010 of file SeExprBuiltins.cpp.
References SeExprFuncNode::setData().
Member Data Documentation
VoronoiFunc* SeExpr::CachedVoronoiFunc::_vfunc [private]
Definition at line 1027 of file SeExprBuiltins.cpp.
Referenced by eval().
The documentation for this class was generated from the following file:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprBuiltins.cpp