SeExpr: SeExprExpNode Class Reference
SeExprExpNode Class Reference
Node that implements an arithmetic operator.
#include <SeExprNode.h>
Public Member Functions
SeExprExpNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that implements an arithmetic operator.
Definition at line 394 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprExpNode::SeExprExpNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 397 of file SeExprNode.h.
Member Function Documentation
void SeExprExpNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 653 of file SeExprNode.cpp.
References SeExprNode::_isVec, a, b, SeExprNode::child(), SeExprNode::eval(), SeExprNode::isVec(), and pow().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp