SeExpr: SeExprEdHighlighter Class Reference
SeExprEdHighlighter Class Reference
#include <SeExprEdHighlighter.h>
Classes
struct HighlightingRule
Public Member Functions
SeExprEdHighlighter (QTextDocument *parent)
SeExprEdHighlighter (QTextEdit *edit)
void fixStyle (const QPalette &palette)
void init ()
void highlightBlock (const QString &text)
Private Attributes
QVector< HighlightingRule > highlightingRules
QTextCharFormat singleLineCommentFormat
QTextCharFormat variableFormat
QTextCharFormat numberFormat
QTextCharFormat operatorFormat
int lightness
Detailed Description
Definition at line 20 of file SeExprEdHighlighter.h.
Constructor & Destructor Documentation
SeExprEdHighlighter::SeExprEdHighlighter (QTextDocument * parent) [inline]
Definition at line 35 of file SeExprEdHighlighter.h.
References init().
SeExprEdHighlighter::SeExprEdHighlighter (QTextEdit * edit) [inline]
Definition at line 41 of file SeExprEdHighlighter.h.
References init().
Member Function Documentation
void SeExprEdHighlighter::fixStyle (const QPalette & palette) [inline]
Definition at line 47 of file SeExprEdHighlighter.h.
References init(), and lightness.
Referenced by SeExprEdShortTextEdit::paintEvent(), SeExprEdExpressionTextEdit::paintEvent(), SeExprEdShortTextEdit::SeExprEdShortTextEdit(), and SeExprEdExpressionTextEdit::updateStyle().
void SeExprEdHighlighter::highlightBlock (const QString & text) [inline]
Definition at line 86 of file SeExprEdHighlighter.h.
References expression, SeExprEdHighlighter::HighlightingRule::format, highlightingRules, index(), SeExpr::length(), and SeExprEdHighlighter::HighlightingRule::pattern.
void SeExprEdHighlighter::init () [inline]
Definition at line 53 of file SeExprEdHighlighter.h.
References SeExprEdHighlighter::HighlightingRule::format, highlightingRules, lightness, numberFormat, SeExprEdHighlighter::HighlightingRule::pattern, singleLineCommentFormat, and variableFormat.
Referenced by fixStyle(), and SeExprEdHighlighter().
Member Data Documentation
QVector<HighlightingRule> SeExprEdHighlighter::highlightingRules [private]
Definition at line 26 of file SeExprEdHighlighter.h.
Referenced by highlightBlock(), and init().
int SeExprEdHighlighter::lightness [private]
Definition at line 32 of file SeExprEdHighlighter.h.
Referenced by fixStyle(), and init().
QTextCharFormat SeExprEdHighlighter::numberFormat [private]
Definition at line 29 of file SeExprEdHighlighter.h.
Referenced by init().
QTextCharFormat SeExprEdHighlighter::operatorFormat [private]
Definition at line 30 of file SeExprEdHighlighter.h.
QTextCharFormat SeExprEdHighlighter::singleLineCommentFormat [private]
Definition at line 27 of file SeExprEdHighlighter.h.
Referenced by init().
QTextCharFormat SeExprEdHighlighter::variableFormat [private]
Definition at line 28 of file SeExprEdHighlighter.h.
Referenced by init().
The documentation for this class was generated from the following file:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdHighlighter.h