SeExpr: ExprTreeItem Class Reference
ExprTreeItem Class Reference
Public Member Functions
ExprTreeItem (ExprTreeItem *parent, const QString &label, const QString &path)
~ExprTreeItem ()
ExprTreeItem * find (QString path)
void clear ()
void populate ()
void addChild (ExprTreeItem *child)
ExprTreeItem * getChild (const int row)
int getChildCount ()
void regen ()
Public Attributes
int row
ExprTreeItem * parent
QString label
QString path
Private Attributes
std::vector< ExprTreeItem * > children
bool populated
Detailed Description
Definition at line 43 of file ExprBrowser.cpp.
Constructor & Destructor Documentation
ExprTreeItem::ExprTreeItem (ExprTreeItem * parent, const QString & label, const QString & path) inline
Definition at line 46 of file ExprBrowser.cpp.
Referenced by populate(), and regen().
ExprTreeItem::~ExprTreeItem () inline
Definition at line 50 of file ExprBrowser.cpp.
References children.
Member Function Documentation
void ExprTreeItem::addChild (ExprTreeItem * child) inline
Definition at line 95 of file ExprBrowser.cpp.
References children, and row.
Referenced by ExprTreeModel::addPath(), populate(), and regen().
void ExprTreeItem::clear () inline
Definition at line 69 of file ExprBrowser.cpp.
References children.
Referenced by ExprTreeModel::clear().
ExprTreeItem* ExprTreeItem::find (QString path) inline
Definition at line 56 of file ExprBrowser.cpp.
References children, and populate().
Referenced by ExprTreeModel::find().
ExprTreeItem* ExprTreeItem::getChild (const int row) inline
Definition at line 101 of file ExprBrowser.cpp.
References children, populate(), and row.
Referenced by ExprTreeModel::index().
int ExprTreeItem::getChildCount () inline
Definition at line 110 of file ExprBrowser.cpp.
References children, and populate().
Referenced by ExprTreeModel::rowCount().
void ExprTreeItem::populate () inline
Definition at line 77 of file ExprBrowser.cpp.
References addChild(), ExprTreeItem(), it, path, and populated.
Referenced by find(), getChild(), and getChildCount().
void ExprTreeItem::regen () inline
Definition at line 116 of file ExprBrowser.cpp.
References addChild(), children, ExprTreeItem(), label, and path.
Referenced by ExprTreeModel::find().
Member Data Documentation
std::vector<ExprTreeItem*> ExprTreeItem::children private
Definition at line 136 of file ExprBrowser.cpp.
Referenced by addChild(), clear(), find(), getChild(), getChildCount(), regen(), and ~ExprTreeItem().
QString ExprTreeItem::label
Definition at line 133 of file ExprBrowser.cpp.
Referenced by ExprTreeModel::data(), and regen().
ExprTreeItem* ExprTreeItem::parent
Definition at line 132 of file ExprBrowser.cpp.
Referenced by ExprTreeModel::parent().
QString ExprTreeItem::path
Definition at line 134 of file ExprBrowser.cpp.
Referenced by ExprBrowser::getSelectedPath(), ExprBrowser::handleSelection(), populate(), and regen().
bool ExprTreeItem::populated private
Definition at line 137 of file ExprBrowser.cpp.
Referenced by populate().
int ExprTreeItem::row
Definition at line 131 of file ExprBrowser.cpp.
Referenced by addChild(), ExprTreeModel::find(), getChild(), and ExprTreeModel::parent().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprBrowser.cpp