SeExpr: ColorSwatchControl Class Reference
ColorSwatchControl Class Reference
A control for editing color swatches.
#include <ExprControl.h>
Public Member Functions
ColorSwatchControl (int id, ColorSwatchEditable *swatchEditable)
Public Member Functions inherited from ExprControl
ExprControl (int id, Editable *editable, bool showColorLink)
virtual ~ExprControl ()
virtual QColor getColor ()
Interface for getting the color (used for linked color picking)
virtual void setColor (QColor color)
Interface for setting the color (used for linked color picking)
void linkDisconnect (int newId)
Private Slots
void buildSwatchWidget ()
void colorChanged (int index, SeExpr2::Vec3d value)
void colorAdded (int index, SeExpr2::Vec3d value)
void colorRemoved (int index)
Private Attributes
ColorSwatchEditable * _swatchEditable
model for the color swatches control
ExprColorSwatchWidget * _swatch
Edit box for the color swatches.
bool _indexLabel
Additional Inherited Members
Public Slots inherited from ExprControl
void linkStateChange (int state)
Signals inherited from ExprControl
void controlChanged (int id)
void linkColorEdited (int id, QColor color)
void linkColorLink (int id)
Protected Attributes inherited from ExprControl
int _id
bool _updating
QHBoxLayout * hbox
QCheckBox * _colorLinkCB
QLabel * _label
Editable * _editable
Detailed Description
A control for editing color swatches.
Definition at line 289 of file ExprControl.h.
Constructor & Destructor Documentation
ColorSwatchControl::ColorSwatchControl (int id, ColorSwatchEditable * swatchEditable)
Definition at line 820 of file ExprControl.cpp.
References _indexLabel, _swatchEditable, buildSwatchWidget(), and ColorSwatchEditable::labelType.
Member Function Documentation
void ColorSwatchControl::buildSwatchWidget () private slot
Definition at line 858 of file ExprControl.cpp.
References _indexLabel, _swatch, _swatchEditable, ExprControl::_updating, ExprColorSwatchWidget::addSwatch(), colorAdded(), colorChanged(), colorRemoved(), ColorSwatchEditable::colors, and ExprControl::hbox.
Referenced by colorRemoved(), and ColorSwatchControl().
void ColorSwatchControl::colorAdded (int index, SeExpr2::Vec3d value) private slot
Definition at line 838 of file ExprControl.cpp.
References ExprControl::_id, _swatchEditable, ExprControl::_updating, ColorSwatchEditable::add(), ColorSwatchEditable::colors, and ExprControl::controlChanged().
Referenced by buildSwatchWidget().
void ColorSwatchControl::colorChanged (int index, SeExpr2::Vec3d value) private slot
Definition at line 830 of file ExprControl.cpp.
References ExprControl::_id, _swatchEditable, ExprControl::_updating, ColorSwatchEditable::change(), ColorSwatchEditable::colors, and ExprControl::controlChanged().
Referenced by buildSwatchWidget().
void ColorSwatchControl::colorRemoved (int index) private slot
Definition at line 846 of file ExprControl.cpp.
References ExprControl::_id, _swatch, _swatchEditable, ExprControl::_updating, buildSwatchWidget(), ColorSwatchEditable::colors, ExprControl::controlChanged(), and ColorSwatchEditable::remove().
Referenced by buildSwatchWidget().
Member Data Documentation
bool ColorSwatchControl::_indexLabel private
Definition at line 305 of file ExprControl.h.
Referenced by buildSwatchWidget(), and ColorSwatchControl().
ExprColorSwatchWidget* ColorSwatchControl::_swatch private
Edit box for the color swatches.
Definition at line 296 of file ExprControl.h.
Referenced by buildSwatchWidget(), and colorRemoved().
ColorSwatchEditable* ColorSwatchControl::_swatchEditable private
model for the color swatches control
Definition at line 294 of file ExprControl.h.
Referenced by buildSwatchWidget(), colorAdded(), colorChanged(), colorRemoved(), and ColorSwatchControl().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp