SeExpr: ExprSlider Class Reference
ExprSlider Class Reference
Generic Slider (used for int and float sliders)
#include <ExprControl.h>
Public Member Functions
ExprSlider (QWidget *parent=0)
ExprSlider (Qt::Orientation orientation, QWidget *parent=0)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void leaveEvent (QEvent *event)
virtual void enterEvent (QEvent *event)
virtual void wheelEvent (QWheelEvent *e)
Detailed Description
Generic Slider (used for int and float sliders)
Definition at line 124 of file ExprControl.h.
Constructor & Destructor Documentation
ExprSlider::ExprSlider (QWidget * parent = 0) inline
Definition at line 128 of file ExprControl.h.
ExprSlider::ExprSlider (Qt::Orientation orientation, QWidget * parent = 0) inline
Definition at line 129 of file ExprControl.h.
Member Function Documentation
virtual void ExprSlider::enterEvent (QEvent * event) inline virtual
Definition at line 135 of file ExprControl.h.
virtual void ExprSlider::leaveEvent (QEvent * event) inline virtual
Definition at line 134 of file ExprControl.h.
void ExprSlider::mouseMoveEvent (QMouseEvent * e) virtual
Definition at line 175 of file ExprControl.cpp.
References SeExpr2::max(), and SeExpr2::min().
Referenced by mousePressEvent().
void ExprSlider::mousePressEvent (QMouseEvent * e) virtual
Definition at line 170 of file ExprControl.cpp.
References mouseMoveEvent().
void ExprSlider::paintEvent (QPaintEvent * e) virtual
Definition at line 183 of file ExprControl.cpp.
References p, and value().
virtual void ExprSlider::wheelEvent (QWheelEvent * e) inline virtual
Definition at line 136 of file ExprControl.h.
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp