SeExpr: SeExprModNode Class Reference
SeExprModNode Class Reference
Node that implements an arithmetic operator.
#include <SeExprNode.h>
Public Member Functions
SeExprModNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that implements an arithmetic operator.
Definition at line 354 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprModNode::SeExprModNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 357 of file SeExprNode.h.
Member Function Documentation
void SeExprModNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 605 of file SeExprNode.cpp.
References SeExprNode::_isVec, a, b, SeExprNode::child(), SeExprNode::eval(), SeExprNode::isVec(), and niceMod().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.cpp