SeExpr: ExprTextEdit Class Reference
ExprTextEdit Class Reference
#include <ExprEditor.h>
Signals
void applyShortcut ()
void nextError ()
Public Member Functions
ExprTextEdit (QWidget *parent=0)
~ExprTextEdit ()
void updateStyle ()
Public Attributes
QCompleter * completer
ExprCompletionModel * completionModel
Protected Member Functions
void showTip (const QString &string)
void hideTip ()
virtual void keyPressEvent (QKeyEvent *e)
void focusInEvent (QFocusEvent *e)
void focusOutEvent (QFocusEvent *e)
void mousePressEvent (QMouseEvent *event)
void mouseDoubleClickEvent (QMouseEvent *event)
void paintEvent (QPaintEvent *e)
void wheelEvent (QWheelEvent *e)
void contextMenuEvent (QContextMenuEvent *event)
Private Slots
void insertCompletion (const QString &completion)
Private Attributes
QToolTip * functionTip
std::map< std::string,
std::string > functionTooltips
ExprHighlighter * highlighter
QStyle * lastStyleForHighlighter
ExprPopupDoc * _tip
QAction * _popupEnabledAction
Detailed Description
Definition at line 55 of file ExprEditor.h.
Constructor & Destructor Documentation
ExprTextEdit::ExprTextEdit (QWidget * parent = 0)
Definition at line 199 of file ExprEditor.cpp.
References _popupEnabledAction, completer, completionModel, highlighter, and insertCompletion().
ExprTextEdit::~ExprTextEdit ()
Definition at line 96 of file ExprEditor.cpp.
Member Function Documentation
void ExprTextEdit::applyShortcut () signal
Referenced by keyPressEvent().
void ExprTextEdit::contextMenuEvent (QContextMenuEvent * event) protected
Definition at line 354 of file ExprEditor.cpp.
References _popupEnabledAction, and f().
void ExprTextEdit::focusInEvent (QFocusEvent * e) protected
Definition at line 226 of file ExprEditor.cpp.
References completer.
void ExprTextEdit::focusOutEvent (QFocusEvent * e) protected
Definition at line 232 of file ExprEditor.cpp.
References hideTip().
void ExprTextEdit::hideTip () protected
Definition at line 383 of file ExprEditor.cpp.
References _tip.
Referenced by focusOutEvent(), keyPressEvent(), mouseDoubleClickEvent(), and mousePressEvent().
void ExprTextEdit::insertCompletion (const QString & completion) private slot
Definition at line 388 of file ExprEditor.cpp.
References completer.
Referenced by ExprTextEdit().
void ExprTextEdit::keyPressEvent (QKeyEvent * e) protected virtual
Definition at line 269 of file ExprEditor.cpp.
References _popupEnabledAction, applyShortcut(), completer, completionModel, ExprCompletionModel::getDocString(), hideTip(), index(), nextError(), return, and showTip().
void ExprTextEdit::mouseDoubleClickEvent (QMouseEvent * event) protected
Definition at line 244 of file ExprEditor.cpp.
References hideTip().
void ExprTextEdit::mousePressEvent (QMouseEvent * event) protected
Definition at line 238 of file ExprEditor.cpp.
References hideTip().
void ExprTextEdit::nextError () signal
Referenced by keyPressEvent().
void ExprTextEdit::paintEvent (QPaintEvent * e) protected
Definition at line 250 of file ExprEditor.cpp.
References ExprHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
void ExprTextEdit::showTip (const QString & string) protected
Definition at line 369 of file ExprEditor.cpp.
References _tip, and ExprPopupDoc::label.
Referenced by keyPressEvent().
void ExprTextEdit::updateStyle ()
Definition at line 191 of file ExprEditor.cpp.
References ExprHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
Referenced by ExprEditor::updateStyle().
void ExprTextEdit::wheelEvent (QWheelEvent * e) protected
Definition at line 260 of file ExprEditor.cpp.
Member Data Documentation
QAction* ExprTextEdit::_popupEnabledAction private
Definition at line 64 of file ExprEditor.h.
Referenced by contextMenuEvent(), ExprTextEdit(), and keyPressEvent().
ExprPopupDoc* ExprTextEdit::_tip private
Definition at line 63 of file ExprEditor.h.
Referenced by hideTip(), and showTip().
QCompleter* ExprTextEdit::completer
Definition at line 66 of file ExprEditor.h.
Referenced by ExprTextEdit(), focusInEvent(), insertCompletion(), keyPressEvent(), ExprEditor::rebuildControls(), and ExprEditor::updateCompleter().
ExprCompletionModel* ExprTextEdit::completionModel
Definition at line 67 of file ExprEditor.h.
Referenced by ExprEditor::clearExtraCompleters(), ExprTextEdit(), keyPressEvent(), ExprEditor::rebuildControls(), ExprEditor::registerExtraFunction(), ExprEditor::registerExtraVariable(), ExprEditor::replaceExtras(), and ExprEditor::updateCompleter().
QToolTip* ExprTextEdit::functionTip private
Definition at line 59 of file ExprEditor.h.
std::map<std::string,std::string> ExprTextEdit::functionTooltips private
Definition at line 60 of file ExprEditor.h.
ExprHighlighter* ExprTextEdit::highlighter private
Definition at line 61 of file ExprEditor.h.
Referenced by ExprTextEdit(), paintEvent(), and updateStyle().
QStyle* ExprTextEdit::lastStyleForHighlighter private
Definition at line 62 of file ExprEditor.h.
Referenced by paintEvent(), and updateStyle().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprEditor.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprEditor.cpp