SeExpr: SeExpr::CCurveFuncX Class Reference
SeExpr::CCurveFuncX Class Reference
Public Member Functions
CCurveFuncX ()
virtual ~CCurveFuncX ()
Private Member Functions
virtual bool prep (SeExprFuncNode *node, bool wantVec, std::string &error)
virtual void eval (const SeExprFuncNode *node, SeVec3d &result) const
Detailed Description
Definition at line 1367 of file SeExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr::CCurveFuncX::CCurveFuncX () [inline]
Definition at line 1428 of file SeExprBuiltins.cpp.
virtual SeExpr::CCurveFuncX::~CCurveFuncX () [inline, virtual]
Definition at line 1429 of file SeExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr::CCurveFuncX::eval (const SeExprFuncNode * node, SeVec3d & result) const [inline, private, virtual]
evaluate the expression. the given node is where in the parse tree the evaluation is for
Implements SeExprFuncX.
Definition at line 1412 of file SeExprBuiltins.cpp.
References SeExprNode::child(), SeExpr::CurveData< T >::curve, data, SeExprNode::eval(), SeExprFuncNode::getData(), and SeExprNode::isVec().
virtual bool SeExpr::CCurveFuncX::prep (SeExprFuncNode * node, bool wantVec, std::string & error) [inline, private, virtual]
prep the expression by doing all type checking argument checking, etc. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprFuncX.
Definition at line 1369 of file SeExprBuiltins.cpp.
References SeExprNode::addError(), SeExprNode::child(), SeExpr::CurveData< T >::curve, data, SeExprNode::eval(), SeExprNode::isVec(), SeExprFuncNode::nargs(), SeExprNode::prep(), and SeExprFuncNode::setData().
The documentation for this class was generated from the following file:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprBuiltins.cpp