SeExpr: SeExpr2::ExprCondNode Class Reference
SeExpr2::ExprCondNode Class Reference
Node that evaluates a conditional (if-then-else) expression.
#include <ExprNode.h>
Public Member Functions
ExprCondNode (const Expression *expr, ExprNode *a, ExprNode *b, ExprNode *c)
virtual ExprType prep (bool wantScalar, ExprVarEnvBuilder &envBuilder)
virtual int buildInterpreter (Interpreter *interpreter) const
builds an interpreter. Returns the location index for the evaluated data
virtual LLVM_VALUE codegen (LLVM_BUILDER) LLVM_BODY
Public Member Functions inherited from SeExpr2::ExprNode
ExprNode (const Expression *expr)
ExprNode (const Expression *expr, const ExprType &type)
virtual ~ExprNode ()
bool isVec () const
True if node has a vector result.
const Expression * expr () const
Access expression.
std::string toString () const
Access to original string representation of current expression.
const ExprType & type () const
The type of the node.
void addError (const std::string &error) const
Register error. This will allow users and sophisticated editors to highlight where in code problem was.
ExprNode (const Expression *expr, ExprNode *a)
ExprNode (const Expression *expr, ExprNode *a, const ExprType &type)
ExprNode (const Expression *expr, ExprNode *a, ExprNode *b)
ExprNode (const Expression *expr, ExprNode *a, ExprNode *b, const ExprType &type)
ExprNode (const Expression *expr, ExprNode *a, ExprNode *b, ExprNode *c)
ExprNode (const Expression *expr, ExprNode *a, ExprNode *b, ExprNode *c, const ExprType &type)
const ExprNode * parent () const
Access parent node - root node has no parent.
int numChildren () const
Number of children.
const ExprNode * child (size_t i) const
Get 0 indexed child.
ExprNode * child (size_t i)
Get 0 indexed child.
void swapChildren (size_t i, size_t j)
Swap children, do not use unless you know what you are doing.
void removeLastChild ()
Remove last child and delete the entry.
void addChild (ExprNode *child)
Add a child to the child list (for parser use only)
void addChildren (ExprNode *surrogate)
Transfer children from surrogate parent (for parser use only)
void setPosition (const short int startPos, const short int endPos)
Remember the line and column position in the input string.
short int startPos () const
Access start position in input string.
short int endPos () const
Access end position in input string.
short int length () const
Access length of input string.
bool checkCondition (bool check, const std::string &message, bool &error)
Checks the boolean value and records an error string with node if it is false.
bool checkIsValue (const ExprType &type, bool &error)
Checks if the type is a value (i.e. string or float[d])
bool checkIsFP (const ExprType &type, bool &error)
Checks if the type is a float[d] for any d.
bool checkIsFP (int d, const ExprType &type, bool &error)
Checks if the type is a float[d] for a specific d.
bool checkTypesCompatible (const ExprType &first, const ExprType &second, bool &error)
types match (true if they do)
Additional Inherited Members
Protected Member Functions inherited from SeExpr2::ExprNode
void setType (const ExprType &t)
Set type of parameter.
void setTypeWithChildLife (const ExprType &t)
Set's the type to the argument but uses the children to determine lifetime.
Protected Attributes inherited from SeExpr2::ExprNode
const Expression * _expr
Owning expression (node can't modify)
ExprNode * _parent
Parent node (null if this the the root)
std::vector< ExprNode * > _children
List of children.
bool _isVec
True if node has a vector result.
ExprType _type
int _maxChildDim
unsigned short int _startPos
Position line and collumn.
unsigned short int _endPos
Detailed Description
Node that evaluates a conditional (if-then-else) expression.
Definition at line 405 of file ExprNode.h.
Constructor & Destructor Documentation
SeExpr2::ExprCondNode::ExprCondNode (const Expression * expr, ExprNode * a, ExprNode * b, ExprNode * c) inline
Definition at line 407 of file ExprNode.h.
Member Function Documentation
int SeExpr2::ExprCondNode::buildInterpreter (Interpreter * interpreter) const virtual
builds an interpreter. Returns the location index for the evaluated data
Reimplemented from SeExpr2::ExprNode.
Definition at line 884 of file Interpreter.cpp.
virtual LLVM_VALUE SeExpr2::ExprCondNode::codegen (LLVM_BUILDER) virtual
Reimplemented from SeExpr2::ExprNode.
ExprType SeExpr2::ExprCondNode::prep (bool dontNeedScalar, ExprVarEnvBuilder & envBuilder) virtual
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info.
Default is to call prep on children (giving AnyType as desired type). If all children return valid types, returns NoneType. Otherwise, returns ErrorType. Note: Ignores wanted type.
Reimplemented from SeExpr2::ExprNode.
Definition at line 368 of file ExprNode.cpp.
References SeExpr2::ExprNode::_type, SeExpr2::ExprNode::checkCondition(), SeExpr2::ExprNode::checkIsFP(), SeExpr2::ExprNode::checkIsValue(), SeExpr2::ExprNode::child(), SeExpr2::ExprType::isFP(), SeExpr2::ExprType::isString(), SeExpr2::ExprNode::prep(), SeExpr2::ExprType::setLifetime(), SeExpr2::ExprNode::setType(), and SeExpr2::ExprType::valuesCompatible().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprNode.h
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprNode.cpp
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Interpreter.cpp