SeExpr: SeExprEdFileDialog Class Reference
SeExprEdFileDialog Class Reference
#include <SeExprEdFileDialog.h>
Public Member Functions
SeExprEdFileDialog (QWidget *parent=0)
void addLookInEntries (QStringList paths)
void saveLookInEntries ()
void restoreLookInEntries ()
QString getOpenFileName (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getExistingDirectory (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getExistingOrNewDirectory (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QStringList getOpenFileNames (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
QString getSaveFileName (const QString &caption=QString::null, const QString &startWith=QString::null, const QString &filter=QString::null)
void setPreview ()
void resetPreview ()
void addCheckBox (QString s)
void addFavoritesButton (QString dirname, QString linkname, QString linkdir)
bool checkBoxStatus ()
void showCheckBox ()
void hideCheckBox ()
void addComboBox (QString s, QStringList sl)
void showComboBox ()
void hideComboBox ()
QComboBox * getComboBox ()
void setButtonName (const QString &str)
void addSidebarShortcut (const QString &s)
Private Slots
void handleOk ()
void editReturnPress ()
void gotoFavorites ()
void selChanged (const QString &path)
void resetDir ()
Private Attributes
QString _workingDirectory
QString _favDir
QString _temppath
QStringList _lookInList
QLineEdit * _nameEdit
QPushButton * _okButton
bool _createDir
SeExprEdPreviewWidget * _pw
QCheckBox * _cb
QLabel * _combolabel
QComboBox * _combo
Detailed Description
Definition at line 38 of file SeExprEdFileDialog.h.
Constructor & Destructor Documentation
SeExprEdFileDialog::SeExprEdFileDialog (QWidget * parent = 0)
Definition at line 91 of file SeExprEdFileDialog.cpp.
References _cb, _combo, _combolabel, _createDir, _favDir, _nameEdit, _okButton, _pw, _temppath, editReturnPress(), handleOk(), and selChanged().
Member Function Documentation
void SeExprEdFileDialog::addCheckBox (QString s)
Definition at line 403 of file SeExprEdFileDialog.cpp.
References _cb, and _combo.
void SeExprEdFileDialog::addComboBox (QString s, QStringList sl)
Definition at line 430 of file SeExprEdFileDialog.cpp.
References _combo, and _combolabel.
void SeExprEdFileDialog::addFavoritesButton (QString dirname, QString linkname, QString linkdir)
Definition at line 193 of file SeExprEdFileDialog.cpp.
References _favDir, folder_fav, and gotoFavorites().
void SeExprEdFileDialog::addLookInEntries (QStringList paths)
Definition at line 233 of file SeExprEdFileDialog.cpp.
void SeExprEdFileDialog::addSidebarShortcut (const QString & s)
Definition at line 470 of file SeExprEdFileDialog.cpp.
bool SeExprEdFileDialog::checkBoxStatus ()
Definition at line 414 of file SeExprEdFileDialog.cpp.
References _cb.
void SeExprEdFileDialog::editReturnPress () [private, slot]
Definition at line 155 of file SeExprEdFileDialog.cpp.
References _nameEdit, and handleOk().
Referenced by SeExprEdFileDialog().
QComboBox* SeExprEdFileDialog::getComboBox () [inline]
Definition at line 71 of file SeExprEdFileDialog.h.
References _combo.
QString SeExprEdFileDialog::getExistingDirectory (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 325 of file SeExprEdFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
Referenced by SeExprEdStringControl::directoryBrowse(), and getExistingOrNewDirectory().
QString SeExprEdFileDialog::getExistingOrNewDirectory (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 350 of file SeExprEdFileDialog.cpp.
References _createDir, getExistingDirectory(), and resetPreview().
QString SeExprEdFileDialog::getOpenFileName (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 272 of file SeExprEdFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
Referenced by SeExprEdStringControl::fileBrowse().
QStringList SeExprEdFileDialog::getOpenFileNames (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 298 of file SeExprEdFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
QString SeExprEdFileDialog::getSaveFileName (const QString & caption = QString::null, const QString & startWith = QString::null, const QString & filter = QString::null)
Definition at line 360 of file SeExprEdFileDialog.cpp.
References _workingDirectory, makeFiltersList(), and resetPreview().
void SeExprEdFileDialog::gotoFavorites () [private, slot]
Definition at line 228 of file SeExprEdFileDialog.cpp.
References _favDir.
Referenced by addFavoritesButton().
void SeExprEdFileDialog::handleOk () [private, slot]
Definition at line 132 of file SeExprEdFileDialog.cpp.
References _createDir, _nameEdit, _okButton, _temppath, and resetDir().
Referenced by editReturnPress(), and SeExprEdFileDialog().
void SeExprEdFileDialog::hideCheckBox ()
Definition at line 425 of file SeExprEdFileDialog.cpp.
References _cb.
void SeExprEdFileDialog::hideComboBox ()
Definition at line 454 of file SeExprEdFileDialog.cpp.
References _combo, and _combolabel.
void SeExprEdFileDialog::resetDir () [inline, private, slot]
Definition at line 80 of file SeExprEdFileDialog.h.
References _temppath.
Referenced by handleOk().
void SeExprEdFileDialog::resetPreview ()
Definition at line 398 of file SeExprEdFileDialog.cpp.
References _pw, and SeExprEdPreviewWidget::reset().
Referenced by getExistingDirectory(), getExistingOrNewDirectory(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
void SeExprEdFileDialog::restoreLookInEntries ()
Definition at line 250 of file SeExprEdFileDialog.cpp.
References _lookInList.
void SeExprEdFileDialog::saveLookInEntries ()
Definition at line 245 of file SeExprEdFileDialog.cpp.
References _lookInList.
void SeExprEdFileDialog::selChanged (const QString & path) [private, slot]
Definition at line 460 of file SeExprEdFileDialog.cpp.
References _pw, and SeExprEdPreviewWidget::makePreview().
Referenced by SeExprEdFileDialog().
void SeExprEdFileDialog::setButtonName (const QString & str)
Definition at line 465 of file SeExprEdFileDialog.cpp.
References _okButton.
void SeExprEdFileDialog::setPreview ()
Definition at line 387 of file SeExprEdFileDialog.cpp.
References _pw.
Referenced by SeExprEdStringControl::directoryBrowse(), and SeExprEdStringControl::fileBrowse().
void SeExprEdFileDialog::showCheckBox ()
Definition at line 420 of file SeExprEdFileDialog.cpp.
References _cb.
void SeExprEdFileDialog::showComboBox ()
Definition at line 448 of file SeExprEdFileDialog.cpp.
References _combo, and _combolabel.
Member Data Documentation
QCheckBox* SeExprEdFileDialog::_cb [private]
Definition at line 91 of file SeExprEdFileDialog.h.
Referenced by addCheckBox(), checkBoxStatus(), hideCheckBox(), SeExprEdFileDialog(), and showCheckBox().
QComboBox* SeExprEdFileDialog::_combo [private]
Definition at line 93 of file SeExprEdFileDialog.h.
Referenced by addCheckBox(), addComboBox(), getComboBox(), hideComboBox(), SeExprEdFileDialog(), and showComboBox().
QLabel* SeExprEdFileDialog::_combolabel [private]
Definition at line 92 of file SeExprEdFileDialog.h.
Referenced by addComboBox(), hideComboBox(), SeExprEdFileDialog(), and showComboBox().
bool SeExprEdFileDialog::_createDir [private]
Definition at line 89 of file SeExprEdFileDialog.h.
Referenced by getExistingOrNewDirectory(), handleOk(), and SeExprEdFileDialog().
QString SeExprEdFileDialog::_favDir [private]
Definition at line 84 of file SeExprEdFileDialog.h.
Referenced by addFavoritesButton(), gotoFavorites(), and SeExprEdFileDialog().
QStringList SeExprEdFileDialog::_lookInList [private]
Definition at line 86 of file SeExprEdFileDialog.h.
Referenced by restoreLookInEntries(), and saveLookInEntries().
QLineEdit* SeExprEdFileDialog::_nameEdit [private]
Definition at line 87 of file SeExprEdFileDialog.h.
Referenced by editReturnPress(), handleOk(), and SeExprEdFileDialog().
QPushButton* SeExprEdFileDialog::_okButton [private]
Definition at line 88 of file SeExprEdFileDialog.h.
Referenced by handleOk(), SeExprEdFileDialog(), and setButtonName().
SeExprEdPreviewWidget* SeExprEdFileDialog::_pw [private]
Definition at line 90 of file SeExprEdFileDialog.h.
Referenced by resetPreview(), SeExprEdFileDialog(), selChanged(), and setPreview().
QString SeExprEdFileDialog::_temppath [private]
Definition at line 85 of file SeExprEdFileDialog.h.
Referenced by handleOk(), resetDir(), and SeExprEdFileDialog().
QString SeExprEdFileDialog::_workingDirectory [private]
Definition at line 84 of file SeExprEdFileDialog.h.
Referenced by getExistingDirectory(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdFileDialog.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdFileDialog.cpp