SeExpr: SeExprEdStringControl Class Reference
SeExprEdStringControl Class Reference
A control for editing strings, filenames, and directories.
#include <SeExprEdControl.h>
Public Member Functions
SeExprEdStringControl (int id, SeExprEdStringEditable *stringEditable)
Private Slots
void textChanged (const QString &newText)
void fileBrowse ()
void directoryBrowse ()
Private Member Functions
void updateControl ()
Private Attributes
SeExprEdStringEditable * _stringEditable
model for the string control
QLineEdit * _edit
Edit box for the string.
Detailed Description
A control for editing strings, filenames, and directories.
Definition at line 205 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdStringControl::SeExprEdStringControl (int id, SeExprEdStringEditable * stringEditable)
Definition at line 493 of file SeExprEdControl.cpp.
References _edit, _stringEditable, directoryBrowse(), directoryXPM, fileBrowse(), fileXPM, SeExprEdControl::hbox, textChanged(), SeExprEdStringEditable::type, and updateControl().
Member Function Documentation
void SeExprEdStringControl::directoryBrowse () [private, slot]
Definition at line 530 of file SeExprEdControl.cpp.
References _edit, SeExprEdFileDialog::getExistingDirectory(), and SeExprEdFileDialog::setPreview().
Referenced by SeExprEdStringControl().
void SeExprEdStringControl::fileBrowse () [private, slot]
Definition at line 522 of file SeExprEdControl.cpp.
References _edit, SeExprEdFileDialog::getOpenFileName(), and SeExprEdFileDialog::setPreview().
Referenced by SeExprEdStringControl().
void SeExprEdStringControl::textChanged (const QString & newText) [private, slot]
Definition at line 543 of file SeExprEdControl.cpp.
References SeExprEdControl::_id, _stringEditable, SeExprEdControl::_updating, SeExprEdControl::controlChanged(), and SeExprEdStringEditable::v.
Referenced by SeExprEdStringControl().
void SeExprEdStringControl::updateControl () [private]
Definition at line 538 of file SeExprEdControl.cpp.
References _edit, _stringEditable, and SeExprEdStringEditable::v.
Referenced by SeExprEdStringControl().
Member Data Documentation
QLineEdit* SeExprEdStringControl::_edit [private]
Edit box for the string.
Definition at line 212 of file SeExprEdControl.h.
Referenced by directoryBrowse(), fileBrowse(), SeExprEdStringControl(), and updateControl().
SeExprEdStringEditable* SeExprEdStringControl::_stringEditable [private]
model for the string control
Definition at line 210 of file SeExprEdControl.h.
Referenced by SeExprEdStringControl(), textChanged(), and updateControl().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp