SeExpr: SeExprIfThenElseNode Class Reference
SeExprIfThenElseNode Class Reference
Node that computes local variables before evaluating expression.
#include <SeExprNode.h>
Public Member Functions
SeExprIfThenElseNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b, SeExprNode *c)
virtual bool prep (bool wantVec, std::string &error)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that computes local variables before evaluating expression.
Definition at line 130 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprIfThenElseNode::SeExprIfThenElseNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b, SeExprNode * c) [inline]
Definition at line 133 of file SeExprNode.h.
Member Function Documentation
void SeExprIfThenElseNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 212 of file SeExprNode.cpp.
References SeExprNode::child(), and SeExprNode::eval().
bool SeExprIfThenElseNode::prep (bool wantVec, std::string & error) [virtual]
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprNode.
Definition at line 197 of file SeExprNode.cpp.
References SeExprNode::_isVec, and SeExprNode::child().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp