SeExpr: DeepWaterScene Class Reference
DeepWaterScene Class Reference
#include <ExprDeepWater.h>
Public Slots
void resolutionChanged (int val)
void tileSizeChanged (double val)
void lengthCutoffChanged (double val)
void amplitudeChanged (double val)
void windAngleChanged (double val)
void windSpeedChanged (double val)
void flowDirectionChanged (QString val)
void directionalFactorExponentChanged (double val)
void directionalReflectionDampingChanged (double val)
void sharpenChanged (double val)
void resize (const int width, const int height)
Signals
void deepWaterChanged ()
Public Member Functions
DeepWaterScene ()
~DeepWaterScene ()
void setParams (const SeDeepWaterParams &paramsIn)
void drawRect ()
void drawPoly ()
void drawGrid ()
void emitDeepWaterChanged ()
void rebuildDeepWater ()
Public Attributes
SeDeepWaterParams params
Private Types
typedef SeDeepWater< double > T_CURVE
Private Attributes
T_CURVE * _curve
int _width
int _height
QGraphicsPolygonItem * _curvePoly
QGraphicsRectItem * _baseRect
QGraphicsRectItem * _gridRect
Friends
class ExprDeepWater
Detailed Description
Definition at line 200 of file ExprDeepWater.h.
Member Typedef Documentation
typedef SeDeepWater<double> DeepWaterScene::T_CURVE private
Definition at line 204 of file ExprDeepWater.h.
Constructor & Destructor Documentation
DeepWaterScene::DeepWaterScene ()
Definition at line 40 of file ExprDeepWater.cpp.
References _height, _width, and resize().
DeepWaterScene::~DeepWaterScene ()
Definition at line 45 of file ExprDeepWater.cpp.
References _curve.
Member Function Documentation
void DeepWaterScene::amplitudeChanged (double val) slot
Definition at line 79 of file ExprDeepWater.cpp.
References SeDeepWaterParams::amplitude, params, and setParams().
void DeepWaterScene::deepWaterChanged () signal
Referenced by emitDeepWaterChanged().
void DeepWaterScene::directionalFactorExponentChanged (double val) slot
Definition at line 106 of file ExprDeepWater.cpp.
References SeDeepWaterParams::directionalFactorExponent, params, and setParams().
void DeepWaterScene::directionalReflectionDampingChanged (double val) slot
Definition at line 112 of file ExprDeepWater.cpp.
References SeDeepWaterParams::directionalReflectionDamping, params, and setParams().
void DeepWaterScene::drawGrid ()
Definition at line 178 of file ExprDeepWater.cpp.
References _curve, _gridRect, _height, _width, SeDeepWater< T >::getKHigh(), SeDeepWater< T >::getKLow(), and SeDeepWater< T >::inGrid().
Referenced by resize(), and setParams().
void DeepWaterScene::drawPoly ()
Definition at line 159 of file ExprDeepWater.cpp.
References _curve, _curvePoly, _height, _width, SeDeepWater< T >::getValue(), and x.
Referenced by resize(), and setParams().
void DeepWaterScene::drawRect ()
Definition at line 148 of file ExprDeepWater.cpp.
References _baseRect, _height, and _width.
Referenced by resize().
void DeepWaterScene::emitDeepWaterChanged ()
Definition at line 142 of file ExprDeepWater.cpp.
References deepWaterChanged().
Referenced by setParams().
void DeepWaterScene::flowDirectionChanged (QString val) slot
Definition at line 97 of file ExprDeepWater.cpp.
References components(), SeDeepWaterParams::flowDirection, params, and setParams().
void DeepWaterScene::lengthCutoffChanged (double val) slot
Definition at line 73 of file ExprDeepWater.cpp.
References SeDeepWaterParams::lengthCutoff, params, and setParams().
void DeepWaterScene::rebuildDeepWater ()
Definition at line 133 of file ExprDeepWater.cpp.
References _curve, SeDeepWater< T >::generateSpectrum(), params, and SeDeepWater< T >::setParams().
Referenced by setParams().
void DeepWaterScene::resize (const int width, const int height) slot
Definition at line 50 of file ExprDeepWater.cpp.
References _height, _width, drawGrid(), drawPoly(), and drawRect().
Referenced by DeepWaterScene().
void DeepWaterScene::resolutionChanged (int val) slot
Definition at line 61 of file ExprDeepWater.cpp.
References params, SeDeepWaterParams::resolution, and setParams().
void DeepWaterScene::setParams (const SeDeepWaterParams & paramsIn)
Definition at line 124 of file ExprDeepWater.cpp.
References drawGrid(), drawPoly(), emitDeepWaterChanged(), params, and rebuildDeepWater().
Referenced by amplitudeChanged(), directionalFactorExponentChanged(), directionalReflectionDampingChanged(), flowDirectionChanged(), lengthCutoffChanged(), resolutionChanged(), ExprDeepWater::setParams(), sharpenChanged(), tileSizeChanged(), windAngleChanged(), and windSpeedChanged().
void DeepWaterScene::sharpenChanged (double val) slot
Definition at line 118 of file ExprDeepWater.cpp.
References params, setParams(), and SeDeepWaterParams::sharpen.
void DeepWaterScene::tileSizeChanged (double val) slot
Definition at line 67 of file ExprDeepWater.cpp.
References params, setParams(), and SeDeepWaterParams::tileSize.
void DeepWaterScene::windAngleChanged (double val) slot
Definition at line 85 of file ExprDeepWater.cpp.
References params, setParams(), and SeDeepWaterParams::windAngle.
void DeepWaterScene::windSpeedChanged (double val) slot
Definition at line 91 of file ExprDeepWater.cpp.
References params, setParams(), and SeDeepWaterParams::windSpeed.
Friends And Related Function Documentation
friend class ExprDeepWater friend
Definition at line 219 of file ExprDeepWater.h.
Member Data Documentation
QGraphicsRectItem* DeepWaterScene::_baseRect private
Definition at line 246 of file ExprDeepWater.h.
Referenced by drawRect().
T_CURVE* DeepWaterScene::_curve private
Definition at line 224 of file ExprDeepWater.h.
Referenced by drawGrid(), drawPoly(), rebuildDeepWater(), and ~DeepWaterScene().
QGraphicsPolygonItem* DeepWaterScene::_curvePoly private
Definition at line 245 of file ExprDeepWater.h.
Referenced by drawPoly().
QGraphicsRectItem* DeepWaterScene::_gridRect private
Definition at line 247 of file ExprDeepWater.h.
Referenced by drawGrid().
int DeepWaterScene::_height private
Definition at line 244 of file ExprDeepWater.h.
Referenced by DeepWaterScene(), drawGrid(), drawPoly(), drawRect(), and resize().
int DeepWaterScene::_width private
Definition at line 243 of file ExprDeepWater.h.
Referenced by DeepWaterScene(), drawGrid(), drawPoly(), drawRect(), and resize().
SeDeepWaterParams DeepWaterScene::params
Definition at line 221 of file ExprDeepWater.h.
Referenced by amplitudeChanged(), DeepWaterControl::deepWaterChanged(), directionalFactorExponentChanged(), directionalReflectionDampingChanged(), flowDirectionChanged(), lengthCutoffChanged(), rebuildDeepWater(), resolutionChanged(), setParams(), sharpenChanged(), tileSizeChanged(), windAngleChanged(), and windSpeedChanged().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDeepWater.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDeepWater.cpp