SeExpr: SeExprEdBrowser Class Reference
SeExprEdBrowser Class Reference
#include <SeExprEdBrowser.h>
Public Slots
void handleSelection (const QModelIndex &current, const QModelIndex &previous)
void update ()
void clear ()
void clearSelection ()
void saveExpression ()
void saveLocalExpressionAs ()
void saveExpressionAs ()
Public Member Functions
SeExprEdBrowser (QWidget *parent, SeExprEditor *editor)
~SeExprEdBrowser ()
void addPath (const std::string &name, const std::string &path)
std::string getSelectedPath ()
void selectPath (const char *path)
bool getExpressionDirs ()
bool getExpressionDirs (const std::string &context)
void setSearchPath (const QString &context, const QString &path)
void expandAll ()
Private Slots
void clearFilter ()
void filterChanged (const QString &str)
Private Attributes
SeExprEditor * editor
QList< QString > labels
QList< QString > paths
SeExprEdTreeModel * treeModel
SeExprEdTreeFilterModel * proxyModel
QTreeView * treeNew
QLineEdit * exprFilter
std::string _userExprDir
std::string _localExprDir
std::string _context
std::string _searchPath
Detailed Description
Definition at line 37 of file SeExprEdBrowser.h.
Constructor & Destructor Documentation
SeExprEdBrowser::SeExprEdBrowser (QWidget * parent, SeExprEditor * editor)
Definition at line 256 of file SeExprEdBrowser.cpp.
References clearFilter(), exprFilter, filterChanged(), handleSelection(), proxyModel, treeModel, and treeNew.
SeExprEdBrowser::~SeExprEdBrowser ()
Definition at line 251 of file SeExprEdBrowser.cpp.
References treeModel.
Member Function Documentation
void SeExprEdBrowser::addPath (const std::string & name, const std::string & path)
Definition at line 289 of file SeExprEdBrowser.cpp.
References SeExprEdTreeModel::addPath(), labels, paths, and treeModel.
Referenced by getExpressionDirs().
void SeExprEdBrowser::clear () [slot]
Definition at line 340 of file SeExprEdBrowser.cpp.
References SeExprEdTreeModel::clear(), clearSelection(), labels, paths, and treeModel.
Referenced by getExpressionDirs().
void SeExprEdBrowser::clearFilter () [private, slot]
Definition at line 355 of file SeExprEdBrowser.cpp.
References exprFilter.
Referenced by SeExprEdBrowser().
void SeExprEdBrowser::clearSelection () [slot]
Definition at line 350 of file SeExprEdBrowser.cpp.
References treeNew.
Referenced by clear(), and SeExprEdDialog::clearExpression().
void SeExprEdBrowser::expandAll ()
Definition at line 437 of file SeExprEdBrowser.cpp.
References treeNew.
Referenced by SeExprEdDialog::exec(), and SeExprEdShortEdit::showDetails().
void SeExprEdBrowser::filterChanged (const QString & str) [private, slot]
Definition at line 360 of file SeExprEdBrowser.cpp.
References proxyModel, and treeNew.
Referenced by SeExprEdBrowser().
bool SeExprEdBrowser::getExpressionDirs (const std::string & context)
bool SeExprEdBrowser::getExpressionDirs ()
Definition at line 448 of file SeExprEdBrowser.cpp.
References _context, _localExprDir, _searchPath, _userExprDir, addPath(), clear(), context, P3D_CONFIG_ENVVAR, and update().
Referenced by SeExprEdDialog::exec().
std::string SeExprEdBrowser::getSelectedPath ()
Definition at line 302 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::path, proxyModel, and treeNew.
Referenced by saveExpression().
void SeExprEdBrowser::handleSelection (const QModelIndex & current, const QModelIndex & previous) [slot]
Definition at line 325 of file SeExprEdBrowser.cpp.
References editor, SeExprEdTreeItem::path, proxyModel, and SeExprEditor::setExpr().
Referenced by SeExprEdBrowser().
void SeExprEdBrowser::saveExpression () [slot]
Definition at line 418 of file SeExprEdBrowser.cpp.
References editor, SeExprEditor::getExpr(), getSelectedPath(), and saveExpressionAs().
void SeExprEdBrowser::saveExpressionAs () [slot]
Definition at line 371 of file SeExprEdBrowser.cpp.
References _userExprDir, editor, SeExprEditor::getExpr(), selectPath(), and update().
Referenced by saveExpression().
void SeExprEdBrowser::saveLocalExpressionAs () [slot]
Definition at line 394 of file SeExprEdBrowser.cpp.
References _localExprDir, editor, SeExprEditor::getExpr(), selectPath(), and update().
void SeExprEdBrowser::selectPath (const char * path)
Definition at line 313 of file SeExprEdBrowser.cpp.
References SeExprEdTreeModel::find(), index(), proxyModel, treeModel, and treeNew.
Referenced by saveExpressionAs(), and saveLocalExpressionAs().
void SeExprEdBrowser::setSearchPath (const QString & context, const QString & path)
Definition at line 296 of file SeExprEdBrowser.cpp.
References _context, and _searchPath.
Referenced by SeExprEdShortEdit::showDetails().
void SeExprEdBrowser::update () [slot]
Definition at line 319 of file SeExprEdBrowser.cpp.
References proxyModel, treeModel, SeExprEdTreeFilterModel::update(), and SeExprEdTreeModel::update().
Referenced by getExpressionDirs(), saveExpressionAs(), and saveLocalExpressionAs().
Member Data Documentation
std::string SeExprEdBrowser::_context [private]
Definition at line 50 of file SeExprEdBrowser.h.
Referenced by getExpressionDirs(), and setSearchPath().
std::string SeExprEdBrowser::_localExprDir [private]
Definition at line 49 of file SeExprEdBrowser.h.
Referenced by getExpressionDirs(), and saveLocalExpressionAs().
std::string SeExprEdBrowser::_searchPath [private]
Definition at line 51 of file SeExprEdBrowser.h.
Referenced by getExpressionDirs(), and setSearchPath().
std::string SeExprEdBrowser::_userExprDir [private]
Definition at line 48 of file SeExprEdBrowser.h.
Referenced by getExpressionDirs(), and saveExpressionAs().
SeExprEditor* SeExprEdBrowser::editor [private]
Definition at line 41 of file SeExprEdBrowser.h.
Referenced by handleSelection(), saveExpression(), saveExpressionAs(), and saveLocalExpressionAs().
QLineEdit* SeExprEdBrowser::exprFilter [private]
Definition at line 47 of file SeExprEdBrowser.h.
Referenced by clearFilter(), and SeExprEdBrowser().
QList<QString> SeExprEdBrowser::labels [private]
Definition at line 42 of file SeExprEdBrowser.h.
Referenced by addPath(), and clear().
QList<QString> SeExprEdBrowser::paths [private]
Definition at line 43 of file SeExprEdBrowser.h.
Referenced by addPath(), and clear().
SeExprEdTreeFilterModel* SeExprEdBrowser::proxyModel [private]
Definition at line 45 of file SeExprEdBrowser.h.
Referenced by filterChanged(), getSelectedPath(), handleSelection(), SeExprEdBrowser(), selectPath(), and update().
SeExprEdTreeModel* SeExprEdBrowser::treeModel [private]
Definition at line 44 of file SeExprEdBrowser.h.
Referenced by addPath(), clear(), SeExprEdBrowser(), selectPath(), update(), and ~SeExprEdBrowser().
QTreeView* SeExprEdBrowser::treeNew [private]
Definition at line 46 of file SeExprEdBrowser.h.
Referenced by clearSelection(), expandAll(), filterChanged(), getSelectedPath(), SeExprEdBrowser(), and selectPath().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdBrowser.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdBrowser.cpp