SeExpr: SeExprAssignNode Class Reference
SeExprAssignNode Class Reference
Node that compute a local variable assignment.
#include <SeExprNode.h>
Public Member Functions
SeExprAssignNode (const SeExpression *expr, const char *name, SeExprNode *e)
virtual bool prep (bool wantVec, std::string &error)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Private Attributes
std::string _name
SeExprLocalVarRef * _var
Detailed Description
Node that compute a local variable assignment.
Definition at line 143 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprAssignNode::SeExprAssignNode (const SeExpression * expr, const char * name, SeExprNode * e) [inline]
Definition at line 146 of file SeExprNode.h.
Member Function Documentation
void SeExprAssignNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 240 of file SeExprNode.cpp.
References _var, SeExprNode::child(), SeExprNode::eval(), SeExprNode::isVec(), SeExprLocalVarRef::isVec(), and SeExprLocalVarRef::val.
bool SeExprAssignNode::prep (bool wantVec, std::string & error) [virtual]
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprNode.
Definition at line 226 of file SeExprNode.cpp.
References SeExprNode::_expr, SeExprNode::_isVec, _name, _var, SeExprNode::child(), SeExpression::getLocalVar(), SeExprNode::isVec(), and SeExprLocalVarRef::setIsVec().
Member Data Documentation
std::string SeExprAssignNode::_name [private]
Definition at line 153 of file SeExprNode.h.
Referenced by prep().
SeExprLocalVarRef* SeExprAssignNode::_var [private]
Definition at line 154 of file SeExprNode.h.
Referenced by eval(), and prep().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp