SeExpr: ExprColorCurve Class Reference
ExprColorCurve Class Reference
#include <ExprColorCurve.h>
Public Slots
void cvSelectedSlot (const double pos, const SeExpr2::Vec3d val, const T_INTERP interp)
void selPosChanged ()
void openDetail ()
Signals
void selPosChangedSignal (double pos)
void selValChangedSignal (SeExpr2::Vec3d val)
void swatchChanged (QColor color)
Public Member Functions
ExprColorCurve (QWidget *parent=0, QString pLabel="", QString vLabel="", QString iLabel="", bool expandable=true)
~ExprColorCurve ()
void addPoint (const double x, const SeExpr2::Vec3d y, const T_INTERP interp, bool select=false)
void setSwatchColor (QColor color)
QColor getSwatchColor ()
Public Attributes
CCurveScene * _scene
Private Types
typedef SeExpr2::Curve
< SeExpr2::Vec3d > T_CURVE
typedef T_CURVE::InterpType T_INTERP
Private Slots
void internalSwatchChanged (QColor color)
Private Attributes
QLineEdit * _selPosEdit
ExprCSwatchFrame * _selValEdit
QComboBox * _interpComboBox
Detailed Description
Definition at line 144 of file ExprColorCurve.h.
Member Typedef Documentation
typedef SeExpr2::Curve<SeExpr2::Vec3d> ExprColorCurve::T_CURVE private
Definition at line 148 of file ExprColorCurve.h.
typedef T_CURVE::InterpType ExprColorCurve::T_INTERP private
Definition at line 149 of file ExprColorCurve.h.
Constructor & Destructor Documentation
ExprColorCurve::ExprColorCurve (QWidget * parent = 0, QString pLabel = "", QString vLabel = "", QString iLabel = "", bool expandable = true)
Definition at line 386 of file ExprColorCurve.cpp.
References _interpComboBox, _scene, _selPosEdit, _selValEdit, cvSelectedSlot(), internalSwatchChanged(), openDetail(), selPosChanged(), selPosChangedSignal(), selValChangedSignal(), and swatchChanged().
Referenced by openDetail().
ExprColorCurve::~ExprColorCurve () inline
Definition at line 154 of file ExprColorCurve.h.
Member Function Documentation
void ExprColorCurve::addPoint (const double x, const SeExpr2::Vec3d y, const T_INTERP interp, bool select = false)
Definition at line 524 of file ExprColorCurve.cpp.
References _scene, and CCurveScene::addPoint().
Referenced by CCurveControl::CCurveControl(), and openDetail().
void ExprColorCurve::cvSelectedSlot (const double pos, const SeExpr2::Vec3d val, const T_INTERP interp) slot
Definition at line 504 of file ExprColorCurve.cpp.
References _interpComboBox, _selPosEdit, _selValEdit, ExprCSwatchFrame::setValue(), and swatchChanged().
Referenced by ExprColorCurve().
QColor ExprColorCurve::getSwatchColor ()
Definition at line 536 of file ExprColorCurve.cpp.
References _selValEdit, and ExprCSwatchFrame::getValue().
Referenced by CCurveControl::getColor().
void ExprColorCurve::internalSwatchChanged (QColor color) private slot
Definition at line 542 of file ExprColorCurve.cpp.
References swatchChanged().
Referenced by ExprColorCurve().
void ExprColorCurve::openDetail () slot
Definition at line 547 of file ExprColorCurve.cpp.
References CCurveScene::_cvs, _scene, addPoint(), SeExpr2::curve, CCurveScene::emitCurveChanged(), ExprColorCurve(), and CCurveScene::removeAll().
Referenced by ExprColorCurve().
void ExprColorCurve::selPosChanged () slot
Definition at line 517 of file ExprColorCurve.cpp.
References _selPosEdit, SeExpr2::clamp(), and selPosChangedSignal().
Referenced by ExprColorCurve().
void ExprColorCurve::selPosChangedSignal (double pos) signal
Referenced by ExprColorCurve(), and selPosChanged().
void ExprColorCurve::selValChangedSignal (SeExpr2::Vec3d val) signal
Referenced by ExprColorCurve().
void ExprColorCurve::setSwatchColor (QColor color)
Definition at line 529 of file ExprColorCurve.cpp.
References _scene, _selValEdit, CCurveScene::selValChanged(), and ExprCSwatchFrame::setValue().
Referenced by CCurveControl::setColor().
void ExprColorCurve::swatchChanged (QColor color) signal
Referenced by cvSelectedSlot(), ExprColorCurve(), and internalSwatchChanged().
Member Data Documentation
QComboBox* ExprColorCurve::_interpComboBox private
Definition at line 179 of file ExprColorCurve.h.
Referenced by cvSelectedSlot(), and ExprColorCurve().
CCurveScene* ExprColorCurve::_scene
Definition at line 161 of file ExprColorCurve.h.
Referenced by addPoint(), CCurveControl::CCurveControl(), CCurveControl::curveChanged(), ExprColorCurve(), openDetail(), and setSwatchColor().
QLineEdit* ExprColorCurve::_selPosEdit private
Definition at line 177 of file ExprColorCurve.h.
Referenced by cvSelectedSlot(), ExprColorCurve(), and selPosChanged().
ExprCSwatchFrame* ExprColorCurve::_selValEdit private
Definition at line 178 of file ExprColorCurve.h.
Referenced by cvSelectedSlot(), ExprColorCurve(), getSwatchColor(), and setSwatchColor().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorCurve.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprColorCurve.cpp