SeExpr: SeExprAndNode Class Reference
SeExprAndNode Class Reference
Node that evaluates a logical AND.
#include <SeExprNode.h>
Public Member Functions
SeExprAndNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual bool prep (bool wantVec, std::string &error)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that evaluates a logical AND.
Definition at line 215 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprAndNode::SeExprAndNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 218 of file SeExprNode.h.
Member Function Documentation
void SeExprAndNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 313 of file SeExprNode.cpp.
References a, b, SeExprNode::child(), and SeExprNode::eval().
bool SeExprAndNode::prep (bool wantVec, std::string & error) [virtual]
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info. NOTE: error is deprecated, instead use addError() function for better error localization
Reimplemented from SeExprNode.
Definition at line 303 of file SeExprNode.cpp.
References SeExprNode::_isVec, and SeExprNode::prep().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp