SeExpr: SeExprEdTreeItem Class Reference
SeExprEdTreeItem Class Reference
Public Member Functions
SeExprEdTreeItem (SeExprEdTreeItem *parent, const QString &label, const QString &path)
~SeExprEdTreeItem ()
SeExprEdTreeItem * find (QString path)
void clear ()
void populate ()
void addChild (SeExprEdTreeItem *child)
SeExprEdTreeItem * getChild (const int row)
int getChildCount ()
void regen ()
Public Attributes
int row
SeExprEdTreeItem * parent
QString label
QString path
Private Attributes
std::vector< SeExprEdTreeItem * > children
bool populated
Detailed Description
Definition at line 36 of file SeExprEdBrowser.cpp.
Constructor & Destructor Documentation
SeExprEdTreeItem::SeExprEdTreeItem (SeExprEdTreeItem * parent, const QString & label, const QString & path) [inline]
Definition at line 39 of file SeExprEdBrowser.cpp.
Referenced by populate(), and regen().
SeExprEdTreeItem::~SeExprEdTreeItem () [inline]
Definition at line 43 of file SeExprEdBrowser.cpp.
References children.
Member Function Documentation
void SeExprEdTreeItem::addChild (SeExprEdTreeItem * child) [inline]
Definition at line 88 of file SeExprEdBrowser.cpp.
References children, and row.
Referenced by SeExprEdTreeModel::addPath(), populate(), and regen().
void SeExprEdTreeItem::clear () [inline]
Definition at line 62 of file SeExprEdBrowser.cpp.
References children.
Referenced by SeExprEdTreeModel::clear().
SeExprEdTreeItem* SeExprEdTreeItem::find (QString path) [inline]
Definition at line 49 of file SeExprEdBrowser.cpp.
References children, and populate().
Referenced by SeExprEdTreeModel::find().
SeExprEdTreeItem* SeExprEdTreeItem::getChild (const int row) [inline]
Definition at line 94 of file SeExprEdBrowser.cpp.
References children, and populate().
Referenced by SeExprEdTreeModel::index().
int SeExprEdTreeItem::getChildCount () [inline]
Definition at line 103 of file SeExprEdBrowser.cpp.
References children, and populate().
Referenced by SeExprEdTreeModel::rowCount().
void SeExprEdTreeItem::populate () [inline]
Definition at line 70 of file SeExprEdBrowser.cpp.
References addChild(), path, populated, and SeExprEdTreeItem().
Referenced by find(), getChild(), and getChildCount().
void SeExprEdTreeItem::regen () [inline]
Definition at line 109 of file SeExprEdBrowser.cpp.
References addChild(), children, label, path, and SeExprEdTreeItem().
Referenced by SeExprEdTreeModel::find().
Member Data Documentation
std::vector<SeExprEdTreeItem*> SeExprEdTreeItem::children [private]
Definition at line 129 of file SeExprEdBrowser.cpp.
Referenced by addChild(), clear(), find(), getChild(), getChildCount(), regen(), and ~SeExprEdTreeItem().
QString SeExprEdTreeItem::label
Definition at line 126 of file SeExprEdBrowser.cpp.
Referenced by SeExprEdTreeModel::data(), and regen().
SeExprEdTreeItem* SeExprEdTreeItem::parent
Definition at line 125 of file SeExprEdBrowser.cpp.
Referenced by SeExprEdTreeModel::parent().
QString SeExprEdTreeItem::path
Definition at line 127 of file SeExprEdBrowser.cpp.
Referenced by SeExprEdBrowser::getSelectedPath(), SeExprEdBrowser::handleSelection(), populate(), and regen().
bool SeExprEdTreeItem::populated [private]
Definition at line 130 of file SeExprEdBrowser.cpp.
Referenced by populate().
int SeExprEdTreeItem::row
Definition at line 124 of file SeExprEdBrowser.cpp.
Referenced by addChild(), SeExprEdTreeModel::find(), and SeExprEdTreeModel::parent().
The documentation for this class was generated from the following file:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdBrowser.cpp