SeExpr: ExprShortTextEdit Class Reference
ExprShortTextEdit Class Reference
#include <ExprShortEdit.h>
Signals
void editingFinished ()
Public Member Functions
ExprShortTextEdit (QWidget *parent)
Public Attributes
QCompleter * completer
ExprCompletionModel * completionModel
Protected Member Functions
void showTip (const QString &string)
void hideTip ()
void paintEvent (QPaintEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
virtual void focusInEvent (QFocusEvent *e)
virtual void focusOutEvent (QFocusEvent *e)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *e)
void setColor (bool editing)
void finishEdit ()
Private Slots
void insertCompletion (const QString &completion)
Private Attributes
ExprHighlighter * highlighter
bool editing
QString savedText
ExprPopupDoc * _tip
QStyle * lastStyleForHighlighter
Detailed Description
Definition at line 121 of file ExprShortEdit.h.
Constructor & Destructor Documentation
ExprShortTextEdit::ExprShortTextEdit (QWidget * parent)
Definition at line 342 of file ExprShortEdit.cpp.
References completer, completionModel, ExprHighlighter::fixStyle(), highlighter, insertCompletion(), and lastStyleForHighlighter.
Member Function Documentation
void ExprShortTextEdit::editingFinished () signal
Referenced by finishEdit().
void ExprShortTextEdit::finishEdit () protected
Definition at line 543 of file ExprShortEdit.cpp.
References editing, editingFinished(), and setColor().
Referenced by focusOutEvent(), and keyPressEvent().
void ExprShortTextEdit::focusInEvent (QFocusEvent * e) protected virtual
Definition at line 371 of file ExprShortEdit.cpp.
References completer.
void ExprShortTextEdit::focusOutEvent (QFocusEvent * e) protected virtual
Definition at line 378 of file ExprShortEdit.cpp.
References finishEdit(), hideTip(), and setColor().
void ExprShortTextEdit::hideTip () protected
Definition at line 525 of file ExprShortEdit.cpp.
References _tip.
Referenced by focusOutEvent(), keyPressEvent(), mouseDoubleClickEvent(), and mousePressEvent().
void ExprShortTextEdit::insertCompletion (const QString & completion) private slot
Definition at line 530 of file ExprShortEdit.cpp.
References completer.
Referenced by ExprShortTextEdit().
void ExprShortTextEdit::keyPressEvent (QKeyEvent * e) protected virtual
Definition at line 412 of file ExprShortEdit.cpp.
References completer, completionModel, editing, finishEdit(), ExprCompletionModel::getDocString(), hideTip(), index(), savedText, setColor(), and showTip().
void ExprShortTextEdit::mouseDoubleClickEvent (QMouseEvent * event) protected virtual
Definition at line 396 of file ExprShortEdit.cpp.
References hideTip().
void ExprShortTextEdit::mousePressEvent (QMouseEvent * event) protected virtual
Definition at line 390 of file ExprShortEdit.cpp.
References hideTip().
void ExprShortTextEdit::paintEvent (QPaintEvent * e) protected
Definition at line 402 of file ExprShortEdit.cpp.
References ExprHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
void ExprShortTextEdit::setColor (bool editing) protected
Definition at line 553 of file ExprShortEdit.cpp.
Referenced by finishEdit(), focusOutEvent(), and keyPressEvent().
void ExprShortTextEdit::showTip (const QString & string) protected
Definition at line 511 of file ExprShortEdit.cpp.
References _tip.
Referenced by keyPressEvent().
virtual void ExprShortTextEdit::wheelEvent (QWheelEvent * e) inline protected virtual
Definition at line 148 of file ExprShortEdit.h.
Member Data Documentation
ExprPopupDoc* ExprShortTextEdit::_tip private
Definition at line 129 of file ExprShortEdit.h.
Referenced by hideTip(), and showTip().
QCompleter* ExprShortTextEdit::completer
Definition at line 133 of file ExprShortEdit.h.
Referenced by ExprShortTextEdit(), focusInEvent(), insertCompletion(), keyPressEvent(), ExprShortEdit::rebuildControls(), and ExprShortEdit::updateCompleter().
ExprCompletionModel* ExprShortTextEdit::completionModel
Definition at line 134 of file ExprShortEdit.h.
Referenced by ExprShortEdit::clearExtraCompleters(), ExprShortTextEdit(), keyPressEvent(), ExprShortEdit::rebuildControls(), ExprShortEdit::registerExtraFunction(), ExprShortEdit::registerExtraVariable(), ExprShortEdit::showDetails(), and ExprShortEdit::updateCompleter().
bool ExprShortTextEdit::editing private
Definition at line 127 of file ExprShortEdit.h.
Referenced by finishEdit(), and keyPressEvent().
ExprHighlighter* ExprShortTextEdit::highlighter private
Definition at line 123 of file ExprShortEdit.h.
Referenced by ExprShortTextEdit(), and paintEvent().
QStyle* ExprShortTextEdit::lastStyleForHighlighter private
Definition at line 130 of file ExprShortEdit.h.
Referenced by ExprShortTextEdit(), and paintEvent().
QString ExprShortTextEdit::savedText private
Definition at line 128 of file ExprShortEdit.h.
Referenced by keyPressEvent().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprShortEdit.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprShortEdit.cpp