SeExpr: SeExpr2::CurveFuncX Class Reference
SeExpr2::CurveFuncX Class Reference
Public Member Functions
CurveFuncX ()
virtual ExprType prep (ExprFuncNode *node, bool scalarWanted, ExprVarEnvBuilder &envBuilder) const
virtual ExprFuncNode::Data * evalConstant (const ExprFuncNode *node, ArgHandle args) const
virtual void eval (ArgHandle args)
Public Member Functions inherited from SeExpr2::ExprFuncSimple
ExprFuncSimple (const bool threadSafe)
virtual int buildInterpreter (const ExprFuncNode *node, Interpreter *interpreter) const
Build an interpreter to evaluate the expression.
Public Member Functions inherited from SeExpr2::ExprFuncX
ExprFuncX (const bool threadSafe)
virtual ExprType type () const
virtual ~ExprFuncX ()
bool isThreadSafe () const
virtual size_t sizeInBytes () const
Return memory usage of a funcX in bytes.
virtual void statistics (Statistics &) const
Give this function a chance to populate its statistics.
Additional Inherited Members
Protected Attributes inherited from SeExpr2::ExprFuncX
bool _isScalar
ExprType _type
Detailed Description
Definition at line 1296 of file ExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr2::CurveFuncX::CurveFuncX () inline
Definition at line 1298 of file ExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr2::CurveFuncX::eval (ArgHandle args) inline virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 1335 of file ExprBuiltins.cpp.
References SeExpr2::CurveData< T >::curve, SeExpr2::ExprFuncSimple::ArgHandle::data, SeExpr2::ExprFuncSimple::ArgHandle::inFp(), and SeExpr2::ExprFuncSimple::ArgHandle::outFp.
virtual ExprFuncNode::Data* SeExpr2::CurveFuncX::evalConstant (const ExprFuncNode * node, ArgHandle args) const inline virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 1318 of file ExprBuiltins.cpp.
References SeExpr2::CurveData< T >::curve, SeExpr2::ExprFuncSimple::ArgHandle::inFp(), and SeExpr2::ExprFuncSimple::ArgHandle::nargs().
virtual ExprType SeExpr2::CurveFuncX::prep (ExprFuncNode * node, bool scalarWanted, ExprVarEnvBuilder & env) const inline virtual
prep the expression by doing all type checking argument checking, etc.
Implements SeExpr2::ExprFuncSimple.
Definition at line 1300 of file ExprBuiltins.cpp.
References SeExpr2::ExprNode::addError(), SeExpr2::ExprFuncNode::checkArg(), SeExpr2::ExprType::Error(), SeExpr2::ExprType::FP(), SeExpr2::ExprNode::numChildren(), and SeExpr2::ExprType::Varying().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprBuiltins.cpp