SeExpr: SeExpr2::LLVMEvaluator Class Reference
SeExpr2::LLVMEvaluator Class Reference
#include <Evaluator.h>
Public Member Functions
void unsupported ()
const char * evalStr (VarBlock *varBlock)
const double * evalFP (VarBlock *varBlock)
bool prepLLVM (ExprNode *parseTree, ExprType desiredReturnType)
void evalMultiple (VarBlock *varBlock, int outputVarBlockOffset, size_t rangeStart, size_t rangeEnd)
void debugPrint ()
Detailed Description
Definition at line 348 of file Evaluator.h.
Member Function Documentation
void SeExpr2::LLVMEvaluator::debugPrint () inline
Definition at line 360 of file Evaluator.h.
Referenced by SeExpr2::Expression::debugPrintLLVM().
const double* SeExpr2::LLVMEvaluator::evalFP (VarBlock * varBlock) inline
Definition at line 355 of file Evaluator.h.
References unsupported().
Referenced by SeExpr2::Expression::evalFP().
void SeExpr2::LLVMEvaluator::evalMultiple (VarBlock * varBlock, int outputVarBlockOffset, size_t rangeStart, size_t rangeEnd) inline
Definition at line 357 of file Evaluator.h.
References unsupported().
Referenced by SeExpr2::Expression::evalMultiple().
const char* SeExpr2::LLVMEvaluator::evalStr (VarBlock * varBlock) inline
Definition at line 351 of file Evaluator.h.
References unsupported().
Referenced by SeExpr2::Expression::evalStr().
bool SeExpr2::LLVMEvaluator::prepLLVM (ExprNode * parseTree, ExprType desiredReturnType) inline
Definition at line 356 of file Evaluator.h.
References unsupported().
Referenced by SeExpr2::Expression::prep().
void SeExpr2::LLVMEvaluator::unsupported () inline
Definition at line 350 of file Evaluator.h.
Referenced by evalFP(), evalMultiple(), evalStr(), and prepLLVM().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/Evaluator.h