SeExpr: SeExpr::CurveFuncX Class Reference
SeExpr::CurveFuncX Class Reference
Public Member Functions
CurveFuncX ()
virtual ~CurveFuncX ()
Private Member Functions
virtual bool prep (SeExprFuncNode *node, bool)
virtual void eval (const SeExprFuncNode *node, SeVec3d &result) const
Detailed Description
Definition at line 1331 of file SeExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr::CurveFuncX::CurveFuncX () [inline]
Definition at line 1392 of file SeExprBuiltins.cpp.
virtual SeExpr::CurveFuncX::~CurveFuncX () [inline, virtual]
Definition at line 1393 of file SeExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr::CurveFuncX::eval (const SeExprFuncNode * node, SeVec3d & result) const [inline, private, virtual]
evaluate the expression. the given node is where in the parse tree the evaluation is for
Implements SeExprFuncX.
Definition at line 1375 of file SeExprBuiltins.cpp.
References SeExprNode::child(), SeExpr::CurveData< T >::curve, SeExprNode::eval(), SeExprFuncNode::getData(), and SeExprNode::isVec().
virtual bool SeExpr::CurveFuncX::prep (SeExprFuncNode * node, bool wantVec) [inline, private, virtual]
prep the expression by doing all type checking argument checking, etc.
Reimplemented from SeExprFuncX.
Definition at line 1333 of file SeExprBuiltins.cpp.
References SeExprNode::addError(), SeExprNode::child(), SeExpr::CurveData< T >::curve, SeExprNode::eval(), SeExprFuncNode::nargs(), SeExprNode::prep(), and SeExprFuncNode::setData().
The documentation for this class was generated from the following file:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprBuiltins.cpp