SeExpr: SeExprEdLineEdit Class Reference
SeExprEdLineEdit Class Reference
Line Editor Widget(used for numbers).
#include <SeExprEdControl.h>
Signals
void textChanged (int id, const QString &text)
Public Member Functions
SeExprEdLineEdit (int id, QWidget *parent)
virtual void setText (const QString &t)
Private Slots
void textChangedCB (const QString &text)
Private Attributes
int _id
bool _signaling
Detailed Description
Line Editor Widget(used for numbers).
Definition at line 91 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdLineEdit::SeExprEdLineEdit (int id, QWidget * parent)
Definition at line 54 of file SeExprEditor.cpp.
References textChanged(), and textChangedCB().
Member Function Documentation
virtual void SeExprEdLineEdit::setText (const QString & t) [inline, virtual]
Definition at line 96 of file SeExprEdControl.h.
References _signaling.
Referenced by SeExprEdNumberControl::updateControl().
void SeExprEdLineEdit::textChanged (int id, const QString & text) [signal]
Referenced by SeExprEdLineEdit(), and textChangedCB().
void SeExprEdLineEdit::textChangedCB (const QString & text) [private, slot]
Definition at line 61 of file SeExprEditor.cpp.
References _id, _signaling, and textChanged().
Referenced by SeExprEdLineEdit().
Member Data Documentation
int SeExprEdLineEdit::_id [private]
Definition at line 109 of file SeExprEdControl.h.
Referenced by textChangedCB().
bool SeExprEdLineEdit::_signaling [private]
Definition at line 110 of file SeExprEdControl.h.
Referenced by setText(), and textChangedCB().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEditor.cpp