SeExpr: StringControl Class Reference
StringControl Class Reference
A control for editing strings, filenames, and directories.
#include <ExprControl.h>
Public Member Functions
StringControl (int id, StringEditable *stringEditable)
Public Member Functions inherited from ExprControl
ExprControl (int id, Editable *editable, bool showColorLink)
virtual ~ExprControl ()
virtual QColor getColor ()
Interface for getting the color (used for linked color picking)
virtual void setColor (QColor color)
Interface for setting the color (used for linked color picking)
void linkDisconnect (int newId)
Private Slots
void textChanged (const QString &newText)
void fileBrowse ()
void directoryBrowse ()
Private Member Functions
void updateControl ()
Private Attributes
StringEditable * _stringEditable
model for the string control
QLineEdit * _edit
Edit box for the string.
Additional Inherited Members
Public Slots inherited from ExprControl
void linkStateChange (int state)
Signals inherited from ExprControl
void controlChanged (int id)
void linkColorEdited (int id, QColor color)
void linkColorLink (int id)
Protected Attributes inherited from ExprControl
int _id
bool _updating
QHBoxLayout * hbox
QCheckBox * _colorLinkCB
QLabel * _label
Editable * _editable
Detailed Description
A control for editing strings, filenames, and directories.
Definition at line 215 of file ExprControl.h.
Constructor & Destructor Documentation
StringControl::StringControl (int id, StringEditable * stringEditable)
Definition at line 497 of file ExprControl.cpp.
References _edit, _stringEditable, directoryBrowse(), directoryXPM, fileBrowse(), fileXPM, ExprControl::hbox, textChanged(), StringEditable::type, and updateControl().
Member Function Documentation
void StringControl::directoryBrowse () private slot
Definition at line 534 of file ExprControl.cpp.
References _edit, ExprFileDialog::getExistingDirectory(), and ExprFileDialog::setPreview().
Referenced by StringControl().
void StringControl::fileBrowse () private slot
Definition at line 526 of file ExprControl.cpp.
References _edit, ExprFileDialog::getOpenFileName(), and ExprFileDialog::setPreview().
Referenced by StringControl().
void StringControl::textChanged (const QString & newText) private slot
Definition at line 547 of file ExprControl.cpp.
References ExprControl::_id, _stringEditable, ExprControl::_updating, ExprControl::controlChanged(), and StringEditable::v.
Referenced by StringControl().
void StringControl::updateControl () private
Definition at line 542 of file ExprControl.cpp.
References _edit, _stringEditable, and StringEditable::v.
Referenced by StringControl().
Member Data Documentation
QLineEdit* StringControl::_edit private
Edit box for the string.
Definition at line 222 of file ExprControl.h.
Referenced by directoryBrowse(), fileBrowse(), StringControl(), and updateControl().
StringEditable* StringControl::_stringEditable private
model for the string control
Definition at line 220 of file ExprControl.h.
Referenced by StringControl(), textChanged(), and updateControl().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp