SeExpr: SeExprEdEditableExpression Class Reference
SeExprEdEditableExpression Class Reference
Factors a SeExpr into an editable expression with controls (i.e. value boxes, curve boxes).
#include <SeExprEdEditableExpression.h>
Public Member Functions
SeExprEdEditableExpression ()
~SeExprEdEditableExpression ()
void setExpr (const std::string &expr)
Set's expressions and parses it into "control editable form".
std::string getEditedExpr () const
Return a reconstructed expression using all the editable's current values.
bool controlsMatch (const SeExprEdEditableExpression &other) const
Check if the other editable expression has editables that all match i.e. the controls are same.
void updateString (const SeExprEdEditableExpression &other)
Update the string refered to into the controls (this is only valid if controlsmatch).
SeExprEdEditable * operator[] (const int i)
Access an editable parameter.
size_t size () const
Return the count of editable parameters.
const std::vector< std::string > & getVariables () const
Get list of commentsø.
Private Types
typedef std::vector
< SeExprEdEditable * > Editables
Private Member Functions
void cleanup ()
clean memeory
Private Attributes
std::string _expr
std::vector< SeExprEdEditable * > _editables
std::vector< std::string > _variables
Detailed Description
Factors a SeExpr into an editable expression with controls (i.e. value boxes, curve boxes).
Definition at line 22 of file SeExprEdEditableExpression.h.
Member Typedef Documentation
typedef std::vector<SeExprEdEditable*> SeExprEdEditableExpression::Editables [private]
Definition at line 24 of file SeExprEdEditableExpression.h.
Constructor & Destructor Documentation
SeExprEdEditableExpression::SeExprEdEditableExpression ()
Definition at line 18 of file SeExprEdEditableExpression.cpp.
SeExprEdEditableExpression::~SeExprEdEditableExpression ()
Definition at line 21 of file SeExprEdEditableExpression.cpp.
References cleanup().
Member Function Documentation
void SeExprEdEditableExpression::cleanup () [private]
clean memeory
Definition at line 61 of file SeExprEdEditableExpression.cpp.
References _editables, and _variables.
Referenced by setExpr(), and ~SeExprEdEditableExpression().
bool SeExprEdEditableExpression::controlsMatch (const SeExprEdEditableExpression & other) const
Check if the other editable expression has editables that all match i.e. the controls are same.
Definition at line 97 of file SeExprEdEditableExpression.cpp.
References _editables, and SeExprEdEditable::controlsMatch().
Referenced by SeExprEdControlCollection::rebuildControls().
std::string SeExprEdEditableExpression::getEditedExpr () const
Return a reconstructed expression using all the editable's current values.
Definition at line 69 of file SeExprEdEditableExpression.cpp.
References _editables, _expr, SeExprEdEditable::appendString(), SeExprEdEditable::endPos, and SeExprEdEditable::startPos.
Referenced by SeExprEdControlCollection::updateText().
const std::vector<std::string>& SeExprEdEditableExpression::getVariables () const [inline]
Get list of commentsø.
Definition at line 50 of file SeExprEdEditableExpression.h.
References _variables.
Referenced by SeExprEdControlCollection::rebuildControls().
SeExprEdEditable* SeExprEdEditableExpression::operator[] (const int i) [inline]
Access an editable parameter.
Definition at line 44 of file SeExprEdEditableExpression.h.
References _editables.
void SeExprEdEditableExpression::setExpr (const std::string & expr)
Set's expressions and parses it into "control editable form".
Definition at line 27 of file SeExprEdEditableExpression.cpp.
References _editables, _expr, _variables, cleanup(), SeExprEdEditable::endPos, SeExprEdEditable::parseComment(), and SeExprParse().
Referenced by SeExprEdControlCollection::rebuildControls().
size_t SeExprEdEditableExpression::size () const [inline]
Return the count of editable parameters.
Definition at line 47 of file SeExprEdEditableExpression.h.
References _editables.
Referenced by SeExprEdControlCollection::rebuildControls().
void SeExprEdEditableExpression::updateString (const SeExprEdEditableExpression & other)
Update the string refered to into the controls (this is only valid if controlsmatch).
Definition at line 83 of file SeExprEdEditableExpression.cpp.
References _editables, _expr, _variables, SeExprEdEditable::controlsMatch(), and SeExprEdEditable::updatePositions().
Referenced by SeExprEdControlCollection::rebuildControls().
Member Data Documentation
std::vector<SeExprEdEditable*> SeExprEdEditableExpression::_editables [private]
Definition at line 25 of file SeExprEdEditableExpression.h.
Referenced by cleanup(), controlsMatch(), getEditedExpr(), operator[](), setExpr(), size(), and updateString().
std::string SeExprEdEditableExpression::_expr [private]
Definition at line 23 of file SeExprEdEditableExpression.h.
Referenced by getEditedExpr(), setExpr(), and updateString().
std::vector<std::string> SeExprEdEditableExpression::_variables [private]
Definition at line 26 of file SeExprEdEditableExpression.h.
Referenced by cleanup(), getVariables(), setExpr(), and updateString().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdEditableExpression.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdEditableExpression.cpp