SeExpr: ExprBrowser Class Reference
ExprBrowser Class Reference
#include <ExprBrowser.h>
Public Slots
void handleSelection (const QModelIndex &current, const QModelIndex &previous)
void update ()
void clear ()
void clearSelection ()
void saveExpression ()
void saveLocalExpressionAs ()
void saveExpressionAs ()
Public Member Functions
ExprBrowser (QWidget *parent, ExprEditor *editor)
~ExprBrowser ()
void addPath (const std::string &name, const std::string &path)
std::string getSelectedPath ()
void selectPath (const char *path)
void addUserExpressionPath (const std::string &context)
bool getExpressionDirs ()
bool getExpressionDirs (const std::string &context)
void setSearchPath (const QString &context, const QString &path)
void expandAll ()
void expandToDepth (int depth)
void setApplyOnSelect (bool on)
Private Slots
void clearFilter ()
void filterChanged (const QString &str)
Private Attributes
ExprEditor * editor
QList< QString > labels
QList< QString > paths
ExprTreeModel * treeModel
ExprTreeFilterModel * proxyModel
QTreeView * treeNew
QLineEdit * exprFilter
std::string _userExprDir
std::string _localExprDir
std::string _context
std::string _searchPath
bool _applyOnSelect
Detailed Description
Definition at line 44 of file ExprBrowser.h.
Constructor & Destructor Documentation
ExprBrowser::ExprBrowser (QWidget * parent, ExprEditor * editor)
Definition at line 263 of file ExprBrowser.cpp.
References clearFilter(), exprFilter, filterChanged(), handleSelection(), proxyModel, treeModel, and treeNew.
ExprBrowser::~ExprBrowser ()
Definition at line 258 of file ExprBrowser.cpp.
References treeModel.
Member Function Documentation
void ExprBrowser::addPath (const std::string & name, const std::string & path)
Definition at line 297 of file ExprBrowser.cpp.
References ExprTreeModel::addPath(), labels, paths, and treeModel.
Referenced by addUserExpressionPath(), and getExpressionDirs().
void ExprBrowser::addUserExpressionPath (const std::string & context)
Definition at line 456 of file ExprBrowser.cpp.
References _userExprDir, and addPath().
Referenced by getExpressionDirs().
void ExprBrowser::clear () slot
Definition at line 348 of file ExprBrowser.cpp.
References ExprTreeModel::clear(), clearSelection(), labels, paths, and treeModel.
Referenced by getExpressionDirs().
void ExprBrowser::clearFilter () private slot
Definition at line 363 of file ExprBrowser.cpp.
References exprFilter.
Referenced by ExprBrowser().
void ExprBrowser::clearSelection () slot
Definition at line 358 of file ExprBrowser.cpp.
References treeNew.
Referenced by clear(), and ExprDialog::clearExpression().
void ExprBrowser::expandAll ()
Definition at line 445 of file ExprBrowser.cpp.
References treeNew.
Referenced by ExprDialog::exec(), ExprDialog::show(), and ExprShortEdit::showDetails().
void ExprBrowser::expandToDepth (int depth)
Definition at line 450 of file ExprBrowser.cpp.
References treeNew.
void ExprBrowser::filterChanged (const QString & str) private slot
Definition at line 368 of file ExprBrowser.cpp.
References proxyModel, and treeNew.
Referenced by ExprBrowser().
bool ExprBrowser::getExpressionDirs ()
Definition at line 473 of file ExprBrowser.cpp.
References _context, _localExprDir, _searchPath, addPath(), addUserExpressionPath(), clear(), context, P3D_CONFIG_ENVVAR, and update().
Referenced by ExprDialog::exec(), and ExprDialog::show().
bool ExprBrowser::getExpressionDirs (const std::string & context)
std::string ExprBrowser::getSelectedPath ()
Definition at line 310 of file ExprBrowser.cpp.
References ExprTreeItem::path, proxyModel, and treeNew.
Referenced by saveExpression().
void ExprBrowser::handleSelection (const QModelIndex & current, const QModelIndex & previous) slot
Definition at line 333 of file ExprBrowser.cpp.
References _applyOnSelect, editor, ExprTreeItem::path, proxyModel, and ExprEditor::setExpr().
Referenced by ExprBrowser().
void ExprBrowser::saveExpression () slot
Definition at line 426 of file ExprBrowser.cpp.
References editor, ExprEditor::getExpr(), getSelectedPath(), and saveExpressionAs().
void ExprBrowser::saveExpressionAs () slot
Definition at line 379 of file ExprBrowser.cpp.
References _userExprDir, editor, ExprEditor::getExpr(), selectPath(), and update().
Referenced by saveExpression().
void ExprBrowser::saveLocalExpressionAs () slot
Definition at line 402 of file ExprBrowser.cpp.
References _localExprDir, editor, ExprEditor::getExpr(), selectPath(), and update().
void ExprBrowser::selectPath (const char * path)
Definition at line 321 of file ExprBrowser.cpp.
References ExprTreeModel::find(), index(), proxyModel, treeModel, and treeNew.
Referenced by saveExpressionAs(), and saveLocalExpressionAs().
void ExprBrowser::setApplyOnSelect (bool on) inline
Definition at line 73 of file ExprBrowser.h.
References _applyOnSelect.
Referenced by ExprShortEdit::showDetails().
void ExprBrowser::setSearchPath (const QString & context, const QString & path)
Definition at line 304 of file ExprBrowser.cpp.
References _context, and _searchPath.
Referenced by ExprShortEdit::showDetails().
void ExprBrowser::update () slot
Definition at line 327 of file ExprBrowser.cpp.
References proxyModel, treeModel, ExprTreeModel::update(), and ExprTreeFilterModel::update().
Referenced by getExpressionDirs(), saveExpressionAs(), and saveLocalExpressionAs().
Member Data Documentation
bool ExprBrowser::_applyOnSelect private
Definition at line 59 of file ExprBrowser.h.
Referenced by handleSelection(), and setApplyOnSelect().
std::string ExprBrowser::_context private
Definition at line 57 of file ExprBrowser.h.
Referenced by getExpressionDirs(), and setSearchPath().
std::string ExprBrowser::_localExprDir private
Definition at line 56 of file ExprBrowser.h.
Referenced by getExpressionDirs(), and saveLocalExpressionAs().
std::string ExprBrowser::_searchPath private
Definition at line 58 of file ExprBrowser.h.
Referenced by getExpressionDirs(), and setSearchPath().
std::string ExprBrowser::_userExprDir private
Definition at line 55 of file ExprBrowser.h.
Referenced by addUserExpressionPath(), and saveExpressionAs().
ExprEditor* ExprBrowser::editor private
Definition at line 48 of file ExprBrowser.h.
Referenced by handleSelection(), saveExpression(), saveExpressionAs(), and saveLocalExpressionAs().
QLineEdit* ExprBrowser::exprFilter private
Definition at line 54 of file ExprBrowser.h.
Referenced by clearFilter(), and ExprBrowser().
QList<QString> ExprBrowser::labels private
Definition at line 49 of file ExprBrowser.h.
Referenced by addPath(), and clear().
QList<QString> ExprBrowser::paths private
Definition at line 50 of file ExprBrowser.h.
Referenced by addPath(), and clear().
ExprTreeFilterModel* ExprBrowser::proxyModel private
Definition at line 52 of file ExprBrowser.h.
Referenced by ExprBrowser(), filterChanged(), getSelectedPath(), handleSelection(), selectPath(), and update().
ExprTreeModel* ExprBrowser::treeModel private
Definition at line 51 of file ExprBrowser.h.
Referenced by addPath(), clear(), ExprBrowser(), selectPath(), update(), and ~ExprBrowser().
QTreeView* ExprBrowser::treeNew private
Definition at line 53 of file ExprBrowser.h.
Referenced by clearSelection(), expandAll(), expandToDepth(), ExprBrowser(), filterChanged(), getSelectedPath(), and selectPath().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprBrowser.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprBrowser.cpp