SeExpr: SeExpr2::GetVar Class Reference
SeExpr2::GetVar Class Reference
Classes
struct Assign
struct Data
Public Member Functions
GetVar ()
virtual ~GetVar ()
Public Member Functions inherited from SeExpr2::ExprFuncSimple
ExprFuncSimple (const bool threadSafe)
virtual int buildInterpreter (const ExprFuncNode *node, Interpreter *interpreter) const
Build an interpreter to evaluate the expression.
Public Member Functions inherited from SeExpr2::ExprFuncX
ExprFuncX (const bool threadSafe)
virtual ExprType type () const
virtual ~ExprFuncX ()
bool isThreadSafe () const
virtual size_t sizeInBytes () const
Return memory usage of a funcX in bytes.
virtual void statistics (Statistics &) const
Give this function a chance to populate its statistics.
Private Member Functions
virtual ExprType prep (ExprFuncNode *node, bool wantScalar, ExprVarEnvBuilder &envBuilder) const
virtual ExprFuncNode::Data * evalConstant (const ExprFuncNode *node, ArgHandle args) const
virtual void eval (ArgHandle args)
Additional Inherited Members
Protected Attributes inherited from SeExpr2::ExprFuncX
bool _isScalar
ExprType _type
Detailed Description
Definition at line 1404 of file ExprBuiltins.cpp.
Constructor & Destructor Documentation
SeExpr2::GetVar::GetVar () inline
Definition at line 1454 of file ExprBuiltins.cpp.
virtual SeExpr2::GetVar::~GetVar () inline virtual
Definition at line 1455 of file ExprBuiltins.cpp.
Member Function Documentation
virtual void SeExpr2::GetVar::eval (ArgHandle args) inline private virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 1443 of file ExprBuiltins.cpp.
References SeExpr2::ExprFuncSimple::ArgHandle::data, SeExpr2::GetVar::Data::f, SeExpr2::ExprFuncSimple::ArgHandle::inFp(), and SeExpr2::ExprFuncSimple::ArgHandle::outFp.
virtual ExprFuncNode::Data* SeExpr2::GetVar::evalConstant (const ExprFuncNode * node, ArgHandle args) const inline private virtual
Implements SeExpr2::ExprFuncSimple.
Definition at line 1432 of file ExprBuiltins.cpp.
References SeExpr2::ExprType::dim(), SeExpr2::ExprType::isFP(), and SeExpr2::ExprNode::type().
virtual ExprType SeExpr2::GetVar::prep (ExprFuncNode * node, bool scalarWanted, ExprVarEnvBuilder & env) const inline private virtual
prep the expression by doing all type checking argument checking, etc.
Implements SeExpr2::ExprFuncSimple.
Definition at line 1413 of file ExprBuiltins.cpp.
References SeExpr2::ExprNode::addChild(), SeExpr2::ExprFuncNode::checkArg(), SeExpr2::ExprNode::child(), SeExpr2::ExprType::Error(), SeExpr2::ExprNode::expr(), SeExpr2::ExprFuncNode::getStrArg(), SeExpr2::ExprNode::prep(), SeExpr2::ExprVarNode::prep(), SeExpr2::ExprNode::removeLastChild(), and SeExpr2::ExprNode::swapChildren().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprBuiltins.cpp