SeExpr: SeExprMulNode Class Reference
SeExprMulNode Class Reference
Node that implements an arithmetic operator.
#include <SeExprNode.h>
Public Member Functions
SeExprMulNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that implements an arithmetic operator.
Definition at line 361 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprMulNode::SeExprMulNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 364 of file SeExprNode.h.
Member Function Documentation
void SeExprMulNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 581 of file SeExprNode.cpp.
References SeExprNode::_isVec, a, b, SeExprNode::child(), SeExprNode::eval(), and SeExprNode::isVec().
The documentation for this class was generated from the following files:
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.h
/jobs2/soft/users/aselle/src/seexpr-to-push/src/SeExpr/SeExprNode.cpp