SeExpr: ExprDeepWater Class Reference
ExprDeepWater Class Reference
#include <ExprDeepWater.h>
Public Slots
void resolutionChanged ()
void tileSizeChanged ()
void lengthCutoffChanged ()
void amplitudeChanged ()
void windAngleChanged ()
void windSpeedChanged ()
void flowDirectionChanged ()
void directionalFactorExponentChanged ()
void directionalReflectionDampingChanged ()
void sharpenChanged ()
Signals
void resolutionChangedSignal (int val)
void tileSizeChangedSignal (double val)
void lengthCutoffChangedSignal (double val)
void amplitudeChangedSignal (double val)
void windAngleChangedSignal (double val)
void windSpeedChangedSignal (double val)
void flowDirectionChangedSignal (QString val)
void directionalFactorExponentChangedSignal (double val)
void directionalReflectionDampingChangedSignal (double val)
void sharpenChangedSignal (double val)
Public Member Functions
ExprDeepWater (QWidget *parent=0)
~ExprDeepWater ()
void setParams (const SeDeepWaterParams &params)
Public Attributes
DeepWaterScene * _scene
Private Attributes
DeepWaterLineEdit * _resolutionEdit
DeepWaterLineEdit * _tileSizeEdit
DeepWaterLineEdit * _lengthCutoffEdit
DeepWaterLineEdit * _amplitudeEdit
DeepWaterLineEdit * _windAngleEdit
DeepWaterLineEdit * _windSpeedEdit
DeepWaterLineEdit * _flowDirectionEdit
DeepWaterLineEdit * _directionalFactorExponentEdit
DeepWaterLineEdit * _directionalReflectionDampingEdit
DeepWaterLineEdit * _sharpenEdit
Detailed Description
Definition at line 250 of file ExprDeepWater.h.
Constructor & Destructor Documentation
ExprDeepWater::ExprDeepWater (QWidget * parent = 0)
Definition at line 189 of file ExprDeepWater.cpp.
References _amplitudeEdit, _directionalFactorExponentEdit, _directionalReflectionDampingEdit, _flowDirectionEdit, _lengthCutoffEdit, _resolutionEdit, _scene, _sharpenEdit, _tileSizeEdit, _windAngleEdit, _windSpeedEdit, amplitudeChanged(), amplitudeChangedSignal(), directionalFactorExponentChanged(), directionalFactorExponentChangedSignal(), directionalReflectionDampingChanged(), directionalReflectionDampingChangedSignal(), flowDirectionChanged(), flowDirectionChangedSignal(), lengthCutoffChanged(), lengthCutoffChangedSignal(), resolutionChanged(), resolutionChangedSignal(), sharpenChanged(), sharpenChangedSignal(), tileSizeChanged(), tileSizeChangedSignal(), windAngleChanged(), windAngleChangedSignal(), windSpeedChanged(), and windSpeedChangedSignal().
ExprDeepWater::~ExprDeepWater () inline
Definition at line 255 of file ExprDeepWater.h.
Member Function Documentation
void ExprDeepWater::amplitudeChanged () slot
Definition at line 442 of file ExprDeepWater.cpp.
References _amplitudeEdit, and amplitudeChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::amplitudeChangedSignal (double val) signal
Referenced by amplitudeChanged(), and ExprDeepWater().
void ExprDeepWater::directionalFactorExponentChanged () slot
Definition at line 465 of file ExprDeepWater.cpp.
References _directionalFactorExponentEdit, and directionalFactorExponentChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::directionalFactorExponentChangedSignal (double val) signal
Referenced by directionalFactorExponentChanged(), and ExprDeepWater().
void ExprDeepWater::directionalReflectionDampingChanged () slot
Definition at line 471 of file ExprDeepWater.cpp.
References _directionalReflectionDampingEdit, and directionalReflectionDampingChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::directionalReflectionDampingChangedSignal (double val) signal
Referenced by directionalReflectionDampingChanged(), and ExprDeepWater().
void ExprDeepWater::flowDirectionChanged () slot
Definition at line 460 of file ExprDeepWater.cpp.
References _flowDirectionEdit, and flowDirectionChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::flowDirectionChangedSignal (QString val) signal
Referenced by ExprDeepWater(), and flowDirectionChanged().
void ExprDeepWater::lengthCutoffChanged () slot
Definition at line 436 of file ExprDeepWater.cpp.
References _lengthCutoffEdit, and lengthCutoffChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::lengthCutoffChangedSignal (double val) signal
Referenced by ExprDeepWater(), and lengthCutoffChanged().
void ExprDeepWater::resolutionChanged () slot
Definition at line 424 of file ExprDeepWater.cpp.
References _resolutionEdit, and resolutionChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::resolutionChangedSignal (int val) signal
Referenced by ExprDeepWater(), and resolutionChanged().
void ExprDeepWater::setParams (const SeDeepWaterParams & params)
Definition at line 483 of file ExprDeepWater.cpp.
References _amplitudeEdit, _directionalFactorExponentEdit, _directionalReflectionDampingEdit, _flowDirectionEdit, _lengthCutoffEdit, _resolutionEdit, _scene, _sharpenEdit, _tileSizeEdit, _windAngleEdit, _windSpeedEdit, SeDeepWaterParams::amplitude, SeDeepWaterParams::directionalFactorExponent, SeDeepWaterParams::directionalReflectionDamping, SeDeepWaterParams::flowDirection, SeDeepWaterParams::lengthCutoff, SeDeepWaterParams::resolution, DeepWaterScene::setParams(), SeDeepWaterParams::sharpen, SeDeepWaterParams::tileSize, SeDeepWaterParams::windAngle, and SeDeepWaterParams::windSpeed.
Referenced by DeepWaterControl::DeepWaterControl().
void ExprDeepWater::sharpenChanged () slot
Definition at line 477 of file ExprDeepWater.cpp.
References _sharpenEdit, and sharpenChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::sharpenChangedSignal (double val) signal
Referenced by ExprDeepWater(), and sharpenChanged().
void ExprDeepWater::tileSizeChanged () slot
Definition at line 430 of file ExprDeepWater.cpp.
References _tileSizeEdit, and tileSizeChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::tileSizeChangedSignal (double val) signal
Referenced by ExprDeepWater(), and tileSizeChanged().
void ExprDeepWater::windAngleChanged () slot
Definition at line 448 of file ExprDeepWater.cpp.
References _windAngleEdit, and windAngleChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::windAngleChangedSignal (double val) signal
Referenced by ExprDeepWater(), and windAngleChanged().
void ExprDeepWater::windSpeedChanged () slot
Definition at line 454 of file ExprDeepWater.cpp.
References _windSpeedEdit, and windSpeedChangedSignal().
Referenced by ExprDeepWater().
void ExprDeepWater::windSpeedChangedSignal (double val) signal
Referenced by ExprDeepWater(), and windSpeedChanged().
Member Data Documentation
DeepWaterLineEdit* ExprDeepWater::_amplitudeEdit private
Definition at line 288 of file ExprDeepWater.h.
Referenced by amplitudeChanged(), ExprDeepWater(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_directionalFactorExponentEdit private
Definition at line 292 of file ExprDeepWater.h.
Referenced by directionalFactorExponentChanged(), ExprDeepWater(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_directionalReflectionDampingEdit private
Definition at line 293 of file ExprDeepWater.h.
Referenced by directionalReflectionDampingChanged(), ExprDeepWater(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_flowDirectionEdit private
Definition at line 291 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), flowDirectionChanged(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_lengthCutoffEdit private
Definition at line 287 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), lengthCutoffChanged(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_resolutionEdit private
Definition at line 285 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), resolutionChanged(), and setParams().
DeepWaterScene* ExprDeepWater::_scene
Definition at line 258 of file ExprDeepWater.h.
Referenced by DeepWaterControl::deepWaterChanged(), DeepWaterControl::DeepWaterControl(), ExprDeepWater(), and setParams().
DeepWaterLineEdit* ExprDeepWater::_sharpenEdit private
Definition at line 294 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), setParams(), and sharpenChanged().
DeepWaterLineEdit* ExprDeepWater::_tileSizeEdit private
Definition at line 286 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), setParams(), and tileSizeChanged().
DeepWaterLineEdit* ExprDeepWater::_windAngleEdit private
Definition at line 289 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), setParams(), and windAngleChanged().
DeepWaterLineEdit* ExprDeepWater::_windSpeedEdit private
Definition at line 290 of file ExprDeepWater.h.
Referenced by ExprDeepWater(), setParams(), and windSpeedChanged().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDeepWater.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDeepWater.cpp