SeExpr: SeExpr2::Expressions Class Reference
SeExpr2::Expressions Class Reference
#include <ExprMultiExpr.h>
Public Member Functions
Expressions ()
~Expressions ()
VariableHandle addExternalVariable (const std::string &variableName, ExprType seTy)
ExprHandle addExpression (const std::string &varName, ExprType seTy, const std::string &expr)
VariableSetHandle getLoopVarSetHandle (VariableHandle vh)
void setLoopVariable (VariableSetHandle handle, double *values, unsigned dim)
void setLoopVariable (VariableSetHandle handle, double value)
void setLoopVariable (VariableSetHandle handle, const char *values)
void setVariable (VariableHandle handle, double *values, unsigned dim)
void setVariable (VariableHandle handle, double value)
void setVariable (VariableHandle handle, const char *values)
bool isValid () const
void getErrors (std::vector< std::string > &errors) const
ExprEvalHandle getExprEvalHandle (ExprHandle eh)
const std::vector< double > & evalFP (ExprEvalHandle eeh)
const char * evalStr (ExprEvalHandle eeh)
void resetEval ()
void reset ()
Public Attributes
std::set< DExpression * > AllExprs
std::set< GlobalVal * > AllExternalVars
Private Attributes
std::set< DExpression * > exprToEval
std::set< DExpression * > exprEvaled
Detailed Description
Definition at line 49 of file ExprMultiExpr.h.
Constructor & Destructor Documentation
SeExpr2::Expressions::Expressions () inline
Definition at line 58 of file ExprMultiExpr.h.
SeExpr2::Expressions::~Expressions ()
Definition at line 145 of file ExprMultiExpr.cpp.
References AllExprs, and AllExternalVars.
Member Function Documentation
ExprHandle SeExpr2::Expressions::addExpression (const std::string & varName, ExprType seTy, const std::string & expr)
Definition at line 164 of file ExprMultiExpr.cpp.
References AllExprs.
VariableHandle SeExpr2::Expressions::addExternalVariable (const std::string & variableName, ExprType seTy)
Definition at line 151 of file ExprMultiExpr.cpp.
References AllExternalVars, SeExpr2::ExprType::dim(), SeExpr2::ExprType::isFP(), and SeExpr2::ExprType::isString().
const std::vector< double > & SeExpr2::Expressions::evalFP (ExprEvalHandle eeh)
Definition at line 251 of file ExprMultiExpr.cpp.
References SeExpr2::GlobalFP::val.
const char * SeExpr2::Expressions::evalStr (ExprEvalHandle eeh)
Definition at line 263 of file ExprMultiExpr.cpp.
References SeExpr2::GlobalStr::val.
void SeExpr2::Expressions::getErrors (std::vector< std::string > & errors) const
ExprEvalHandle SeExpr2::Expressions::getExprEvalHandle (ExprHandle eh)
Definition at line 228 of file ExprMultiExpr.cpp.
References exprEvaled, exprToEval, and it.
VariableSetHandle SeExpr2::Expressions::getLoopVarSetHandle (VariableHandle vh)
Definition at line 170 of file ExprMultiExpr.cpp.
References AllExternalVars, exprToEval, and SeExpr2::GlobalVal::users.
bool SeExpr2::Expressions::isValid () const
Definition at line 221 of file ExprMultiExpr.cpp.
References AllExprs.
void SeExpr2::Expressions::reset () inline
Definition at line 86 of file ExprMultiExpr.h.
References AllExprs, AllExternalVars, and resetEval().
void SeExpr2::Expressions::resetEval () inline
Definition at line 81 of file ExprMultiExpr.h.
References exprEvaled, and exprToEval.
Referenced by reset().
void SeExpr2::Expressions::setLoopVariable (VariableSetHandle handle, double * values, unsigned dim)
Definition at line 181 of file ExprMultiExpr.cpp.
References AllExternalVars, and SeExpr2::GlobalFP::val.
void SeExpr2::Expressions::setLoopVariable (VariableSetHandle handle, double value) inline
Definition at line 66 of file ExprMultiExpr.h.
References setLoopVariable().
Referenced by setLoopVariable().
void SeExpr2::Expressions::setLoopVariable (VariableSetHandle handle, const char * values)
Definition at line 191 of file ExprMultiExpr.cpp.
References AllExternalVars, and SeExpr2::GlobalStr::val.
void SeExpr2::Expressions::setVariable (VariableHandle handle, double * values, unsigned dim)
Definition at line 199 of file ExprMultiExpr.cpp.
References SeExpr2::GlobalFP::val.
void SeExpr2::Expressions::setVariable (VariableHandle handle, double value) inline
Definition at line 70 of file ExprMultiExpr.h.
References setVariable().
Referenced by setVariable().
void SeExpr2::Expressions::setVariable (VariableHandle handle, const char * values)
Definition at line 211 of file ExprMultiExpr.cpp.
References SeExpr2::GlobalStr::val.
Member Data Documentation
std::set<DExpression*> SeExpr2::Expressions::AllExprs
Definition at line 54 of file ExprMultiExpr.h.
Referenced by addExpression(), SeExpr2::DExpression::DExpression(), isValid(), reset(), and ~Expressions().
std::set<GlobalVal*> SeExpr2::Expressions::AllExternalVars
Definition at line 55 of file ExprMultiExpr.h.
Referenced by addExternalVariable(), SeExpr2::DExpression::DExpression(), getLoopVarSetHandle(), reset(), setLoopVariable(), and ~Expressions().
std::set<DExpression*> SeExpr2::Expressions::exprEvaled private
Definition at line 51 of file ExprMultiExpr.h.
Referenced by getExprEvalHandle(), and resetEval().
std::set<DExpression*> SeExpr2::Expressions::exprToEval private
Definition at line 50 of file ExprMultiExpr.h.
Referenced by getExprEvalHandle(), getLoopVarSetHandle(), and resetEval().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprMultiExpr.h
/disney/home/jberlin/projects/SeExpr.github/src/SeExpr/ExprMultiExpr.cpp