SeExpr: ExprTreeModel Class Reference
ExprTreeModel Class Reference
Public Member Functions
ExprTreeModel ()
~ExprTreeModel ()
void update ()
void clear ()
void addPath (const char *label, const char *path)
QModelIndex parent (const QModelIndex &index) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
QModelIndex find (QString path)
Private Attributes
ExprTreeItem * root
Detailed Description
Definition at line 140 of file ExprBrowser.cpp.
Constructor & Destructor Documentation
ExprTreeModel::ExprTreeModel () inline
Definition at line 144 of file ExprBrowser.cpp.
ExprTreeModel::~ExprTreeModel () inline
Definition at line 148 of file ExprBrowser.cpp.
References root.
Member Function Documentation
void ExprTreeModel::addPath (const char * label, const char * path) inline
Definition at line 164 of file ExprBrowser.cpp.
References ExprTreeItem::addChild(), and root.
Referenced by ExprBrowser::addPath().
void ExprTreeModel::clear () inline
Definition at line 158 of file ExprBrowser.cpp.
References ExprTreeItem::clear(), root, and update().
Referenced by ExprBrowser::clear().
int ExprTreeModel::columnCount (const QModelIndex & parent) const inline
Definition at line 189 of file ExprBrowser.cpp.
QVariant ExprTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const inline
Definition at line 202 of file ExprBrowser.cpp.
References ExprTreeItem::label.
QModelIndex ExprTreeModel::find (QString path) inline
Definition at line 211 of file ExprBrowser.cpp.
References ExprTreeItem::find(), ExprTreeItem::regen(), root, and ExprTreeItem::row.
Referenced by ExprBrowser::selectPath().
QModelIndex ExprTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const inline
Definition at line 178 of file ExprBrowser.cpp.
References ExprTreeItem::getChild(), parent(), and root.
QModelIndex ExprTreeModel::parent (const QModelIndex & index) const inline
Definition at line 169 of file ExprBrowser.cpp.
References ExprTreeItem::parent, root, and ExprTreeItem::row.
Referenced by index(), and rowCount().
int ExprTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const inline
Definition at line 192 of file ExprBrowser.cpp.
References ExprTreeItem::getChildCount(), parent(), and root.
void ExprTreeModel::update () inline
Definition at line 153 of file ExprBrowser.cpp.
Referenced by clear(), and ExprBrowser::update().
Member Data Documentation
ExprTreeItem* ExprTreeModel::root private
Definition at line 142 of file ExprBrowser.cpp.
Referenced by addPath(), clear(), find(), index(), parent(), rowCount(), and ~ExprTreeModel().
The documentation for this class was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprBrowser.cpp