SeExpr: SeExprEdNumberControl Class Reference
SeExprEdNumberControl Class Reference
Number slider for either float or int data.
#include <SeExprEdControl.h>
Public Member Functions
SeExprEdNumberControl (int id, SeExprEdNumberEditable *number)
Private Slots
void sliderChanged (int val)
void editChanged (int id, const QString &text)
Private Member Functions
void setValue (float value)
Update the model with the value and notify the collection.
void updateControl ()
Update values in slider and textbox given what the model contains.
Private Attributes
SeExprEdNumberEditable * _numberEditable
Pointer to the number control model.
SeExprEdSlider * _slider
Slider for the number.
SeExprEdLineEdit * _edit
Text box for the number.
Detailed Description
Number slider for either float or int data.
Definition at line 154 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdNumberControl::SeExprEdNumberControl (int id, SeExprEdNumberEditable * number)
Definition at line 313 of file SeExprEdControl.cpp.
References _edit, _numberEditable, _slider, editChanged(), SeExprEdControl::hbox, SeExprEdNumberEditable::isInt, SeExpr::max(), SeExprEdNumberEditable::max, SeExprEdNumberEditable::min, sliderChanged(), and updateControl().
Member Function Documentation
void SeExprEdNumberControl::editChanged (int id, const QString & text) [private, slot]
Definition at line 348 of file SeExprEdControl.cpp.
References SeExprEdControl::_updating, and setValue().
Referenced by SeExprEdNumberControl().
void SeExprEdNumberControl::setValue (float value) [private]
Update the model with the value and notify the collection.
Definition at line 368 of file SeExprEdControl.cpp.
References SeExprEdControl::_id, _numberEditable, SeExprEdControl::controlChanged(), updateControl(), and SeExprEdNumberEditable::v.
Referenced by editChanged(), and sliderChanged().
void SeExprEdNumberControl::sliderChanged (int val) [private, slot]
Definition at line 341 of file SeExprEdControl.cpp.
References _numberEditable, SeExprEdControl::_updating, SeExprEdNumberEditable::isInt, and setValue().
Referenced by SeExprEdNumberControl().
void SeExprEdNumberControl::updateControl () [private]
Update values in slider and textbox given what the model contains.
Definition at line 358 of file SeExprEdControl.cpp.
References _edit, _numberEditable, _slider, SeExprEdControl::_updating, SeExprEdNumberEditable::isInt, SeExprEdLineEdit::setText(), and SeExprEdNumberEditable::v.
Referenced by SeExprEdNumberControl(), and setValue().
Member Data Documentation
SeExprEdLineEdit* SeExprEdNumberControl::_edit [private]
Text box for the number.
Definition at line 163 of file SeExprEdControl.h.
Referenced by SeExprEdNumberControl(), and updateControl().
SeExprEdNumberEditable* SeExprEdNumberControl::_numberEditable [private]
Pointer to the number control model.
Definition at line 159 of file SeExprEdControl.h.
Referenced by SeExprEdNumberControl(), setValue(), sliderChanged(), and updateControl().
SeExprEdSlider* SeExprEdNumberControl::_slider [private]
Slider for the number.
Definition at line 161 of file SeExprEdControl.h.
Referenced by SeExprEdNumberControl(), and updateControl().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp