SeExpr: ExprLineEdit Class Reference
ExprLineEdit Class Reference
Line Editor Widget(used for numbers)
#include <ExprControl.h>
Signals
void textChanged (int id, const QString &text)
Public Member Functions
ExprLineEdit (int id, QWidget *parent)
virtual void setText (const QString &t)
Private Slots
void textChangedCB (const QString &text)
Private Attributes
int _id
bool _signaling
Detailed Description
Line Editor Widget(used for numbers)
Definition at line 101 of file ExprControl.h.
Constructor & Destructor Documentation
ExprLineEdit::ExprLineEdit (int id, QWidget * parent)
Definition at line 61 of file ExprEditor.cpp.
References textChanged(), and textChangedCB().
Member Function Documentation
virtual void ExprLineEdit::setText (const QString & t) inline virtual
Definition at line 106 of file ExprControl.h.
References _signaling.
Referenced by NumberControl::updateControl().
void ExprLineEdit::textChanged (int id, const QString & text) signal
Referenced by ExprLineEdit(), and textChangedCB().
void ExprLineEdit::textChangedCB (const QString & text) private slot
Definition at line 68 of file ExprEditor.cpp.
References _id, _signaling, and textChanged().
Referenced by ExprLineEdit().
Member Data Documentation
int ExprLineEdit::_id private
Definition at line 119 of file ExprControl.h.
Referenced by textChangedCB().
bool ExprLineEdit::_signaling private
Definition at line 120 of file ExprControl.h.
Referenced by setText(), and textChangedCB().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprEditor.cpp