SeExpr: ExprControl Class Reference
ExprControl Class Reference
Base class for all controls for Expressions.
#include <ExprControl.h>
Public Slots
void linkStateChange (int state)
Signals
void controlChanged (int id)
void linkColorEdited (int id, QColor color)
void linkColorLink (int id)
Public Member Functions
ExprControl (int id, Editable *editable, bool showColorLink)
virtual ~ExprControl ()
virtual QColor getColor ()
Interface for getting the color (used for linked color picking)
virtual void setColor (QColor color)
Interface for setting the color (used for linked color picking)
void linkDisconnect (int newId)
Protected Attributes
int _id
bool _updating
QHBoxLayout * hbox
QCheckBox * _colorLinkCB
QLabel * _label
Editable * _editable
Detailed Description
Base class for all controls for Expressions.
Definition at line 53 of file ExprControl.h.
Constructor & Destructor Documentation
ExprControl::ExprControl (int id, Editable * editable, bool showColorLink)
Definition at line 263 of file ExprControl.cpp.
References _colorLinkCB, _label, hbox, linkStateChange(), and Editable::name.
virtual ExprControl::~ExprControl () inline virtual
Definition at line 68 of file ExprControl.h.
Member Function Documentation
void ExprControl::controlChanged (int id) signal
Referenced by ColorSwatchControl::colorAdded(), ColorSwatchControl::colorChanged(), ColorSwatchControl::colorRemoved(), CurveControl::curveChanged(), CCurveControl::curveChanged(), DeepWaterControl::deepWaterChanged(), AnimCurveControl::editGraphClicked(), AnimCurveControl::refreshClicked(), NumberControl::setValue(), VectorControl::setValue(), and StringControl::textChanged().
virtual QColor ExprControl::getColor () inline virtual
Interface for getting the color (used for linked color picking)
Reimplemented in CCurveControl, and VectorControl.
Definition at line 71 of file ExprControl.h.
Referenced by linkStateChange().
void ExprControl::linkColorEdited (int id, QColor color) signal
Referenced by linkStateChange(), and VectorControl::sliderChanged().
void ExprControl::linkColorLink (int id) signal
Referenced by linkStateChange().
void ExprControl::linkDisconnect (int newId)
Definition at line 305 of file ExprControl.cpp.
References _colorLinkCB, _id, and _updating.
void ExprControl::linkStateChange (int state) slot
Definition at line 293 of file ExprControl.cpp.
References _id, _updating, getColor(), linkColorEdited(), and linkColorLink().
Referenced by ExprControl().
virtual void ExprControl::setColor (QColor color) inline virtual
Interface for setting the color (used for linked color picking)
Reimplemented in CCurveControl, and VectorControl.
Definition at line 73 of file ExprControl.h.
Member Data Documentation
QCheckBox* ExprControl::_colorLinkCB protected
Definition at line 61 of file ExprControl.h.
Referenced by ExprControl(), and linkDisconnect().
Editable* ExprControl::_editable protected
Definition at line 64 of file ExprControl.h.
int ExprControl::_id protected
Definition at line 55 of file ExprControl.h.
Referenced by ColorSwatchControl::colorAdded(), ColorSwatchControl::colorChanged(), ColorSwatchControl::colorRemoved(), CurveControl::curveChanged(), CCurveControl::curveChanged(), DeepWaterControl::deepWaterChanged(), AnimCurveControl::editGraphClicked(), linkDisconnect(), linkStateChange(), AnimCurveControl::refreshClicked(), NumberControl::setValue(), VectorControl::setValue(), VectorControl::sliderChanged(), and StringControl::textChanged().
QLabel* ExprControl::_label protected
Definition at line 62 of file ExprControl.h.
Referenced by ExprControl(), and VectorControl::updateControl().
bool ExprControl::_updating protected
Definition at line 59 of file ExprControl.h.
Referenced by ColorSwatchControl::buildSwatchWidget(), ColorSwatchControl::colorAdded(), ColorSwatchControl::colorChanged(), ColorSwatchControl::colorRemoved(), NumberControl::editChanged(), VectorControl::editChanged(), linkDisconnect(), linkStateChange(), NumberControl::sliderChanged(), VectorControl::sliderChanged(), StringControl::textChanged(), NumberControl::updateControl(), and VectorControl::updateControl().
QHBoxLayout* ExprControl::hbox protected
Definition at line 60 of file ExprControl.h.
Referenced by AnimCurveControl::AnimCurveControl(), ColorSwatchControl::buildSwatchWidget(), CCurveControl::CCurveControl(), CurveControl::CurveControl(), DeepWaterControl::DeepWaterControl(), ExprControl(), NumberControl::NumberControl(), StringControl::StringControl(), and VectorControl::VectorControl().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprControl.cpp