SeExpr: ExprGrapherView Class Reference
ExprGrapherView Class Reference
#include <ExprGrapher2d.h>
Signals
void scaleValueManipulated ()
void clicked ()
Public Member Functions
ExprGrapherView (ExprGrapherWidget &widget, QWidget *parent, int width, int height)
virtual ~ExprGrapherView ()
void update ()
void setWindow (float xmin, float xmax, float ymin, float ymax, float z)
void getWindow (float &xmin, float &xmax, float &ymin, float &ymax, float &z)
Protected Member Functions
void clear ()
void paintGL ()
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
Protected Attributes
int event_oldx
int event_oldy
Private Attributes
ExprGrapherWidget & widget
float * _image
int _width
int _height
float xmin
float xmax
float ymin
float ymax
float z
float dx
float dy
bool scaling
bool translating
Detailed Description
Definition at line 34 of file ExprGrapher2d.h.
Constructor & Destructor Documentation
ExprGrapherView::ExprGrapherView (ExprGrapherWidget & widget, QWidget * parent, int width, int height)
Definition at line 98 of file ExprGrapher2d.cpp.
References _height, _image, _width, clear(), and setWindow().
ExprGrapherView::~ExprGrapherView () virtual
Definition at line 112 of file ExprGrapher2d.cpp.
References _image.
Member Function Documentation
void ExprGrapherView::clear () protected
Definition at line 138 of file ExprGrapher2d.cpp.
References _height, _image, _width, and index().
Referenced by ExprGrapherView(), and update().
void ExprGrapherView::clicked () signal
Referenced by mouseReleaseEvent().
void ExprGrapherView::getWindow (float & xmin, float & xmax, float & ymin, float & ymax, float & z)
Definition at line 129 of file ExprGrapher2d.cpp.
References xmax, xmin, ymax, ymin, and z.
Referenced by ExprGrapherWidget::ExprGrapherWidget(), ExprGrapherWidget::scaleValueEdited(), and ExprGrapherWidget::scaleValueManipulated().
void ExprGrapherView::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 171 of file ExprGrapher2d.cpp.
References dx, dy, event_oldx, event_oldy, f(), pow(), scaleValueManipulated(), scaling, setWindow(), translating, update(), x, xmax, xmin, y, ymax, ymin, and z.
void ExprGrapherView::mousePressEvent (QMouseEvent * event) protected
Definition at line 150 of file ExprGrapher2d.cpp.
References event_oldx, event_oldy, scaling, and translating.
void ExprGrapherView::mouseReleaseEvent (QMouseEvent * event) protected
Definition at line 164 of file ExprGrapher2d.cpp.
References clicked(), scaling, and translating.
void ExprGrapherView::paintGL () protected
Definition at line 237 of file ExprGrapher2d.cpp.
References _height, _image, _width, and f().
void ExprGrapherView::scaleValueManipulated () signal
Referenced by mouseMoveEvent().
void ExprGrapherView::setWindow (float xmin, float xmax, float ymin, float ymax, float z)
Definition at line 117 of file ExprGrapher2d.cpp.
References _height, _width, dx, dy, xmax, xmin, ymax, ymin, and z.
Referenced by ExprGrapherView(), mouseMoveEvent(), and ExprGrapherWidget::scaleValueEdited().
void ExprGrapherView::update ()
Definition at line 203 of file ExprGrapher2d.cpp.
References _height, _image, _width, clear(), dx, dy, SeExpr2::Expression::evalFP(), ExprGrapherWidget::expr, index(), SeExpr2::Expression::isValid(), BasicExpression::P, BasicExpression::u, BasicExpression::v, BasicExpression::ScalarRef::value, BasicExpression::VectorRef::value, value(), widget, x, xmin, y, ymin, and z.
Referenced by mouseMoveEvent(), and ExprGrapherWidget::update().
Member Data Documentation
int ExprGrapherView::_height private
Definition at line 61 of file ExprGrapher2d.h.
Referenced by clear(), ExprGrapherView(), paintGL(), setWindow(), and update().
float* ExprGrapherView::_image private
Definition at line 59 of file ExprGrapher2d.h.
Referenced by clear(), ExprGrapherView(), paintGL(), update(), and ~ExprGrapherView().
int ExprGrapherView::_width private
Definition at line 60 of file ExprGrapher2d.h.
Referenced by clear(), ExprGrapherView(), paintGL(), setWindow(), and update().
float ExprGrapherView::dx private
Definition at line 64 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), setWindow(), and update().
float ExprGrapherView::dy private
Definition at line 64 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), setWindow(), and update().
int ExprGrapherView::event_oldx protected
Definition at line 52 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
int ExprGrapherView::event_oldy protected
Definition at line 52 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
bool ExprGrapherView::scaling private
Definition at line 67 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
bool ExprGrapherView::translating private
Definition at line 67 of file ExprGrapher2d.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
ExprGrapherWidget& ExprGrapherView::widget private
Definition at line 36 of file ExprGrapher2d.h.
Referenced by update().
float ExprGrapherView::xmax private
Definition at line 63 of file ExprGrapher2d.h.
Referenced by getWindow(), mouseMoveEvent(), and setWindow().
float ExprGrapherView::xmin private
Definition at line 63 of file ExprGrapher2d.h.
Referenced by getWindow(), mouseMoveEvent(), setWindow(), and update().
float ExprGrapherView::ymax private
Definition at line 63 of file ExprGrapher2d.h.
Referenced by getWindow(), mouseMoveEvent(), and setWindow().
float ExprGrapherView::ymin private
Definition at line 63 of file ExprGrapher2d.h.
Referenced by getWindow(), mouseMoveEvent(), setWindow(), and update().
float ExprGrapherView::z private
Definition at line 63 of file ExprGrapher2d.h.
Referenced by getWindow(), mouseMoveEvent(), setWindow(), and update().
The documentation for this class was generated from the following files:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprGrapher2d.h
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprGrapher2d.cpp