SeExpr: /disney/home/jberlin/projects/SeExpr.github/src/ui/Editable.h File Reference
Editable.h File Reference
#include <sstream>
#include <SeExpr2/Vec.h>
#include <SeExpr2/Curve.h>
#include <cstdio>
#include <cstring>
#include <ExprDeepWater.h>
Classes
struct Editable
struct NumberEditable
struct VectorEditable
struct StringEditable
struct GenericCurveEditable< TVAL >
struct AnimCurveEditable
struct ColorSwatchEditable
struct DeepWaterEditable
Macros
#define UNUSED(x) (void)(x)
Typedefs
typedef GenericCurveEditable
< SeExpr2::Vec3d > ColorCurveEditable
typedef GenericCurveEditable
< double > CurveEditable
Functions
void printVal (std::stringstream &stream, double v)
void printVal (std::stringstream &stream, const SeExpr2::Vec3d &v)
Macro Definition Documentation
#define UNUSED (x) (void)(x)
Definition at line 36 of file Editable.h.
Referenced by AnimCurveEditable::appendString(), GenericCurveEditable< TVAL >::controlsMatch(), AnimCurveEditable::controlsMatch(), ColorSwatchEditable::controlsMatch(), and DeepWaterEditable::controlsMatch().
Typedef Documentation
typedef GenericCurveEditable<SeExpr2::Vec3d> ColorCurveEditable
Definition at line 234 of file Editable.h.
typedef GenericCurveEditable<double> CurveEditable
Definition at line 235 of file Editable.h.
Function Documentation
void printVal (std::stringstream & stream, double v) inline
Definition at line 33 of file Editable.h.
Referenced by VectorEditable::appendString(), GenericCurveEditable< TVAL >::appendString(), ColorSwatchEditable::appendString(), and DeepWaterEditable::appendString().
void printVal (std::stringstream & stream, const SeExpr2::Vec3d & v) inline
Definition at line 34 of file Editable.h.