SeExpr: /jobs2/soft/users/aselle/src/seexpr-to-push/src/demos/imageSynth/imageSynth.cpp File Reference
/jobs2/soft/users/aselle/src/seexpr-to-push/src/demos/imageSynth/imageSynth.cpp File Reference
#include <map>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <SeExpression.h>
#include <png.h>
#include <fstream>
Classes
class ImageSynthExpr
Simple image synthesizer expression class to support our function grapher.
struct ImageSynthExpr::Var
Simple variable that just returns its internal value.
Functions
double clamp (double x)
int main (int argc, char *argv[])
Detailed Description
Definition in file imageSynth.cpp.
Function Documentation
double clamp (double x)
Definition at line 77 of file imageSynth.cpp.
References SeExpr::max(), and SeExpr::min().
int main (int argc, char * argv[])
Definition at line 79 of file imageSynth.cpp.
References SeExpr::clamp(), SeExpression::evaluate(), expr(), SeExpression::isValid(), SeExpression::parseError(), result, and ImageSynthExpr::vars.