SeExpr: /disney/home/jberlin/projects/SeExpr.github/src/demos/llvmtest.cpp File Reference
llvmtest.cpp File Reference
#include <Expression.h>
#include <fstream>
#include <string>
#include <sstream>
Classes
class llvmexpr
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 33 of file llvmtest.cpp.
References SeExpr2::Expression::evalFP(), SeExpr2::Expression::evalStr(), expr(), SeExpr2::Expression::isValid(), and SeExpr2::Expression::parseError().