SeExpr: SeExpr Namespace Reference
SeExpr Namespace Reference
Classes
class SeCurve
Interpolation curve class for double->double and double->SeVec3D.
struct VoronoiPointData
class CachedVoronoiFunc
struct CurveData
class CurveFuncX
class CCurveFuncX
class PrintFuncX
Functions
double compress (double x, double lo, double hi)
double expand (double x, double lo, double hi)
double fit (double x, double a1, double b1, double a2, double b2)
double gamma (double x, double g)
double bias (double x, double b)
double contrast (double x, double c)
double boxstep (double x, double a)
double linearstep (double x, double a, double b)
double smoothstep (double x, double a, double b)
double gaussstep (double x, double a, double b)
double remap (double x, double source, double range, double falloff, double interp)
double mix (double x, double y, double alpha)
SeVec3d satAdjust (const SeVec3d &rgb, double s, double i)
SeVec3d hsiAdjust (const SeVec3d &rgb, double h, double s, double i)
SeVec3d hsi (int n, const SeVec3d *args)
SeVec3d midhsi (int n, const SeVec3d *args)
SeVec3d rgbtohsl (const SeVec3d &rgb)
static double hslvalue (double x, double y, double H)
SeVec3d hsltorgb (const SeVec3d &hsl)
static SeVec3d saturate (const SeVec3d &Cin, double amt)
SeVec3d saturate (int n, const SeVec3d *args)
double hash (int n, double *args)
double noise (int n, const SeVec3d *args)
double snoise (const SeVec3d &p)
SeVec3d vnoise (const SeVec3d &p)
SeVec3d cnoise (const SeVec3d &p)
double snoise4 (int, const SeVec3d *args)
SeVec3d vnoise4 (int, const SeVec3d *args)
SeVec3d cnoise4 (int n, const SeVec3d *args)
double turbulence (int n, const SeVec3d *args)
SeVec3d vturbulence (int n, const SeVec3d *args)
SeVec3d cturbulence (int n, const SeVec3d *args)
double fbm (int n, const SeVec3d *args)
SeVec3d vfbm (int n, const SeVec3d *args)
double fbm4 (int n, const SeVec3d *args)
SeVec3d vfbm4 (int n, const SeVec3d *args)
SeVec3d cfbm (int n, const SeVec3d *args)
SeVec3d cfbm4 (int n, const SeVec3d *args)
double cellnoise (const SeVec3d &p)
SeVec3d ccellnoise (const SeVec3d &p)
double pnoise (const SeVec3d &p, const SeVec3d &period)
static SeVec3d * voronoi_points (VoronoiPointData &data, const SeVec3d &cell, double jitter)
static void voronoi_f1_3d (VoronoiPointData &data, const SeVec3d &p, double jitter, double &f1, SeVec3d &pos1)
static void voronoi_f1f2_3d (VoronoiPointData &data, const SeVec3d &p, double jitter, double &f1, SeVec3d &pos1, double &f2, SeVec3d &pos2)
SeVec3d voronoiFn (VoronoiPointData &data, int n, const SeVec3d *args)
SeVec3d cvoronoiFn (VoronoiPointData &data, int n, const SeVec3d *args)
SeVec3d pvoronoiFn (VoronoiPointData &data, int n, const SeVec3d *args)
double dist (double ax, double ay, double az, double bx, double by, double bz)
double length (const SeVec3d &v)
double hypot (double x, double y)
double dot (const SeVec3d &a, const SeVec3d &b)
SeVec3d norm (const SeVec3d &a)
SeVec3d cross (const SeVec3d &a, const SeVec3d &b)
double angle (const SeVec3d &a, const SeVec3d &b)
SeVec3d ortho (const SeVec3d &a, const SeVec3d &b)
SeVec3d rotate (int n, const SeVec3d *args)
SeVec3d up (const SeVec3d &P, const SeVec3d &upvec)
double cycle (double index, double loRange, double hiRange)
double pick (int n, double *params)
double choose (int n, double *params)
double wchoose (int n, double *params)
double spline (int n, double *params)
void defineBuiltins (SeExprFunc::Define, SeExprFunc::Define3 define3)
void initPerlin ()
double deg (double angle)
double rad (double angle)
double cosd (double x)
double sind (double x)
double tand (double x)
double acosd (double x)
double asind (double x)
double atand (double x)
double atan2d (double y, double x)
double clamp (double x, double lo, double hi)
double round (double x)
double max (double x, double y)
double min (double x, double y)
double invert (double x)
double remap (double x, double s, double r, double f, int interp)
double s_curve (double t)
This is the Quintic interpolant from Perlin's Improved Noise Paper.
template<int d>
unsigned char hashReduceChar (int index[d])
Does a hash reduce to a character.
template<int d>
uint32_t hashReduce (uint32_t index[d])
Does a hash reduce to an integer.
template<int d_in, int d_out, class T >
void CellNoise (const T *in, T *out)
Computes cellular noise (non-interpolated piecewise constant cell random values).
template<int d, class T , bool periodic>
T noiseHelper (const T *X, const int *period=0)
Noise with d_in dimensional domain, 1 dimensional abcissa.
template<int d_in, int d_out, class T >
void Noise (const T *in, T *out)
Noise with d_in dimensional domain, d_out dimensional abcissa.
template<int d_in, int d_out, class T >
void PNoise (const T *in, const int *period, T *out)
Periodic Noise with d_in dimensional domain, d_out dimensional abcissa.
template<int d_in, int d_out, bool turbulence, class T >
void FBM (const T *in, T *out, int octaves, T lacunarity, T gain)
Fractional Brownian Motion. If turbulence is true then turbulence computed.
template void CellNoise< 3, 1, double > (const double *, double *)
template void CellNoise< 3, 3, double > (const double *, double *)
template void Noise< 1, 1, double > (const double *, double *)
template void Noise< 2, 1, double > (const double *, double *)
template void Noise< 3, 1, double > (const double *, double *)
template void PNoise< 3, 1, double > (const double *, const int *, double *)
template void Noise< 4, 1, double > (const double *, double *)
template void Noise< 3, 3, double > (const double *, double *)
template void Noise< 4, 3, double > (const double *, double *)
template void FBM< 3, 1, false, double > (const double *, double *, int, double, double)
template void FBM< 3, 1, true, double > (const double *, double *, int, double, double)
template void FBM< 3, 3, false, double > (const double *, double *, int, double, double)
template void FBM< 3, 3, true, double > (const double *, double *, int, double, double)
template void FBM< 4, 1, false, double > (const double *, double *, int, double, double)
template void FBM< 4, 3, false, double > (const double *, double *, int, double, double)
Variables
static const char * fabs_docstring = "float abs(float x)\nabsolute value of x"
static const char * deg_docstring = "float deg(float angle)\nradians to degrees"
static const char * rad_docstring = "float deg(float angle)\ndegrees to radians"
static const char * cosd_docstring = "float cosd(float angle)\ncosine in degrees"
static const char * sind_docstring = "float sind(float angle)\nsine in degrees"
static const char * tand_docstring = "float tand(float angle)\ntangent in degrees"
static const char * acosd_docstring = "float acosd(float angle)\narc cosine in degrees"
static const char * asind_docstring = "float asind(float angle)\narc sine in degrees"
static const char * atand_docstring = "float atand(float angle)\narc tangent in degrees"
static const char * atan2d_docstring = "float atan2d(float y,float x)\narc tangent in degrees of y/x between -180 and 180"
static const char * cos_docstring = "float cos(float angle)\ncosine in radians"
static const char * sin_docstring = "float sin(float angle)\nsine in radians"
static const char * tan_docstring = "float tan(float angle)\ntangent in radians"
static const char * acos_docstring = "float acos(float angle)\narc cosine in radians"
static const char * asin_docstring = "float asin(float angle)\narc sine in radians"
static const char * atan_docstring = "float atan(float angle)\narc tangent in radians"
static const char * atan2_docstring = "float atan2(float y,float x)\narc tangent in radians of y/x between -PI and PI"
static const char * cosh_docstring = "float cosh(float angle)\nhyperbolic cosine in radians"
static const char * sinh_docstring = "float sinh(float angle)\nhyperbolic sine in radians"
static const char * tanh_docstring = "float tanh(float angle)\nhyperbolic tangent in radians"
static const char * acosh_docstring = "float acosh(float angle)\nhyperbolic arc cosine in radians"
static const char * asinh_docstring = "float asinh(float angle)\nhyperbolic arc sine in radians"
static const char * atanh_docstring = "float atanh(float angle)\nhyperbolic arc tangent in radians"
static const char * clamp_docstring = "float clamp(float x,float lo,float hi)\nconstrain x to range [lo,hi]"
static const char * round_docstring = "float round(float x)\nconstrain x to range [lo,hi]"
static const char * max_docstring = "float max(float a,float b)\ngreater of a and b"
static const char * min_docstring = "float min(float a,float b)\nlesser of a and b"
static const char * trunc_docstring = "float trunc(float a)\nnearest integer towards zero"
static const char * floor_docstring = "float floor(float a)\nnext lower integer"
static const char * ceil_docstring = "float ceil(float a)\nnext higher integer"
static const char * invert_docstring = "float invert(float a)\nDefined as 1-x"
static const char * cbrt_docstring = "float cbrt(float x)\ncube root"
static const char * sqrt_docstring = "float sqrt(float x)\nsquare root"
static const char * exp_docstring = "float exp(float x)\nE raised to the x power"
static const char * pow_docstring = "float pow(float x)\nx to the y power, also available as ^"
static const char * log_docstring = "float log(float x)\nNatural logarithm"
static const char * log10_docstring = "float log10(float x)\nBase 10 logarithm"
static const char * fmod_docstring = "float fmod(float x,float y)\nremainder of x/y (also available as % operator)"
static const char * turbulence_docstring = "float turbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance"
static const char * cturbulence_docstring = "color cturbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance"
static const char * vturbulence_docstring = "vector vturbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance"
static const char * compress_docstring = "float compress(float x,float lo,float hi)\nRemaps x in [0,1] to [lo,hi]"
static const char * expand_docstring = "float expand(float x,float lo,float hi)\nRemaps x in [lo,hi] to [0,1]"
static const char * fit_docstring = "float fit(float x,float a1,float b1,float a2,float b2)\nLinearly remaps x from the range [a1,b1] to the range [a2,b2]\n\nNote: This extrapolates if x is outside [a1,b1]\nTo clamp the result, use fit(x,a1,b1,a2,b2)->clamp(a2,b2)"
static const char * gamma_docstring = "float gamma(float x, float g)\nGamma correction of x with gamma factor g"
static const char * bias_docstring = "float bias(float x, float g)\nVariation of gamma where values less than 0.5 pull the curve down\nand values greater than 0.5 pull the curve up\npow(x,log(b)/log(0.5))"
static const char * contrast_docstring = "float contrast(float x,float x)\nAdjust the contrast.&nbsp; For c from 0 to 0.5, the contrast is decreased.&nbsp; For c &gt; 0.5, the contrast is increased."
static const char * boxstep_docstring = "float boxstep(float x,float a)\n if x < a then 0 otherwise 1"
static const char * linearstep_docstring = "float linearstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions linearly when &lt; x &lt; b "
static const char * smoothstep_docstring = "float smoothstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions smoothly (cubic) when &lt; x &lt; b"
static const char * gaussstep_docstring = "float gasussstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions smoothly (exponentially) when &lt; x &lt; b"
static const char * remap_docstring
static const char * mix_docstring = "mix(float a,float b,float alpha)\nBlend of a and b according to alpha."
static const char * hsi_docstring
static const char * midhsi_docstring
static const char * rgbtohsl_docstring
static const char * hsltorgb_docstring
static const char * saturate_docstring
static const char * hash_docstring
static const char * noise_docstring
static const char * snoise_docstring
static const char * vnoise_docstring
static const char * cnoise_docstring
static const char * snoise4_docstring
static const char * vnoise4_docstring
static const char * cnoise4_docstring
static const char * fbm_docstring
static const char * vfbm_docstring = "vector vfbm(vector vint octaves=6,float lacunarity=2,float gain=.5)"
static const char * fbm4_docstring
static const char * vfbm4_docstring = "vector vfbm4(vector v,float time,int octaves=6,float lacunarity=2,float gain=.5)"
static const char * cfbm_docstring = "color cfbm(vector vint octaves=6,float lacunarity=2,float gain=.5)"
static const char * cfbm4_docstring = "color cfbm4(vector v,float time,int octaves=6,float lacunarity=2,float gain=.5)"
static const char * cellnoise_docstring
static const char * ccellnoise_docstring
static const char * pnoise_docstring
static const char * voronoi_docstring
static const char * cvoronoi_docstring
static const char * pvoronoi_docstring
SeExpr::CachedVoronoiFunc voronoiFn
SeExpr::CachedVoronoiFunc cvoronoiFn
SeExpr::CachedVoronoiFunc pvoronoiFn
static const char * dist_docstring
static const char * length_docstring
static const char * hypot_docstring
static const char * dot_docstring
static const char * norm_docstring
static const char * cross_docstring
static const char * angle_docstring
static const char * ortho_docstring
static const char * rotate_docstring
static const char * up_docstring
static const char * cycle_docstring
static const char * pick_docstring
static const char * choose_docstring
static const char * wchoose_docstring
static const char * spline_docstring
SeExpr::CurveFuncX curve
static const char * curve_docstring
SeExpr::CCurveFuncX ccurve
static const char * ccurve_docstring
SeExpr::PrintFuncX printf
static const char * printf_docstring
Function Documentation
double SeExpr::acosd (double x) [inline]
Definition at line 29 of file SeExprBuiltins.h.
References deg().
double SeExpr::angle (const SeVec3d & a, const SeVec3d & b)
Referenced by rotate().
double SeExpr::asind (double x) [inline]
Definition at line 30 of file SeExprBuiltins.h.
References deg().
double SeExpr::atan2d (double y, double x) [inline]
Definition at line 32 of file SeExprBuiltins.h.
References deg().
double SeExpr::atand (double x) [inline]
Definition at line 31 of file SeExprBuiltins.h.
References deg().
double SeExpr::bias (double x, double b)
double SeExpr::boxstep (double x, double a)
SeVec3d SeExpr::ccellnoise (const SeVec3d & p)
Referenced by cvoronoiFn(), and voronoi_points().
template<int d_in, int d_out, class T > void SeExpr::CellNoise (const T * in, T * out) [inline]
Computes cellular noise (non-interpolated piecewise constant cell random values).
Cellular noise with input and output dimensionality.
double SeExpr::cellnoise (const SeVec3d & p)
Referenced by voronoiFn().
template void SeExpr::CellNoise< 3, 1, double > (const double * , double *)
template void SeExpr::CellNoise< 3, 3, double > (const double * , double *)
SeVec3d SeExpr::cfbm (int n, const SeVec3d * args)
SeVec3d SeExpr::cfbm4 (int n, const SeVec3d * args)
Definition at line 770 of file SeExprBuiltins.cpp.
References vfbm4().
double SeExpr::choose (int n, double * params)
double SeExpr::clamp (double x, double lo, double hi) [inline]
Definition at line 35 of file SeExprBuiltins.h.
Referenced by CurveScene::addPoint(), CCurveScene::addPoint(), SeExpr::SeCurve< T >::clampCurveSegment(), cvoronoiFn(), fbm4(), SeExprEdVectorControl::getColor(), main(), CurveScene::mouseMoveEvent(), SeExprEdChannelSlider::mouseMoveEvent(), CCurveScene::mouseMoveEvent(), CurveScene::mousePressEvent(), CCurveScene::mousePressEvent(), pvoronoiFn(), CurveScene::selPosChanged(), SeExprEdColorCurve::selPosChanged(), CCurveScene::selPosChanged(), SeExprEdCurve::selValChanged(), CurveScene::selValChanged(), SeExprEdVectorControl::updateControl(), vfbm4(), and voronoiFn().
SeVec3d SeExpr::cnoise (const SeVec3d & p)
SeVec3d SeExpr::cnoise4 (int n, const SeVec3d * args)
Definition at line 598 of file SeExprBuiltins.cpp.
References vnoise4().
double SeExpr::compress (double x, double lo, double hi)
double SeExpr::contrast (double x, double c)
double SeExpr::cosd (double x) [inline]
Definition at line 26 of file SeExprBuiltins.h.
References rad().
SeVec3d SeExpr::cross (const SeVec3d & a, const SeVec3d & b)
SeVec3d SeExpr::cturbulence (int n, const SeVec3d * args)
SeVec3d SeExpr::cvoronoiFn (VoronoiPointData & data, int n, const SeVec3d * args)
Definition at line 944 of file SeExprBuiltins.cpp.
References ccellnoise(), clamp(), length(), pos1, smoothstep(), vfbm(), voronoi_f1_3d(), and voronoi_f1f2_3d().
double SeExpr::cycle (double index, double loRange, double hiRange)
void SeExpr::defineBuiltins (SeExprFunc::Define , SeExprFunc::Define3 define3)
double SeExpr::deg (double angle) [inline]
Definition at line 24 of file SeExprBuiltins.h.
Referenced by acosd(), asind(), atan2d(), and atand().
double SeExpr::dist (double ax, double ay, double az, double bx, double by, double bz)
Referenced by voronoi_f1_3d(), and voronoi_f1f2_3d().
double SeExpr::dot (const SeVec3d & a, const SeVec3d & b)
double SeExpr::expand (double x, double lo, double hi)
template<int d_in, int d_out, bool turbulence, class T > void SeExpr::FBM (const T * in, T * out, int octaves, T lacunarity, T gain) [inline]
Fractional Brownian Motion. If turbulence is true then turbulence computed.
Noise with d_in dimensional domain, d_out dimensional abcissa If turbulence is true then Perlin's turbulence is computed
double SeExpr::fbm (int n, const SeVec3d * args)
double SeExpr::fbm4 (int n, const SeVec3d * args)
Definition at line 708 of file SeExprBuiltins.cpp.
References clamp().
template void SeExpr::FBM< 3, 1, false, double > (const double * , double * , int , double , double)
template void SeExpr::FBM< 3, 1, true, double > (const double * , double * , int , double , double)
template void SeExpr::FBM< 3, 3, false, double > (const double * , double * , int , double , double)
template void SeExpr::FBM< 3, 3, true, double > (const double * , double * , int , double , double)
template void SeExpr::FBM< 4, 1, false, double > (const double * , double * , int , double , double)
template void SeExpr::FBM< 4, 3, false, double > (const double * , double * , int , double , double)
double SeExpr::fit (double x, double a1, double b1, double a2, double b2)
double SeExpr::gamma (double x, double g)
double SeExpr::gaussstep (double x, double a, double b)
Referenced by remap().
double SeExpr::hash (int n, double * args)
template<int d> uint32_t SeExpr::hashReduce (uint32_t index[d]) [inline]
Does a hash reduce to an integer.
Definition at line 43 of file SeNoise.cpp.
References index(), and p.
template<int d> unsigned char SeExpr::hashReduceChar (int index[d]) [inline]
Does a hash reduce to a character.
Definition at line 25 of file SeNoise.cpp.
References index().
SeVec3d SeExpr::hsi (int n, const SeVec3d * args)
SeVec3d SeExpr::hsiAdjust (const SeVec3d & rgb, double h, double s, double i)
Definition at line 264 of file SeExprBuiltins.cpp.
References hsltorgb(), rgbtohsl(), and satAdjust().
SeVec3d SeExpr::hsltorgb (const SeVec3d & hsl)
Referenced by hsiAdjust().
static double SeExpr::hslvalue (double x, double y, double H) [inline, static]
Definition at line 387 of file SeExprBuiltins.cpp.
double SeExpr::hypot (double x, double y)
void SeExpr::initPerlin ()
double SeExpr::invert (double x) [inline]
Definition at line 43 of file SeExprBuiltins.h.
double SeExpr::length (const SeVec3d & v)
Referenced by cvoronoiFn(), SeExprEdHighlighter::highlightBlock(), and voronoiFn().
double SeExpr::linearstep (double x, double a, double b)
Referenced by remap().
double SeExpr::max (double x, double y) [inline]
Definition at line 39 of file SeExprBuiltins.h.
Referenced by SeExprSpecListNode::add(), clamp(), SeExpr::SeCurve< T >::getChannelValue(), CCurveScene::getCPixmap(), SeExpr::SeCurve< T >::getLowerBoundCV(), SeExpr::SeCurve< T >::getValue(), SeExprEdSlider::mouseMoveEvent(), satAdjust(), SeExprEdNumberControl::SeExprEdNumberControl(), and SeExprEdVectorControl::updateControl().
SeVec3d SeExpr::midhsi (int n, const SeVec3d * args)
double SeExpr::min (double x, double y) [inline]
Definition at line 40 of file SeExprBuiltins.h.
Referenced by SeExprSpecListNode::add(), clamp(), SeExpr::SeCurve< T >::getChannelValue(), CCurveScene::getCPixmap(), SeExpr::SeCurve< T >::getLowerBoundCV(), SeExpr::SeCurve< T >::getValue(), SeExprEdSlider::mouseMoveEvent(), satAdjust(), and SeExprEdVectorControl::updateControl().
double SeExpr::mix (double x, double y, double alpha)
template<int d_in, int d_out, class T > void SeExpr::Noise (const T * in, T * out) [inline]
Noise with d_in dimensional domain, d_out dimensional abcissa.
One octave of non-periodic Perlin noise.
double SeExpr::noise (int n, const SeVec3d * args)
template void SeExpr::Noise< 1, 1, double > (const double * , double *)
template void SeExpr::Noise< 2, 1, double > (const double * , double *)
template void SeExpr::Noise< 3, 1, double > (const double * , double *)
template void SeExpr::Noise< 3, 3, double > (const double * , double *)
template void SeExpr::Noise< 4, 1, double > (const double * , double *)
template void SeExpr::Noise< 4, 3, double > (const double * , double *)
template<int d, class T , bool periodic> T SeExpr::noiseHelper (const T * X, const int * period = 0) [inline]
Noise with d_in dimensional domain, 1 dimensional abcissa.
Definition at line 85 of file SeNoise.cpp.
References s_curve().
SeVec3d SeExpr::norm (const SeVec3d & a)
SeVec3d SeExpr::ortho (const SeVec3d & a, const SeVec3d & b)
double SeExpr::pick (int n, double * params)
template<int d_in, int d_out, class T > void SeExpr::PNoise (const T * in, const int * period, T * out) [inline]
Periodic Noise with d_in dimensional domain, d_out dimensional abcissa.
One octave of periodic noise period gives the integer period before tiles repease
double SeExpr::pnoise (const SeVec3d & p, const SeVec3d & period)
template void SeExpr::PNoise< 3, 1, double > (const double * , const int * , double *)
SeVec3d SeExpr::pvoronoiFn (VoronoiPointData & data, int n, const SeVec3d * args)
Definition at line 1003 of file SeExprBuiltins.cpp.
References clamp(), pos1, vfbm(), and voronoi_f1_3d().
double SeExpr::rad (double angle) [inline]
Definition at line 25 of file SeExprBuiltins.h.
Referenced by cosd(), sind(), and tand().
double SeExpr::remap (double x, double s, double r, double f, int interp)
double SeExpr::remap (double x, double source, double range, double falloff, double interp)
Definition at line 193 of file SeExprBuiltins.cpp.
References a, b, gaussstep(), linearstep(), and smoothstep().
SeVec3d SeExpr::rgbtohsl (const SeVec3d & rgb)
Referenced by hsiAdjust().
SeVec3d SeExpr::rotate (int n, const SeVec3d * args)
Definition at line 1148 of file SeExprBuiltins.cpp.
References angle(), SeVec3d::length(), and SeVec3d::rotateBy().
double SeExpr::round (double x) [inline]
Definition at line 38 of file SeExprBuiltins.h.
double SeExpr::s_curve (double t)
This is the Quintic interpolant from Perlin's Improved Noise Paper.
Definition at line 20 of file SeNoise.cpp.
Referenced by noiseHelper().
SeVec3d SeExpr::satAdjust (const SeVec3d & rgb, double s, double i)
Definition at line 230 of file SeExprBuiltins.cpp.
References max(), min(), x, y, and y2.
Referenced by hsiAdjust().
SeVec3d SeExpr::saturate (int n, const SeVec3d * args)
Definition at line 445 of file SeExprBuiltins.cpp.
References saturate().
static SeVec3d SeExpr::saturate (const SeVec3d & Cin, double amt) [inline, static]
Definition at line 435 of file SeExprBuiltins.cpp.
References SeVec3d::dot().
Referenced by saturate().
double SeExpr::sind (double x) [inline]
Definition at line 27 of file SeExprBuiltins.h.
References rad(), and sin().
double SeExpr::smoothstep (double x, double a, double b)
Referenced by cvoronoiFn(), remap(), and voronoiFn().
double SeExpr::snoise (const SeVec3d & p)
double SeExpr::snoise4 (int , const SeVec3d * args)
Definition at line 576 of file SeExprBuiltins.cpp.
double SeExpr::spline (int n, double * params)
double SeExpr::tand (double x) [inline]
Definition at line 28 of file SeExprBuiltins.h.
References rad().
double SeExpr::turbulence (int n, const SeVec3d * args)
SeVec3d SeExpr::up (const SeVec3d & P, const SeVec3d & upvec)
SeVec3d SeExpr::vfbm (int n, const SeVec3d * args)
Referenced by cvoronoiFn(), pvoronoiFn(), and voronoiFn().
SeVec3d SeExpr::vfbm4 (int n, const SeVec3d * args)
Definition at line 739 of file SeExprBuiltins.cpp.
References clamp().
Referenced by cfbm4().
SeVec3d SeExpr::vnoise (const SeVec3d & p)
SeVec3d SeExpr::vnoise4 (int , const SeVec3d * args)
Definition at line 587 of file SeExprBuiltins.cpp.
Referenced by cnoise4().
static void SeExpr::voronoi_f1_3d (VoronoiPointData & data, const SeVec3d & p, double jitter, double & f1, SeVec3d & pos1) [static]
Definition at line 839 of file SeExprBuiltins.cpp.
References dist(), SeVec3d::dot(), and voronoi_points().
Referenced by cvoronoiFn(), pvoronoiFn(), and voronoiFn().
static void SeExpr::voronoi_f1f2_3d (VoronoiPointData & data, const SeVec3d & p, double jitter, double & f1, SeVec3d & pos1, double & f2, SeVec3d & pos2) [static]
Definition at line 861 of file SeExprBuiltins.cpp.
References dist(), SeVec3d::dot(), and voronoi_points().
Referenced by cvoronoiFn(), and voronoiFn().
static SeVec3d* SeExpr::voronoi_points (VoronoiPointData & data, const SeVec3d & cell, double jitter) [static]
Definition at line 821 of file SeExprBuiltins.cpp.
References ccellnoise(), SeExpr::VoronoiPointData::cell, SeExpr::VoronoiPointData::jitter, and SeExpr::VoronoiPointData::points.
Referenced by voronoi_f1_3d(), and voronoi_f1f2_3d().
SeVec3d SeExpr::voronoiFn (VoronoiPointData & data, int n, const SeVec3d * args)
Definition at line 886 of file SeExprBuiltins.cpp.
References cellnoise(), clamp(), length(), pos1, smoothstep(), vfbm(), voronoi_f1_3d(), and voronoi_f1f2_3d().
SeVec3d SeExpr::vturbulence (int n, const SeVec3d * args)
double SeExpr::wchoose (int n, double * params)
Variable Documentation
const char* SeExpr::acos_docstring = "float acos(float angle)\narc cosine in radians" [static]
Definition at line 59 of file SeExprBuiltins.cpp.
const char* SeExpr::acosd_docstring = "float acosd(float angle)\narc cosine in degrees" [static]
Definition at line 51 of file SeExprBuiltins.cpp.
const char* SeExpr::acosh_docstring = "float acosh(float angle)\nhyperbolic arc cosine in radians" [static]
Definition at line 67 of file SeExprBuiltins.cpp.
const char* SeExpr::angle_docstring [static]
Initial value:
        "float angle(vector a,vector b)\n"
        "angle between two vectors (in radians)"
Definition at line 1133 of file SeExprBuiltins.cpp.
const char* SeExpr::asin_docstring = "float asin(float angle)\narc sine in radians" [static]
Definition at line 60 of file SeExprBuiltins.cpp.
const char* SeExpr::asind_docstring = "float asind(float angle)\narc sine in degrees" [static]
Definition at line 52 of file SeExprBuiltins.cpp.
const char* SeExpr::asinh_docstring = "float asinh(float angle)\nhyperbolic arc sine in radians" [static]
Definition at line 68 of file SeExprBuiltins.cpp.
const char* SeExpr::atan2_docstring = "float atan2(float y,float x)\narc tangent in radians of y/x between -PI and PI" [static]
Definition at line 62 of file SeExprBuiltins.cpp.
const char* SeExpr::atan2d_docstring = "float atan2d(float y,float x)\narc tangent in degrees of y/x between -180 and 180" [static]
Definition at line 54 of file SeExprBuiltins.cpp.
const char* SeExpr::atan_docstring = "float atan(float angle)\narc tangent in radians" [static]
Definition at line 61 of file SeExprBuiltins.cpp.
const char* SeExpr::atand_docstring = "float atand(float angle)\narc tangent in degrees" [static]
Definition at line 53 of file SeExprBuiltins.cpp.
const char* SeExpr::atanh_docstring = "float atanh(float angle)\nhyperbolic arc tangent in radians" [static]
Definition at line 69 of file SeExprBuiltins.cpp.
const char* SeExpr::bias_docstring = "float bias(float x, float g)\nVariation of gamma where values less than 0.5 pull the curve down\nand values greater than 0.5 pull the curve up\npow(x,log(b)/log(0.5))" [static]
Definition at line 129 of file SeExprBuiltins.cpp.
const char* SeExpr::boxstep_docstring = "float boxstep(float x,float a)\n if x < a then 0 otherwise 1" [static]
Definition at line 144 of file SeExprBuiltins.cpp.
const char* SeExpr::cbrt_docstring = "float cbrt(float x)\ncube root" [static]
Definition at line 80 of file SeExprBuiltins.cpp.
const char* SeExpr::ccellnoise_docstring [static]
Initial value:
        "color cellnoise(vector v)\n"
        "cellnoise generates a field of constant colored cubes based on the integer location.\n"
        "This is the same as the prman cellnoise function."
Definition at line 796 of file SeExprBuiltins.cpp.
SeExpr::CCurveFuncX SeExpr::ccurve
const char* SeExpr::ccurve_docstring [static]
Initial value:
        "color curve(float param,float pos0,color val0,int interp0,float pos1,color val1,int interp1,[...])\n\n"
        "Interpolates color ramp given by control points at 'param'. Control points are specified \n"
        "by triples of parameters pos_i, val_i, and interp_i. Interpolation codes are \n"
        "0 - none, 1 - linear, 2 - smooth, 3 - spline, \n"
        "4 - monotone (non oscillating spline)"
Definition at line 1468 of file SeExprBuiltins.cpp.
const char* SeExpr::ceil_docstring = "float ceil(float a)\nnext higher integer" [static]
Definition at line 77 of file SeExprBuiltins.cpp.
const char* SeExpr::cellnoise_docstring [static]
Initial value:
        "float cellnoise(vector v)\n"
        "cellnoise generates a field of constant colored cubes based on the integer location.\n"
        "This is the same as the prman cellnoise function."
Definition at line 784 of file SeExprBuiltins.cpp.
const char* SeExpr::cfbm4_docstring = "color cfbm4(vector v,float time,int octaves=6,float lacunarity=2,float gain=.5)" [static]
Definition at line 774 of file SeExprBuiltins.cpp.
const char* SeExpr::cfbm_docstring = "color cfbm(vector vint octaves=6,float lacunarity=2,float gain=.5)" [static]
Definition at line 768 of file SeExprBuiltins.cpp.
const char* SeExpr::choose_docstring [static]
Initial value:
        "float choose(float index,float choice1, float choice2, [...])\n"
        "Chooses one of the supplied choices based on the index (assumed to be in range [0..1])."
Definition at line 1250 of file SeExprBuiltins.cpp.
const char* SeExpr::clamp_docstring = "float clamp(float x,float lo,float hi)\nconstrain x to range [lo,hi]" [static]
Definition at line 71 of file SeExprBuiltins.cpp.
const char* SeExpr::cnoise4_docstring [static]
Initial value:
"color cnoise4 (vector v,float t)\n"
        "4D color noise formed with original perlin noise at location (C2 interpolant)"
Definition at line 602 of file SeExprBuiltins.cpp.
const char* SeExpr::cnoise_docstring [static]
Initial value:
"color cnoise (vector v)\n"
        "color noise formed with original perlin noise at location (C2 interpolant)"
Definition at line 573 of file SeExprBuiltins.cpp.
const char* SeExpr::compress_docstring = "float compress(float x,float lo,float hi)\nRemaps x in [0,1] to [lo,hi]" [static]
Definition at line 98 of file SeExprBuiltins.cpp.
const char* SeExpr::contrast_docstring = "float contrast(float x,float x)\nAdjust the contrast.&nbsp; For c from 0 to 0.5, the contrast is decreased.&nbsp; For c &gt; 0.5, the contrast is increased." [static]
Definition at line 137 of file SeExprBuiltins.cpp.
const char* SeExpr::cos_docstring = "float cos(float angle)\ncosine in radians" [static]
Definition at line 56 of file SeExprBuiltins.cpp.
const char* SeExpr::cosd_docstring = "float cosd(float angle)\ncosine in degrees" [static]
Definition at line 48 of file SeExprBuiltins.cpp.
const char* SeExpr::cosh_docstring = "float cosh(float angle)\nhyperbolic cosine in radians" [static]
Definition at line 64 of file SeExprBuiltins.cpp.
const char* SeExpr::cross_docstring [static]
Initial value:
        "vector cross(vector a,vector b)\n"
        "vector cross product"
Definition at line 1122 of file SeExprBuiltins.cpp.
const char* SeExpr::cturbulence_docstring = "color cturbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance" [static]
Definition at line 88 of file SeExprBuiltins.cpp.
SeExpr::CurveFuncX SeExpr::curve
Referenced by SeExprEdAnimCurveEditable::appendString(), SeExprEdCurve::openDetail(), and SeExprEdColorCurve::openDetail().
const char* SeExpr::curve_docstring [static]
Initial value:
        "float curve(float param,float pos0,float val0,int interp0,float pos1,float val1,int interp1,[...])\n\n"
        "Interpolates a 1D ramp defined by control points at 'param'. Control points are specified \n"
        "by triples of parameters pos_i, val_i, and interp_i. Interpolation codes are \n"
        "0 - none, 1 - linear, 2 - smooth, 3 - spline, \n"
        "4-monotone (non oscillating spline)"
Definition at line 1397 of file SeExprBuiltins.cpp.
const char* SeExpr::cvoronoi_docstring [static]
Initial value:
        "color cvoronoi(vector v, int type=1,float jitter=0.5, float fbmScale=0, int fbmOctaves=4,float fbmLacunarity=2, float fbmGain=.5)\n"
        "returns color in cellular pattern. It is a jittered variant of cellnoise."
Definition at line 998 of file SeExprBuiltins.cpp.
SeExpr::CachedVoronoiFunc SeExpr::cvoronoiFn
const char* SeExpr::cycle_docstring [static]
Initial value:
        "int cycle(int index, int loRange, int hiRange )\n"
        "Cycles through values between loRange and hiRange based on supplied index.\n"
        "This is an offset \"mod\" function. The result is rotates v such that the\n"
        "Y axis points in the given up direction"
Definition at line 1183 of file SeExprBuiltins.cpp.
const char* SeExpr::deg_docstring = "float deg(float angle)\nradians to degrees" [static]
Definition at line 45 of file SeExprBuiltins.cpp.
const char* SeExpr::dist_docstring [static]
Initial value:
        "float dist(vector a, vector b)\n"
        "distance between two points"
Definition at line 1075 of file SeExprBuiltins.cpp.
const char* SeExpr::dot_docstring [static]
Initial value:
        "float dot(vector a,vector b)\n"
        "vector dot product"
Definition at line 1100 of file SeExprBuiltins.cpp.
const char* SeExpr::exp_docstring = "float exp(float x)\nE raised to the x power" [static]
Definition at line 82 of file SeExprBuiltins.cpp.
const char* SeExpr::expand_docstring = "float expand(float x,float lo,float hi)\nRemaps x in [lo,hi] to [0,1]" [static]
Definition at line 106 of file SeExprBuiltins.cpp.
const char* SeExpr::fabs_docstring = "float abs(float x)\nabsolute value of x" [static]
Definition at line 42 of file SeExprBuiltins.cpp.
const char* SeExpr::fbm4_docstring [static]
Initial value:
"float fbm4(vector v,float time,int octaves=6,float lacunarity=2,float gain=.5)\n"
        "fbm (Fractal Brownian Motion) is a multi-frequency noise function. \n"
        "The base frequency is the same as the \"noise\" function. The total \n"
        "number of frequencies is controlled by octaves. The lacunarity is the \n"
        "spacing between the frequencies - a value of 2 means each octave is \n"
        "twice the previous frequency. The gain< controls how much each \n"
        "frequency is scaled relative to the previous frequency."
Definition at line 730 of file SeExprBuiltins.cpp.
const char* SeExpr::fbm_docstring [static]
Initial value:
        "float fbm(vector v,int octaves=6,float lacunarity=2,float gain=.5)\n"
        "fbm (Fractal Brownian Motion) is a multi-frequency noise function. \n"
        "The base frequency is the same as the \"noise\" function. The total \n"
        "number of frequencies is controlled by octaves. The lacunarity is the \n"
        "spacing between the frequencies - a value of 2 means each octave is \n"
        "twice the previous frequency. The gain< controls how much each \n"
        "frequency is scaled relative to the previous frequency."
Definition at line 675 of file SeExprBuiltins.cpp.
const char* SeExpr::fit_docstring = "float fit(float x,float a1,float b1,float a2,float b2)\nLinearly remaps x from the range [a1,b1] to the range [a2,b2]\n\nNote: This extrapolates if x is outside [a1,b1]\nTo clamp the result, use fit(x,a1,b1,a2,b2)->clamp(a2,b2)" [static]
Definition at line 113 of file SeExprBuiltins.cpp.
const char* SeExpr::floor_docstring = "float floor(float a)\nnext lower integer" [static]
Definition at line 76 of file SeExprBuiltins.cpp.
const char* SeExpr::fmod_docstring = "float fmod(float x,float y)\nremainder of x/y (also available as % operator)" [static]
Definition at line 86 of file SeExprBuiltins.cpp.
const char* SeExpr::gamma_docstring = "float gamma(float x, float g)\nGamma correction of x with gamma factor g" [static]
Definition at line 121 of file SeExprBuiltins.cpp.
const char* SeExpr::gaussstep_docstring = "float gasussstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions smoothly (exponentially) when &lt; x &lt; b" [static]
Definition at line 189 of file SeExprBuiltins.cpp.
const char* SeExpr::hash_docstring [static]
Initial value:
        "float hash(float seed1,[float seed2, ...])\n"
        "Like rand, but with no internal seeds. Any number of seeds may be given\n"
        "and the result will be a random function based on all the seeds."
Definition at line 508 of file SeExprBuiltins.cpp.
const char* SeExpr::hsi_docstring [static]
Initial value:
        "color  hsi(color x, float h, float s, float i, float map=1)\n"
        "The hsi function shifts the hue by h\n"
        "(in degrees) and scales the saturation and intensity by s and i\n"
        "respectively.&nbsp; An map may be supplied which will control the shift\n"
        "- the full shift will happen when the map is one and no shift will\n"
        "happen when the map is zero.&nbsp; The shift will be scaled back for\n"
        "values between zero and one."
Definition at line 294 of file SeExprBuiltins.cpp.
const char* SeExpr::hsltorgb_docstring [static]
Initial value:
        "color hsltorgb(color hsl)\n"
        "RGB to HSL color space conversion.\n"
        "HSL is Hue, Saturation, Lightness (all in range [0..1] )\n"
        "These functions have also been extended to support rgb and hsl values\n"
        "outside of the range [0..1] in a reasonable way.&nbsp; For any rgb or\n"
        "hsl value (except for negative s values), the conversion is\n"
        "well-defined and reversible."
Definition at line 425 of file SeExprBuiltins.cpp.
const char* SeExpr::hypot_docstring [static]
Initial value:
        "float hypot(vector v)\n"
        "length of 2d vector [x,y]"
Definition at line 1092 of file SeExprBuiltins.cpp.
const char* SeExpr::invert_docstring = "float invert(float a)\nDefined as 1-x" [static]
Definition at line 79 of file SeExprBuiltins.cpp.
const char* SeExpr::length_docstring [static]
Initial value:
        "float length(vector v)\n"
        "length of vector"
Definition at line 1083 of file SeExprBuiltins.cpp.
const char* SeExpr::linearstep_docstring = "float linearstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions linearly when &lt; x &lt; b " [static]
Definition at line 155 of file SeExprBuiltins.cpp.
const char* SeExpr::log10_docstring = "float log10(float x)\nBase 10 logarithm" [static]
Definition at line 85 of file SeExprBuiltins.cpp.
const char* SeExpr::log_docstring = "float log(float x)\nNatural logarithm" [static]
Definition at line 84 of file SeExprBuiltins.cpp.
const char* SeExpr::max_docstring = "float max(float a,float b)\ngreater of a and b" [static]
Definition at line 73 of file SeExprBuiltins.cpp.
const char* SeExpr::midhsi_docstring [static]
Initial value:
        "color midhsi(color x, float h, float s, float i, float map, float falloff=1, int interp=0)\n"
        "The midhsi function is just like the hsi function except that\n"
        "the control map is centered around the mid point (value of 0.5)\n"
        "and can scale the shift in both directions."
Definition at line 336 of file SeExprBuiltins.cpp.
const char* SeExpr::min_docstring = "float min(float a,float b)\nlesser of a and b" [static]
Definition at line 74 of file SeExprBuiltins.cpp.
const char* SeExpr::mix_docstring = "mix(float a,float b,float alpha)\nBlend of a and b according to alpha." [static]
Definition at line 227 of file SeExprBuiltins.cpp.
const char* SeExpr::noise_docstring [static]
Initial value:
        "float noise ( vector v ) <br>\n"
        "float noise ( float x, float y )\n"
        "float noise ( float x, float y, float z )\n"
        "float noise ( float x, float y, float z, float w )\n"
        "Original perlin noise at location (C2 interpolant)"
Definition at line 538 of file SeExprBuiltins.cpp.
const char* SeExpr::norm_docstring [static]
Initial value:
        "vector norm(vector v)\n"
        "vector scaled to unit length"
Definition at line 1111 of file SeExprBuiltins.cpp.
const char* SeExpr::ortho_docstring [static]
Initial value:
        "vector angle(vector a,vector b)\n"
        "normalized vector orthogonal to a and b scaled to unit length"
Definition at line 1143 of file SeExprBuiltins.cpp.
const char* SeExpr::pick_docstring [static]
Initial value:
        "int pick(float index, int loRange, int hiRange, [float weights, ...] )\n"
        "Picks values randomly between loRange and hiRange based on supplied index (which is\n"
        "automatically hashed).&nbsp; The values will be distributed according\n"
        "to the supplied weights.&nbsp; Any weights not supplied are assumed to\n"
        "be 1.0."
Definition at line 1236 of file SeExprBuiltins.cpp.
const char* SeExpr::pnoise_docstring [static]
Initial value:
        "float pnoise ( vector v, vector period )\n"
        "periodic noise"
Definition at line 810 of file SeExprBuiltins.cpp.
const char* SeExpr::pow_docstring = "float pow(float x)\nx to the y power, also available as ^" [static]
Definition at line 83 of file SeExprBuiltins.cpp.
SeExpr::PrintFuncX SeExpr::printf
const char* SeExpr::printf_docstring [static]
Initial value:
        "printf(string format,[vec0, vec1,  ...])\n"
        "Prints out a string to STDOUT, Format parameter allowed is %v"
Definition at line 1580 of file SeExprBuiltins.cpp.
const char* SeExpr::pvoronoi_docstring [static]
Initial value:
        "color pvoronoi(vector v, int type=1,float jitter=0.5, float fbmScale=0, int fbmOctaves=4,float fbmLacunarity=2, float fbmGain=.5)\n"
        "returns center of voronoi cell."
Definition at line 1036 of file SeExprBuiltins.cpp.
SeExpr::CachedVoronoiFunc SeExpr::pvoronoiFn
const char* SeExpr::rad_docstring = "float deg(float angle)\ndegrees to radians" [static]
Definition at line 46 of file SeExprBuiltins.cpp.
const char* SeExpr::remap_docstring [static]
Initial value:
        "remap(float x, float\n"
        "source, float range, float falloff, int interp)\nGeneral remapping function.\n"
        "When x is within +/- <i>range</i> of source, the result is one.\n"
        "The result falls to zero beyond that range over <i>falloff</i> distance.\n"
        "The falloff shape is controlled by <i>interp</i>. Numeric values\n"
        "or named constants may be used:\n"
        "&nbsp;&nbsp;&nbsp;&nbsp;int <b>linear</b>\n"
        "= 0\n"
        "&nbsp;&nbsp;&nbsp;&nbsp;int <b>smooth</b> = 1\n"
        "&nbsp;&nbsp;&nbsp;&nbsp;int <b>gaussian</b> = 2\n"
Definition at line 211 of file SeExprBuiltins.cpp.
const char* SeExpr::rgbtohsl_docstring [static]
Initial value:
        "color rgbtohsl(color rgb)\n"
        "RGB to HSL color space conversion.\n"
        "HSL is Hue, Saturation, Lightness (all in range [0..1] )\n"
        "These functions have also been extended to support rgb and hsl values\n"
        "outside of the range [0..1] in a reasonable way.&nbsp; For any rgb or\n"
        "hsl value (except for negative s values), the conversion is\n"
        "well-defined and reversible."
Definition at line 377 of file SeExprBuiltins.cpp.
const char* SeExpr::rotate_docstring [static]
Initial value:
        "vector rotate(vector v,vector axis,float angle)\n"
        "rotates v around axis by given angle (in radians)"
Definition at line 1158 of file SeExprBuiltins.cpp.
const char* SeExpr::round_docstring = "float round(float x)\nconstrain x to range [lo,hi]" [static]
Definition at line 72 of file SeExprBuiltins.cpp.
const char* SeExpr::saturate_docstring [static]
Initial value:
        "color saturate(color val, float amt)\n"
        "Scale saturation of color by amt.\n"
        "The color is scaled around the rec709 luminance value,\n"
        "and negative results are clamped at zero.\n"
Definition at line 450 of file SeExprBuiltins.cpp.
const char* SeExpr::sin_docstring = "float sin(float angle)\nsine in radians" [static]
Definition at line 57 of file SeExprBuiltins.cpp.
const char* SeExpr::sind_docstring = "float sind(float angle)\nsine in degrees" [static]
Definition at line 49 of file SeExprBuiltins.cpp.
const char* SeExpr::sinh_docstring = "float sinh(float angle)\nhyperbolic sine in radians" [static]
Definition at line 65 of file SeExprBuiltins.cpp.
const char* SeExpr::smoothstep_docstring = "float smoothstep(float x,float a,float b)\n if x &lt; a then 0, if x &gt; b then 1, and\nx transitions smoothly (cubic) when &lt; x &lt; b" [static]
Definition at line 172 of file SeExprBuiltins.cpp.
const char* SeExpr::snoise4_docstring [static]
Initial value:
"float snoise4 (vector v,float t)\n"
        "4D signed noise w/ range -1 to 1 formed with original perlin noise at location (C2 interpolant)"
Definition at line 583 of file SeExprBuiltins.cpp.
const char* SeExpr::snoise_docstring [static]
Initial value:
        "float snoise ( vector v)\n"
        "signed noise w/ range -1 to 1 formed with original perlin noise at location (C2 interpolant)"
Definition at line 552 of file SeExprBuiltins.cpp.
const char* SeExpr::spline_docstring [static]
Initial value:
        "float spline(float param,float y1,float y2,float y3,float y4,[...])\n\n"
        "Interpolates a set of values to the parameter specified where y1, ..., yn are\n"
        "distributed evenly from [0...1]"
Definition at line 1318 of file SeExprBuiltins.cpp.
const char* SeExpr::sqrt_docstring = "float sqrt(float x)\nsquare root" [static]
Definition at line 81 of file SeExprBuiltins.cpp.
const char* SeExpr::tan_docstring = "float tan(float angle)\ntangent in radians" [static]
Definition at line 58 of file SeExprBuiltins.cpp.
const char* SeExpr::tand_docstring = "float tand(float angle)\ntangent in degrees" [static]
Definition at line 50 of file SeExprBuiltins.cpp.
const char* SeExpr::tanh_docstring = "float tanh(float angle)\nhyperbolic tangent in radians" [static]
Definition at line 66 of file SeExprBuiltins.cpp.
const char* SeExpr::trunc_docstring = "float trunc(float a)\nnearest integer towards zero" [static]
Definition at line 75 of file SeExprBuiltins.cpp.
const char* SeExpr::turbulence_docstring = "float turbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance" [static]
Definition at line 87 of file SeExprBuiltins.cpp.
const char* SeExpr::up_docstring [static]
Initial value:
        "vector up(vector P,vector upvec)\n"
        "rotates v such that the Y axis points in the given up direction"
Definition at line 1169 of file SeExprBuiltins.cpp.
const char* SeExpr::vfbm4_docstring = "vector vfbm4(vector v,float time,int octaves=6,float lacunarity=2,float gain=.5)" [static]
Definition at line 761 of file SeExprBuiltins.cpp.
const char* SeExpr::vfbm_docstring = "vector vfbm(vector vint octaves=6,float lacunarity=2,float gain=.5)" [static]
Definition at line 705 of file SeExprBuiltins.cpp.
const char* SeExpr::vnoise4_docstring [static]
Initial value:
"vector vnoise4 (vector v,float t)\n"
        "4D vector noise formed with original perlin noise at location (C2 interpolant)"
Definition at line 594 of file SeExprBuiltins.cpp.
const char* SeExpr::vnoise_docstring [static]
Initial value:
        "vector vnoise ( vector v)\n"
        "vector noise formed with original perlin noise at location (C2 interpolant)"
Definition at line 564 of file SeExprBuiltins.cpp.
const char* SeExpr::voronoi_docstring [static]
Initial value:
        "float voronoi(vector v, int type=1,float jitter=0.5, float fbmScale=0, int fbmOctaves=4,float fbmLacunarity=2, float fbmGain=.5)\n"
        "voronoi is a cellular noise pattern. It is a jittered variant of cellnoise."
Definition at line 939 of file SeExprBuiltins.cpp.
SeExpr::CachedVoronoiFunc SeExpr::voronoiFn
const char* SeExpr::vturbulence_docstring = "vector vturbulence(vector v,int octaves=6,float lacunarity=2,float gain=.5)\nAbsolute value of each noise term is taken. This gives billowy appearance" [static]
Definition at line 89 of file SeExprBuiltins.cpp.
const char* SeExpr::wchoose_docstring [static]
Initial value:
        "float wchoose(float index,float choice1, float weight1, float choice2, float weight2, [...] )\n"
        "Chooses one of the supplied choices based on the index (assumed to be in range[0..1]).\n"
        "The values will be distributed according to the supplied weights."
Definition at line 1296 of file SeExprBuiltins.cpp.