SeExpr: /disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExpressionEditor.cpp File Reference
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExpressionEditor.cpp File Reference
#include <iostream>
#include <string>
#include <QtGui/QApplication>
#include "SeExprEdDialog.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 17 of file SeExpressionEditor.cpp.
References SeExprEdDialog::exec(), SeExprEdDialog::getExpressionString(), and SeExprEdDialog::setExpressionString().