SeExpr: SeDeepWater< T > Struct Template Reference
SeDeepWater< T > Struct Template Reference
#include <ExprDeepWater.h>
Public Member Functions
SeDeepWater ()
virtual ~SeDeepWater ()
void setParams (const SeDeepWaterParams &paramsIn)
T sqr (T x)
T toIndex (const T x)
T fromIndex (const T index)
T fromLog (const T x)
T toLog (const T z)
T powerLaw (const T x, const SeDeepWaterParams &params)
T rescale (const T x)
void generateSpectrum ()
T getValue (double param) const
Evaluates curve and returns full value.
T getKLow ()
T getKHigh ()
bool inGrid ()
Static Public Member Functions
static T kscale ()
static T bottom_offset ()
Public Attributes
T gravity
size_t gridSize
SeDeepWaterParams params
std::vector< T > energy
T klowindex
T khighindex
T kmaxindex
Detailed Description
template<class T>
struct SeDeepWater< T >
Definition at line 53 of file ExprDeepWater.h.
Constructor & Destructor Documentation
template<class T > SeDeepWater< T >::SeDeepWater () inline
Definition at line 55 of file ExprDeepWater.h.
template<class T > virtual SeDeepWater< T >::~SeDeepWater () inline virtual
Definition at line 56 of file ExprDeepWater.h.
Member Function Documentation
template<class T > static T SeDeepWater< T >::bottom_offset () inline static
Definition at line 79 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::fromLog(), and SeDeepWater< T >::toLog().
template<class T > T SeDeepWater< T >::fromIndex (const T index) inline
Definition at line 74 of file ExprDeepWater.h.
References index(), and SeDeepWater< T >::kscale().
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > T SeDeepWater< T >::fromLog (const T x) inline
Definition at line 81 of file ExprDeepWater.h.
References SeDeepWater< T >::bottom_offset().
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > void SeDeepWater< T >::generateSpectrum () inline
Definition at line 101 of file ExprDeepWater.h.
References SeDeepWaterParams::directionalFactorExponent, SeDeepWater< T >::energy, SeDeepWater< T >::fromIndex(), SeDeepWater< T >::fromLog(), SeDeepWater< T >::gravity, SeDeepWater< T >::gridSize, SeDeepWater< T >::khighindex, SeDeepWater< T >::klowindex, SeDeepWater< T >::kmaxindex, SeDeepWaterParams::lengthCutoff, SeDeepWater< T >::params, SeDeepWater< T >::powerLaw(), SeDeepWater< T >::rescale(), SeDeepWater< T >::sqr(), SeDeepWaterParams::tileSize, SeDeepWater< T >::toIndex(), SeDeepWater< T >::toLog(), SeDeepWaterParams::windSpeed, and x.
Referenced by DeepWaterScene::rebuildDeepWater().
template<class T > T SeDeepWater< T >::getKHigh () inline
Definition at line 143 of file ExprDeepWater.h.
References SeDeepWater< T >::energy, and SeDeepWater< T >::khighindex.
Referenced by DeepWaterScene::drawGrid().
template<class T > T SeDeepWater< T >::getKLow () inline
Definition at line 138 of file ExprDeepWater.h.
References SeDeepWater< T >::energy, and SeDeepWater< T >::klowindex.
Referenced by DeepWaterScene::drawGrid().
template<class T > T SeDeepWater< T >::getValue (double param) const inline
Evaluates curve and returns full value.
Definition at line 130 of file ExprDeepWater.h.
References SeDeepWater< T >::energy, and index().
Referenced by DeepWaterScene::drawPoly().
template<class T > bool SeDeepWater< T >::inGrid () inline
Definition at line 148 of file ExprDeepWater.h.
References SeDeepWater< T >::khighindex, SeDeepWater< T >::klowindex, and SeDeepWater< T >::kmaxindex.
Referenced by DeepWaterScene::drawGrid().
template<class T > static T SeDeepWater< T >::kscale () inline static
Definition at line 67 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::fromIndex(), and SeDeepWater< T >::toIndex().
template<class T > T SeDeepWater< T >::powerLaw (const T x, const SeDeepWaterParams & params) inline
Definition at line 91 of file ExprDeepWater.h.
References SeDeepWaterParams::amplitude, SeDeepWaterParams::directionalFactorExponent, pow(), and SeDeepWater< T >::sqr().
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > T SeDeepWater< T >::rescale (const T x) inline
Definition at line 96 of file ExprDeepWater.h.
References pow().
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > void SeDeepWater< T >::setParams (const SeDeepWaterParams & paramsIn) inline
Definition at line 58 of file ExprDeepWater.h.
References SeDeepWater< T >::gridSize, SeDeepWater< T >::params, and SeDeepWaterParams::resolution.
Referenced by DeepWaterScene::rebuildDeepWater().
template<class T > T SeDeepWater< T >::sqr (T x) inline
Definition at line 63 of file ExprDeepWater.h.
References x.
Referenced by SeDeepWater< T >::generateSpectrum(), and SeDeepWater< T >::powerLaw().
template<class T > T SeDeepWater< T >::toIndex (const T x) inline
Definition at line 69 of file ExprDeepWater.h.
References SeDeepWater< T >::kscale().
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > T SeDeepWater< T >::toLog (const T z) inline
Definition at line 86 of file ExprDeepWater.h.
References SeDeepWater< T >::bottom_offset().
Referenced by SeDeepWater< T >::generateSpectrum().
Member Data Documentation
template<class T > std::vector<T> SeDeepWater< T >::energy
Definition at line 153 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), SeDeepWater< T >::getKHigh(), SeDeepWater< T >::getKLow(), and SeDeepWater< T >::getValue().
template<class T > T SeDeepWater< T >::gravity
Definition at line 150 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum().
template<class T > size_t SeDeepWater< T >::gridSize
Definition at line 151 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), and SeDeepWater< T >::setParams().
template<class T > T SeDeepWater< T >::khighindex
Definition at line 155 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), SeDeepWater< T >::getKHigh(), and SeDeepWater< T >::inGrid().
template<class T > T SeDeepWater< T >::klowindex
Definition at line 154 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), SeDeepWater< T >::getKLow(), and SeDeepWater< T >::inGrid().
template<class T > T SeDeepWater< T >::kmaxindex
Definition at line 156 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), and SeDeepWater< T >::inGrid().
template<class T > SeDeepWaterParams SeDeepWater< T >::params
Definition at line 152 of file ExprDeepWater.h.
Referenced by SeDeepWater< T >::generateSpectrum(), and SeDeepWater< T >::setParams().
The documentation for this struct was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/ui/ExprDeepWater.h