SeExpr: SeExprEdExpression::DummyFuncX Struct Reference
SeExprEdExpression::DummyFuncX Struct Reference
#include <SeExprEdExpression.h>
Public Member Functions
DummyFuncX ()
bool prep (SeExprFuncNode *node, bool wantVec)
void eval (const SeExprFuncNode *node, SeVec3d &result) const
Detailed Description
Definition at line 47 of file SeExprEdExpression.h.
Constructor & Destructor Documentation
SeExprEdExpression::DummyFuncX::DummyFuncX () [inline]
Definition at line 49 of file SeExprEdExpression.h.
Member Function Documentation
void SeExprEdExpression::DummyFuncX::eval (const SeExprFuncNode * node, SeVec3d & result) const [inline, virtual]
evaluate the expression. the given node is where in the parse tree the evaluation is for
Implements SeExprFuncX.
Definition at line 61 of file SeExprEdExpression.h.
References UNUSED.
bool SeExprEdExpression::DummyFuncX::prep (SeExprFuncNode * node, bool wantVec) [inline, virtual]
prep the expression by doing all type checking argument checking, etc.
Reimplemented from SeExprFuncX.
Definition at line 53 of file SeExprEdExpression.h.
References SeExprNode::child(), SeExprFuncNode::isStrArg(), SeExprNode::numChildren(), and SeExprNode::prep().
The documentation for this struct was generated from the following file:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdExpression.h