SeExpr: ColorSwatchEditable Struct Reference
ColorSwatchEditable Struct Reference
#include <Editable.h>
Public Member Functions
ColorSwatchEditable (const std::string &name, int startPos, int endPos)
bool parseComment (const std::string &comment)
parses a comment. if false is returned then delete the control from the editable
std::string str () const
void appendString (std::stringstream &stream) const
virtual bool controlsMatch (const Editable &other) const
void add (const SeExpr2::Vec3d &value)
void change (int index, const SeExpr2::Vec3d &value)
void remove (int index)
void print ()
Public Member Functions inherited from Editable
Editable (const std::string &name, int startPos, int endPos)
void updatePositions (const Editable &other)
virtual ~Editable ()
Public Attributes
std::vector< SeExpr2::Vec3d > colors
std::string labelType
Public Attributes inherited from Editable
std::string name
int startPos
int endPos
Detailed Description
Definition at line 301 of file Editable.h.
Constructor & Destructor Documentation
ColorSwatchEditable::ColorSwatchEditable (const std::string & name, int startPos, int endPos) inline
Definition at line 306 of file Editable.h.
Member Function Documentation
void ColorSwatchEditable::add (const SeExpr2::Vec3d & value) inline
Definition at line 345 of file Editable.h.
References colors.
Referenced by ColorSwatchControl::colorAdded().
void ColorSwatchEditable::appendString (std::stringstream & stream) const inline virtual
Implements Editable.
Definition at line 328 of file Editable.h.
References colors, and printVal().
void ColorSwatchEditable::change (int index, const SeExpr2::Vec3d & value) inline
Definition at line 349 of file Editable.h.
References colors, index(), and value().
Referenced by ColorSwatchControl::colorChanged().
virtual bool ColorSwatchEditable::controlsMatch (const Editable & other) const inline virtual
Implements Editable.
Definition at line 336 of file Editable.h.
References UNUSED.
bool ColorSwatchEditable::parseComment (const std::string & comment) inline virtual
parses a comment. if false is returned then delete the control from the editable
Implements Editable.
Definition at line 312 of file Editable.h.
References labelType.
void ColorSwatchEditable::print () inline
Definition at line 357 of file Editable.h.
References colors.
void ColorSwatchEditable::remove (int index) inline
Definition at line 353 of file Editable.h.
References colors, and index().
Referenced by ColorSwatchControl::colorRemoved().
std::string ColorSwatchEditable::str () const inline virtual
Reimplemented from Editable.
Definition at line 322 of file Editable.h.
References Editable::name.
Member Data Documentation
std::vector<SeExpr2::Vec3d> ColorSwatchEditable::colors
Definition at line 303 of file Editable.h.
Referenced by add(), appendString(), ColorSwatchControl::buildSwatchWidget(), change(), ColorSwatchControl::colorAdded(), ColorSwatchControl::colorChanged(), ColorSwatchControl::colorRemoved(), print(), and remove().
std::string ColorSwatchEditable::labelType
Definition at line 304 of file Editable.h.
Referenced by ColorSwatchControl::ColorSwatchControl(), and parseComment().
The documentation for this struct was generated from the following file:
/disney/home/jberlin/projects/SeExpr.github/src/ui/Editable.h