SeExpr: varblocks.txt File Reference
varblocks.txt File Reference
Functions
<!--CopyrightDisneyEnterprises,
Inc.Allrightsreserved.LicensedundertheApacheLicense,
Version2.0(the"License");youmaynotusethisfileexceptincompliancewiththeLicenseandthefollowingmodificationtoit:Section6Trademarks.deletedandreplacedwith:6.Trademarks.ThisLicensedoesnotgrantpermissiontousethetradenames,
trademarks, servicemarks,
orproductnamesoftheLicensoranditsaffiliates,
exceptasrequiredforreproducingthecontentoftheNOTICEfile.YoumayobtainacopyoftheLicenseathttp:-->
< p > You can still define resolveVar () and resolveFunc() methods in your custom expression classes
with numParticles
numAttributes A variable block
contains variable names and
types but doesn t care what
the values are< pre > void f (const std::string &s, MyParticleData *p, int outputDim=3)
</pre > To parallelize
evaluation per a simple
parallel_for can be p numParticles ())
Variables
</pre > To parallelize
evaluation per particle
</pre > To parallelize
evaluation per a simple
parallel_for can be used
</pre > To parallelize
evaluation per a simple
parallel_for can be p
blocked_range r VarBlock myBlock =block.clone()
e evalMultiple & myblock
Function Documentation
with numParticles numAttributes A variable block contains variable names and types but doesn t care what the values are<pre> void f (const std::string & s, MyParticleData * p, int outputDim = 3)
Definition at line 35 of file varblocks.txt.
References SeExpr2::VarBlockCreator::create(), SeExpr2::VarBlock::Pointer(), SeExpr2::VarBlockCreator::registerVariable(), and SeExpr2::TypeVec().
Referenced by SeExpr2::ExprIfThenElseNode::buildInterpreter(), SeExpr2::ExprAssignNode::buildInterpreter(), SeExpr2::ExprCompareNode::buildInterpreter(), SeExpr2::ExprVarNode::buildInterpreter(), ExprTextEdit::contextMenuEvent(), SeExpr2::copyVarToPromotedPosition(), SeExpr2::Expression::evalMultiple(), SeExpr2::getTemplatizedOp(), SeExpr2::getTemplatizedOp2(), ExprGrapherView::mouseMoveEvent(), SeExpr2::noiseHelper(), ExprGrapherView::paintGL(), and SeExpr2::ExprVecNode::value().
</pre> To parallelize evaluation per a simple parallel_for can be p numParticles ()
<!--CopyrightDisneyEnterprises,Inc.Allrightsreserved.LicensedundertheApacheLicense,Version2.0(the"License");youmaynotusethisfileexceptincompliancewiththeLicenseandthefollowingmodificationtoit:Section6Trademarks.deletedandreplacedwith:6.Trademarks.ThisLicensedoesnotgrantpermissiontousethetradenames,trademarks,servicemarks,orproductnamesoftheLicensoranditsaffiliates,exceptasrequiredforreproducingthecontentoftheNOTICEfile.YoumayobtainacopyoftheLicenseathttp:--><p> You can still define resolveVar ()
Variable Documentation
</pre> To parallelize evaluation per a simple parallel_for can be p blocked_range r VarBlock myBlock =block.clone()
Definition at line 77 of file varblocks.txt.
e evalMultiple& myblock
Definition at line 78 of file varblocks.txt.
</pre> To parallelize evaluation per particle
Definition at line 73 of file varblocks.txt.
</pre> To parallelize evaluation per a simple parallel_for can be used
Definition at line 73 of file varblocks.txt.