SeExpr: SeExprEdShortTextEdit Class Reference
SeExprEdShortTextEdit Class Reference
#include <SeExprEdShortEdit.h>
Signals
void editingFinished ()
Public Member Functions
SeExprEdShortTextEdit (QWidget *parent)
Public Attributes
QCompleter * completer
SeExprEdCompletionModel * completionModel
Protected Member Functions
void showTip (const QString &string)
void hideTip ()
void paintEvent (QPaintEvent *e)
virtual void keyPressEvent (QKeyEvent *e)
virtual void focusInEvent (QFocusEvent *e)
virtual void focusOutEvent (QFocusEvent *e)
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseDoubleClickEvent (QMouseEvent *event)
virtual void wheelEvent (QWheelEvent *e)
void setColor (bool editing)
void finishEdit ()
Private Slots
void insertCompletion (const QString &completion)
Private Attributes
SeExprEdHighlighter * highlighter
bool editing
QString savedText
SeExprEdPopupDocumentation * _tip
QStyle * lastStyleForHighlighter
Detailed Description
Definition at line 104 of file SeExprEdShortEdit.h.
Constructor & Destructor Documentation
SeExprEdShortTextEdit::SeExprEdShortTextEdit (QWidget * parent)
Definition at line 316 of file SeExprEdShortEdit.cpp.
References completer, completionModel, SeExprEdHighlighter::fixStyle(), highlighter, insertCompletion(), and lastStyleForHighlighter.
Member Function Documentation
void SeExprEdShortTextEdit::editingFinished () [signal]
Referenced by finishEdit().
void SeExprEdShortTextEdit::finishEdit () [protected]
Definition at line 517 of file SeExprEdShortEdit.cpp.
References editing, editingFinished(), and setColor().
Referenced by focusOutEvent(), and keyPressEvent().
void SeExprEdShortTextEdit::focusInEvent (QFocusEvent * e) [protected, virtual]
Definition at line 345 of file SeExprEdShortEdit.cpp.
References completer.
void SeExprEdShortTextEdit::focusOutEvent (QFocusEvent * e) [protected, virtual]
Definition at line 352 of file SeExprEdShortEdit.cpp.
References finishEdit(), hideTip(), and setColor().
void SeExprEdShortTextEdit::hideTip () [protected]
Definition at line 499 of file SeExprEdShortEdit.cpp.
References _tip.
Referenced by focusOutEvent(), keyPressEvent(), mouseDoubleClickEvent(), and mousePressEvent().
void SeExprEdShortTextEdit::insertCompletion (const QString & completion) [private, slot]
Definition at line 504 of file SeExprEdShortEdit.cpp.
References completer.
Referenced by SeExprEdShortTextEdit().
void SeExprEdShortTextEdit::keyPressEvent (QKeyEvent * e) [protected, virtual]
Definition at line 386 of file SeExprEdShortEdit.cpp.
References completer, completionModel, editing, finishEdit(), SeExprEdCompletionModel::getDocString(), hideTip(), index(), savedText, setColor(), and showTip().
void SeExprEdShortTextEdit::mouseDoubleClickEvent (QMouseEvent * event) [protected, virtual]
Definition at line 370 of file SeExprEdShortEdit.cpp.
References hideTip().
void SeExprEdShortTextEdit::mousePressEvent (QMouseEvent * event) [protected, virtual]
Definition at line 364 of file SeExprEdShortEdit.cpp.
References hideTip().
void SeExprEdShortTextEdit::paintEvent (QPaintEvent * e) [protected]
Definition at line 376 of file SeExprEdShortEdit.cpp.
References SeExprEdHighlighter::fixStyle(), highlighter, and lastStyleForHighlighter.
void SeExprEdShortTextEdit::setColor (bool editing) [protected]
Definition at line 527 of file SeExprEdShortEdit.cpp.
Referenced by finishEdit(), focusOutEvent(), and keyPressEvent().
void SeExprEdShortTextEdit::showTip (const QString & string) [protected]
Definition at line 485 of file SeExprEdShortEdit.cpp.
References _tip.
Referenced by keyPressEvent().
virtual void SeExprEdShortTextEdit::wheelEvent (QWheelEvent * e) [inline, protected, virtual]
Definition at line 131 of file SeExprEdShortEdit.h.
Member Data Documentation
SeExprEdPopupDocumentation* SeExprEdShortTextEdit::_tip [private]
Definition at line 112 of file SeExprEdShortEdit.h.
Referenced by hideTip(), and showTip().
QCompleter* SeExprEdShortTextEdit::completer
Definition at line 116 of file SeExprEdShortEdit.h.
Referenced by focusInEvent(), insertCompletion(), keyPressEvent(), SeExprEdShortEdit::rebuildControls(), SeExprEdShortTextEdit(), and SeExprEdShortEdit::updateCompleter().
SeExprEdCompletionModel* SeExprEdShortTextEdit::completionModel
Definition at line 117 of file SeExprEdShortEdit.h.
Referenced by SeExprEdShortEdit::clearExtraCompleters(), keyPressEvent(), SeExprEdShortEdit::rebuildControls(), SeExprEdShortEdit::registerExtraFunction(), SeExprEdShortEdit::registerExtraVariable(), SeExprEdShortTextEdit(), SeExprEdShortEdit::showDetails(), and SeExprEdShortEdit::updateCompleter().
bool SeExprEdShortTextEdit::editing [private]
Definition at line 110 of file SeExprEdShortEdit.h.
Referenced by finishEdit(), and keyPressEvent().
SeExprEdHighlighter* SeExprEdShortTextEdit::highlighter [private]
Definition at line 106 of file SeExprEdShortEdit.h.
Referenced by paintEvent(), and SeExprEdShortTextEdit().
QStyle* SeExprEdShortTextEdit::lastStyleForHighlighter [private]
Definition at line 113 of file SeExprEdShortEdit.h.
Referenced by paintEvent(), and SeExprEdShortTextEdit().
QString SeExprEdShortTextEdit::savedText [private]
Definition at line 111 of file SeExprEdShortEdit.h.
Referenced by keyPressEvent().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdShortEdit.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdShortEdit.cpp