SeExpr: SeExprEdDialog Class Reference
SeExprEdDialog Class Reference
#include <SeExprEdDialog.h>
Public Slots
void applyExpression ()
void clearExpression ()
Signals
void expressionApplied ()
Public Member Functions
SeExprEdDialog (QWidget *parent)
std::string getExpressionString ()
void setExpressionString (const std::string &str)
int exec ()
void showEditor (int idx)
Public Attributes
SeExprEditor * editor
SeExprEdBrowser * browser
Protected Member Functions
void keyPressEvent (QKeyEvent *event)
void findHelper (QTextDocument::FindFlags flags)
Private Slots
void verifiedApply ()
void verifiedAccept ()
void findNextInHelp ()
void findPrevInHelp ()
void _showEditor ()
Private Member Functions
void setupHelp (QTabWidget *tab)
Private Attributes
SeExprEdGrapherWidget * grapher
QLabel * previewCommentLabel
QPushButton * acceptButton
QPushButton * cancelButton
SeExprEdControlCollection * controls
QPushButton * applyButton
QPushButton * previewButton
QPushButton * saveButton
QPushButton * saveAsButton
QPushButton * saveLocalButton
QPushButton * clearButton
QLineEdit * helpFindBox
QTimer * showEditorTimer
QTextBrowser * helpBrowser
QTextCursor cursor
QString prevFind
int _currentEditorIdx
Detailed Description
Definition at line 40 of file SeExprEdDialog.h.
Constructor & Destructor Documentation
SeExprEdDialog::SeExprEdDialog (QWidget * parent)
Definition at line 33 of file SeExprEdDialog.cpp.
References _showEditor(), acceptButton, applyButton, applyExpression(), browser, cancelButton, clearButton, clearExpression(), controls, editor, grapher, previewButton, previewCommentLabel, saveAsButton, saveButton, saveLocalButton, setupHelp(), showEditorTimer, verifiedAccept(), and verifiedApply().
Member Function Documentation
void SeExprEdDialog::_showEditor () [private, slot]
Definition at line 148 of file SeExprEdDialog.cpp.
References _currentEditorIdx, controls, and SeExprEdControlCollection::showEditor().
Referenced by SeExprEdDialog().
void SeExprEdDialog::applyExpression () [slot]
Definition at line 281 of file SeExprEdDialog.cpp.
References SeExprEditor::addError(), SeExprEditor::clearErrors(), editor, SeExprEdGrapherWidget::expr, SeExprEdExpression::funcmap, SeExpression::getErrors(), SeExprEditor::getExpr(), grapher, SeExpression::isValid(), SeExprEditor::nextError(), previewCommentLabel, SeExprEdExpression::setExpr(), SeExprEdGrapherWidget::update(), and SeExprEdExpression::varmap.
Referenced by SeExprEdDialog(), verifiedAccept(), and verifiedApply().
void SeExprEdDialog::clearExpression () [slot]
Definition at line 330 of file SeExprEdDialog.cpp.
References browser, SeExprEdBrowser::clearSelection(), editor, SeExprEdGrapherWidget::expr, grapher, SeExprEdExpression::setExpr(), SeExprEditor::setExpr(), and SeExprEdGrapherWidget::update().
Referenced by SeExprEdDialog(), and setExpressionString().
int SeExprEdDialog::exec ()
Definition at line 153 of file SeExprEdDialog.cpp.
References browser, SeExprEdBrowser::expandAll(), and SeExprEdBrowser::getExpressionDirs().
Referenced by main(), and SeExprEdShortEdit::showDetails().
void SeExprEdDialog::expressionApplied () [signal]
Referenced by verifiedApply().
void SeExprEdDialog::findHelper (QTextDocument::FindFlags flags) [protected]
Definition at line 262 of file SeExprEdDialog.cpp.
References helpBrowser, helpFindBox, and prevFind.
Referenced by findNextInHelp(), and findPrevInHelp().
void SeExprEdDialog::findNextInHelp () [private, slot]
Definition at line 272 of file SeExprEdDialog.cpp.
References findHelper().
Referenced by setupHelp().
void SeExprEdDialog::findPrevInHelp () [private, slot]
Definition at line 277 of file SeExprEdDialog.cpp.
References findHelper().
Referenced by setupHelp().
std::string SeExprEdDialog::getExpressionString () [inline]
Definition at line 65 of file SeExprEdDialog.h.
References editor, and SeExprEditor::getExpr().
Referenced by main(), and SeExprEdShortEdit::showDetails().
void SeExprEdDialog::keyPressEvent (QKeyEvent * event) [protected]
Definition at line 161 of file SeExprEdDialog.cpp.
void SeExprEdDialog::setExpressionString (const std::string & str) [inline]
Definition at line 70 of file SeExprEdDialog.h.
References clearExpression(), editor, and SeExprEditor::setExpr().
Referenced by main(), and SeExprEdShortEdit::showDetails().
void SeExprEdDialog::setupHelp (QTabWidget * tab) [private]
Definition at line 205 of file SeExprEdDialog.cpp.
References findNextInHelp(), findPrevInHelp(), helpBrowser, and helpFindBox.
Referenced by SeExprEdDialog().
void SeExprEdDialog::showEditor (int idx)
Definition at line 141 of file SeExprEdDialog.cpp.
References _currentEditorIdx, and showEditorTimer.
Referenced by SeExprEdShortEdit::showDetails().
void SeExprEdDialog::verifiedAccept () [private, slot]
Definition at line 188 of file SeExprEdDialog.cpp.
References applyExpression(), SeExprEdGrapherWidget::expr, grapher, and SeExpression::isValid().
Referenced by SeExprEdDialog().
void SeExprEdDialog::verifiedApply () [private, slot]
Definition at line 167 of file SeExprEdDialog.cpp.
References applyExpression(), SeExprEdGrapherWidget::expr, expressionApplied(), grapher, and SeExpression::isValid().
Referenced by SeExprEdDialog().
Member Data Documentation
int SeExprEdDialog::_currentEditorIdx [private]
Definition at line 61 of file SeExprEdDialog.h.
Referenced by _showEditor(), and showEditor().
QPushButton* SeExprEdDialog::acceptButton [private]
Definition at line 50 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QPushButton* SeExprEdDialog::applyButton [private]
Definition at line 54 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
SeExprEdBrowser* SeExprEdDialog::browser
Definition at line 46 of file SeExprEdDialog.h.
Referenced by clearExpression(), exec(), SeExprEdDialog(), and SeExprEdShortEdit::showDetails().
QPushButton* SeExprEdDialog::cancelButton [private]
Definition at line 51 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QPushButton * SeExprEdDialog::clearButton [private]
Definition at line 55 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
SeExprEdControlCollection* SeExprEdDialog::controls [private]
Definition at line 52 of file SeExprEdDialog.h.
Referenced by _showEditor(), and SeExprEdDialog().
QTextCursor SeExprEdDialog::cursor [private]
Definition at line 59 of file SeExprEdDialog.h.
SeExprEditor* SeExprEdDialog::editor
Definition at line 45 of file SeExprEdDialog.h.
Referenced by applyExpression(), clearExpression(), getExpressionString(), SeExprEdDialog(), setExpressionString(), and SeExprEdShortEdit::showDetails().
SeExprEdGrapherWidget* SeExprEdDialog::grapher [private]
Definition at line 48 of file SeExprEdDialog.h.
Referenced by applyExpression(), clearExpression(), SeExprEdDialog(), verifiedAccept(), and verifiedApply().
QTextBrowser* SeExprEdDialog::helpBrowser [private]
Definition at line 58 of file SeExprEdDialog.h.
Referenced by findHelper(), and setupHelp().
QLineEdit* SeExprEdDialog::helpFindBox [private]
Definition at line 56 of file SeExprEdDialog.h.
Referenced by findHelper(), and setupHelp().
QString SeExprEdDialog::prevFind [private]
Definition at line 60 of file SeExprEdDialog.h.
Referenced by findHelper().
QPushButton * SeExprEdDialog::previewButton [private]
Definition at line 54 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QLabel* SeExprEdDialog::previewCommentLabel [private]
Definition at line 49 of file SeExprEdDialog.h.
Referenced by applyExpression(), and SeExprEdDialog().
QPushButton * SeExprEdDialog::saveAsButton [private]
Definition at line 54 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QPushButton * SeExprEdDialog::saveButton [private]
Definition at line 54 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QPushButton* SeExprEdDialog::saveLocalButton [private]
Definition at line 55 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog().
QTimer* SeExprEdDialog::showEditorTimer [private]
Definition at line 57 of file SeExprEdDialog.h.
Referenced by SeExprEdDialog(), and showEditor().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdDialog.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdDialog.cpp