SeExpr: SeExprEdExpression Class Reference
SeExprEdExpression Class Reference
#include <SeExprEdExpression.h>
Classes
struct DummyFuncX
struct ScalarRef
struct VectorRef
Public Types
typedef std::map< std::string,
VectorRef * > VARMAP
typedef std::map< std::string,
bool > FUNCMAP
Public Member Functions
SeExprEdExpression (const std::string &expr, bool vec)
virtual ~SeExprEdExpression ()
SeExprVarRef * resolveVar (const std::string &name) const
SeExprFunc * resolveFunc (const std::string &name) const
void setExpr (const std::string &str)
void clearVars ()
Public Attributes
SeExprEdExpression::DummyFuncX dummyFuncX
SeExprFunc dummyFunc
ScalarRef u
ScalarRef v
VectorRef P
VARMAP varmap
FUNCMAP funcmap
Detailed Description
Definition at line 24 of file SeExprEdExpression.h.
Member Typedef Documentation
typedef std::map<std::string,bool> SeExprEdExpression::FUNCMAP
Definition at line 72 of file SeExprEdExpression.h.
typedef std::map<std::string,VectorRef*> SeExprEdExpression::VARMAP
Definition at line 70 of file SeExprEdExpression.h.
Constructor & Destructor Documentation
SeExprEdExpression::SeExprEdExpression (const std::string & expr, bool vec)
Definition at line 17 of file SeExprEdExpression.cpp.
SeExprEdExpression::~SeExprEdExpression () [virtual]
Definition at line 21 of file SeExprEdExpression.cpp.
References clearVars().
Member Function Documentation
void SeExprEdExpression::clearVars ()
Definition at line 31 of file SeExprEdExpression.cpp.
References deleteAndClear(), funcmap, and varmap.
Referenced by setExpr(), and ~SeExprEdExpression().
SeExprFunc * SeExprEdExpression::resolveFunc (const std::string &) const [virtual]
override resolveFunc to add external functions
Reimplemented from SeExpression.
Definition at line 59 of file SeExprEdExpression.cpp.
References dummyFunc, funcmap, and SeExprFunc::lookup().
SeExprVarRef * SeExprEdExpression::resolveVar (const std::string &) const [virtual]
override resolveVar to add external variables
Reimplemented from SeExpression.
Definition at line 43 of file SeExprEdExpression.cpp.
References P, u, v, and varmap.
void SeExprEdExpression::setExpr (const std::string & e)
Set expression string to e. This invalidates all parsed state.
Reimplemented from SeExpression.
Definition at line 37 of file SeExprEdExpression.cpp.
References clearVars().
Referenced by SeExprEdDialog::applyExpression(), and SeExprEdDialog::clearExpression().
Member Data Documentation
SeExprFunc SeExprEdExpression::dummyFunc [mutable]
Definition at line 64 of file SeExprEdExpression.h.
Referenced by resolveFunc().
SeExprEdExpression::DummyFuncX SeExprEdExpression::dummyFuncX
FUNCMAP SeExprEdExpression::funcmap [mutable]
Definition at line 73 of file SeExprEdExpression.h.
Referenced by SeExprEdDialog::applyExpression(), clearVars(), and resolveFunc().
VectorRef SeExprEdExpression::P [mutable]
Definition at line 68 of file SeExprEdExpression.h.
Referenced by resolveVar(), and SeExprEdGrapherView::update().
ScalarRef SeExprEdExpression::u [mutable]
Definition at line 66 of file SeExprEdExpression.h.
Referenced by resolveVar(), and SeExprEdGrapherView::update().
ScalarRef SeExprEdExpression::v [mutable]
Definition at line 67 of file SeExprEdExpression.h.
Referenced by resolveVar(), and SeExprEdGrapherView::update().
VARMAP SeExprEdExpression::varmap [mutable]
Definition at line 71 of file SeExprEdExpression.h.
Referenced by SeExprEdDialog::applyExpression(), clearVars(), and resolveVar().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdExpression.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdExpression.cpp