SeExpr: SeExprEdGrapherWidget Class Reference
SeExprEdGrapherWidget Class Reference
#include <SeExprEdGrapher2d.h>
Signals
void preview ()
Public Member Functions
SeExprEdGrapherWidget (QWidget *parent, int width, int height)
void update ()
Public Attributes
SeExprEdGrapherView * view
SeExprEdExpression expr
Private Slots
void scaleValueEdited ()
void scaleValueManipulated ()
void forwardPreview ()
Private Attributes
QLineEdit * scale
Detailed Description
Definition at line 64 of file SeExprEdGrapher2d.h.
Constructor & Destructor Documentation
SeExprEdGrapherWidget::SeExprEdGrapherWidget (QWidget * parent, int width, int height)
Definition at line 23 of file SeExprEdGrapher2d.cpp.
References forwardPreview(), SeExprEdGrapherView::getWindow(), scale, scaleValueEdited(), scaleValueManipulated(), view, and z.
Member Function Documentation
void SeExprEdGrapherWidget::forwardPreview () [private, slot]
Definition at line 84 of file SeExprEdGrapher2d.cpp.
References preview().
Referenced by SeExprEdGrapherWidget().
void SeExprEdGrapherWidget::preview () [signal]
Referenced by forwardPreview().
void SeExprEdGrapherWidget::scaleValueEdited () [private, slot]
Definition at line 53 of file SeExprEdGrapher2d.cpp.
References SeExprEdGrapherView::getWindow(), scale, SeExprEdGrapherView::setWindow(), view, and z.
Referenced by SeExprEdGrapherWidget().
void SeExprEdGrapherWidget::scaleValueManipulated () [private, slot]
Definition at line 70 of file SeExprEdGrapher2d.cpp.
References SeExprEdGrapherView::getWindow(), scale, view, and z.
Referenced by SeExprEdGrapherWidget().
void SeExprEdGrapherWidget::update ()
Definition at line 77 of file SeExprEdGrapher2d.cpp.
References expr, SeExpression::setWantVec(), SeExprEdGrapherView::update(), and view.
Referenced by SeExprEdDialog::applyExpression(), and SeExprEdDialog::clearExpression().
Member Data Documentation
SeExprEdExpression SeExprEdGrapherWidget::expr
Definition at line 71 of file SeExprEdGrapher2d.h.
Referenced by SeExprEdDialog::applyExpression(), SeExprEdDialog::clearExpression(), SeExprEdGrapherView::update(), update(), SeExprEdDialog::verifiedAccept(), and SeExprEdDialog::verifiedApply().
QLineEdit* SeExprEdGrapherWidget::scale [private]
Definition at line 67 of file SeExprEdGrapher2d.h.
Referenced by scaleValueEdited(), scaleValueManipulated(), and SeExprEdGrapherWidget().
SeExprEdGrapherView* SeExprEdGrapherWidget::view
Definition at line 70 of file SeExprEdGrapher2d.h.
Referenced by scaleValueEdited(), scaleValueManipulated(), SeExprEdGrapherWidget(), and update().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdGrapher2d.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdGrapher2d.cpp