SeExpr: SeExprEditor Class Reference
SeExprEditor Class Reference
#include <SeExprEditor.h>
Public Slots
void exprChanged ()
void rebuildControls ()
void controlChanged (int id)
void nextError ()
void selectError ()
void sendApply ()
void sendPreview ()
void insertStr (const std::string &str)
Signals
void apply ()
void preview ()
Public Member Functions
SeExprEditor (QWidget *parent, SeExprEdControlCollection *controls)
virtual ~SeExprEditor ()
std::string getExpr ()
void setExpr (const std::string &expression, const bool apply=false)
void appendStr (const std::string &str)
void addError (const int startPos, const int endPos, const std::string &error)
void clearErrors ()
void clearExtraCompleters ()
void registerExtraFunction (const std::string &name, const std::string &docString)
void registerExtraVariable (const std::string &name, const std::string &docString)
void replaceExtras (const SeExprEdCompletionModel &completer)
void updateCompleter ()
void updateStyle ()
Private Attributes
SeExprEdExpressionTextEdit * exprTe
SeExprEdControlCollection * controls
QListWidget * errorWidget
QTimer * controlRebuildTimer
QTimer * previewTimer
bool _updatingText
int errorHeight
Detailed Description
Definition at line 90 of file SeExprEditor.h.
Constructor & Destructor Documentation
SeExprEditor::SeExprEditor (QWidget * parent, SeExprEdControlCollection * controls)
Definition at line 92 of file SeExprEditor.cpp.
References clearErrors(), controlChanged(), controlRebuildTimer, errorWidget, exprChanged(), exprTe, insertStr(), nextError(), previewTimer, rebuildControls(), selectError(), sendApply(), and sendPreview().
SeExprEditor::~SeExprEditor () [virtual]
Definition at line 83 of file SeExprEditor.cpp.
References controlRebuildTimer, and previewTimer.
Member Function Documentation
void SeExprEditor::addError (const int startPos, const int endPos, const std::string & error)
Definition at line 418 of file SeExprEditor.cpp.
References errorHeight, and errorWidget.
Referenced by SeExprEdDialog::applyExpression().
void SeExprEditor::appendStr (const std::string & str)
Definition at line 413 of file SeExprEditor.cpp.
References exprTe.
void SeExprEditor::apply () [signal]
Referenced by sendApply(), and setExpr().
void SeExprEditor::clearErrors ()
Definition at line 443 of file SeExprEditor.cpp.
References errorHeight, and errorWidget.
Referenced by SeExprEdDialog::applyExpression(), SeExprEditor(), and setExpr().
void SeExprEditor::clearExtraCompleters ()
Definition at line 450 of file SeExprEditor.cpp.
References SeExprEdCompletionModel::clearFunctions(), SeExprEdCompletionModel::clearVariables(), SeExprEdExpressionTextEdit::completionModel, and exprTe.
void SeExprEditor::controlChanged (int id) [slot]
Definition at line 68 of file SeExprEditor.cpp.
References _updatingText, controls, exprTe, previewTimer, and SeExprEdControlCollection::updateText().
Referenced by SeExprEditor().
void SeExprEditor::exprChanged () [slot]
Definition at line 167 of file SeExprEditor.cpp.
References _updatingText, and controlRebuildTimer.
Referenced by SeExprEditor().
std::string SeExprEditor::getExpr ()
Definition at line 393 of file SeExprEditor.cpp.
References exprTe.
Referenced by SeExprEdDialog::applyExpression(), SeExprEdDialog::getExpressionString(), SeExprEdBrowser::saveExpression(), SeExprEdBrowser::saveExpressionAs(), and SeExprEdBrowser::saveLocalExpressionAs().
void SeExprEditor::insertStr (const std::string & str) [slot]
Definition at line 408 of file SeExprEditor.cpp.
References exprTe.
Referenced by SeExprEditor().
void SeExprEditor::nextError () [slot]
Definition at line 436 of file SeExprEditor.cpp.
References errorWidget.
Referenced by SeExprEdDialog::applyExpression(), and SeExprEditor().
void SeExprEditor::preview () [signal]
Referenced by sendPreview().
void SeExprEditor::rebuildControls () [slot]
Definition at line 176 of file SeExprEditor.cpp.
References SeExprEdExpressionTextEdit::completer, SeExprEdExpressionTextEdit::completionModel, controls, exprTe, SeExprEdCompletionModel::local_variables, and SeExprEdControlCollection::rebuildControls().
Referenced by SeExprEditor().
void SeExprEditor::registerExtraFunction (const std::string & name, const std::string & docString)
Definition at line 456 of file SeExprEditor.cpp.
References SeExprEdCompletionModel::addFunction(), SeExprEdExpressionTextEdit::completionModel, and exprTe.
void SeExprEditor::registerExtraVariable (const std::string & name, const std::string & docString)
Definition at line 461 of file SeExprEditor.cpp.
References SeExprEdCompletionModel::addVariable(), SeExprEdExpressionTextEdit::completionModel, and exprTe.
void SeExprEditor::replaceExtras (const SeExprEdCompletionModel & completer)
Definition at line 466 of file SeExprEditor.cpp.
References SeExprEdExpressionTextEdit::completionModel, exprTe, and SeExprEdCompletionModel::syncExtras().
Referenced by SeExprEdShortEdit::showDetails().
void SeExprEditor::selectError () [slot]
Definition at line 144 of file SeExprEditor.cpp.
References errorWidget, and exprTe.
Referenced by SeExprEditor().
void SeExprEditor::sendApply () [slot]
Definition at line 157 of file SeExprEditor.cpp.
References apply().
Referenced by SeExprEditor().
void SeExprEditor::sendPreview () [slot]
Definition at line 162 of file SeExprEditor.cpp.
References preview().
Referenced by SeExprEditor().
void SeExprEditor::setExpr (const std::string & expression, const bool apply = false)
Definition at line 398 of file SeExprEditor.cpp.
References apply(), clearErrors(), and exprTe.
Referenced by SeExprEdDialog::clearExpression(), SeExprEdBrowser::handleSelection(), and SeExprEdDialog::setExpressionString().
void SeExprEditor::updateCompleter ()
Definition at line 471 of file SeExprEditor.cpp.
References SeExprEdExpressionTextEdit::completer, SeExprEdExpressionTextEdit::completionModel, and exprTe.
void SeExprEditor::updateStyle ()
Definition at line 476 of file SeExprEditor.cpp.
References exprTe, and SeExprEdExpressionTextEdit::updateStyle().
Member Data Documentation
bool SeExprEditor::_updatingText [private]
Definition at line 146 of file SeExprEditor.h.
Referenced by controlChanged(), and exprChanged().
QTimer* SeExprEditor::controlRebuildTimer [private]
Definition at line 142 of file SeExprEditor.h.
Referenced by exprChanged(), SeExprEditor(), and ~SeExprEditor().
SeExprEdControlCollection* SeExprEditor::controls [private]
Definition at line 139 of file SeExprEditor.h.
Referenced by controlChanged(), and rebuildControls().
int SeExprEditor::errorHeight [private]
Definition at line 147 of file SeExprEditor.h.
Referenced by addError(), and clearErrors().
QListWidget* SeExprEditor::errorWidget [private]
Definition at line 140 of file SeExprEditor.h.
Referenced by addError(), clearErrors(), nextError(), SeExprEditor(), and selectError().
SeExprEdExpressionTextEdit* SeExprEditor::exprTe [private]
Definition at line 138 of file SeExprEditor.h.
Referenced by appendStr(), clearExtraCompleters(), controlChanged(), getExpr(), insertStr(), rebuildControls(), registerExtraFunction(), registerExtraVariable(), replaceExtras(), SeExprEditor(), selectError(), setExpr(), updateCompleter(), and updateStyle().
QTimer* SeExprEditor::previewTimer [private]
Definition at line 143 of file SeExprEditor.h.
Referenced by controlChanged(), SeExprEditor(), and ~SeExprEditor().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEditor.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEditor.cpp