SeExpr: SeExprEdColorCurve Class Reference
SeExprEdColorCurve Class Reference
#include <SeExprEdColorCurve.h>
Public Slots
void cvSelectedSlot (const double pos, const SeVec3d val, const T_INTERP interp)
void selPosChanged ()
void openDetail ()
Signals
void selPosChangedSignal (double pos)
void selValChangedSignal (SeVec3d val)
void swatchChanged (QColor color)
Public Member Functions
SeExprEdColorCurve (QWidget *parent=0, QString pLabel="", QString vLabel="", QString iLabel="", bool expandable=true)
~SeExprEdColorCurve ()
void addPoint (const double x, const SeVec3d y, const T_INTERP interp, bool select=false)
void setSwatchColor (QColor color)
QColor getSwatchColor ()
Public Attributes
CCurveScene * _scene
Private Types
typedef SeExpr::SeCurve< SeVec3d > T_CURVE
typedef T_CURVE::InterpType T_INTERP
Private Slots
void internalSwatchChanged (QColor color)
Private Attributes
QLineEdit * _selPosEdit
SeExprEdCSwatchFrame * _selValEdit
QComboBox * _interpComboBox
Detailed Description
Definition at line 137 of file SeExprEdColorCurve.h.
Member Typedef Documentation
typedef SeExpr::SeCurve<SeVec3d> SeExprEdColorCurve::T_CURVE [private]
Definition at line 141 of file SeExprEdColorCurve.h.
typedef T_CURVE::InterpType SeExprEdColorCurve::T_INTERP [private]
Definition at line 142 of file SeExprEdColorCurve.h.
Constructor & Destructor Documentation
SeExprEdColorCurve::SeExprEdColorCurve (QWidget * parent = 0, QString pLabel = "", QString vLabel = "", QString iLabel = "", bool expandable = true)
Definition at line 363 of file SeExprEdColorCurve.cpp.
References _interpComboBox, _scene, _selPosEdit, _selValEdit, cvSelectedSlot(), internalSwatchChanged(), openDetail(), selPosChanged(), selPosChangedSignal(), selValChangedSignal(), and swatchChanged().
Referenced by openDetail().
SeExprEdColorCurve::~SeExprEdColorCurve () [inline]
Definition at line 147 of file SeExprEdColorCurve.h.
Member Function Documentation
void SeExprEdColorCurve::addPoint (const double x, const SeVec3d y, const T_INTERP interp, bool select = false)
Definition at line 501 of file SeExprEdColorCurve.cpp.
References _scene, and CCurveScene::addPoint().
Referenced by openDetail(), and SeExprEdCCurveControl::SeExprEdCCurveControl().
void SeExprEdColorCurve::cvSelectedSlot (const double pos, const SeVec3d val, const T_INTERP interp) [slot]
Definition at line 481 of file SeExprEdColorCurve.cpp.
References _interpComboBox, _selPosEdit, _selValEdit, SeExprEdCSwatchFrame::setValue(), and swatchChanged().
Referenced by SeExprEdColorCurve().
QColor SeExprEdColorCurve::getSwatchColor ()
Definition at line 513 of file SeExprEdColorCurve.cpp.
References _selValEdit, and SeExprEdCSwatchFrame::getValue().
Referenced by SeExprEdCCurveControl::getColor().
void SeExprEdColorCurve::internalSwatchChanged (QColor color) [private, slot]
Definition at line 519 of file SeExprEdColorCurve.cpp.
References swatchChanged().
Referenced by SeExprEdColorCurve().
void SeExprEdColorCurve::openDetail () [slot]
Definition at line 524 of file SeExprEdColorCurve.cpp.
References CCurveScene::_cvs, _scene, addPoint(), SeExpr::curve, CCurveScene::emitCurveChanged(), CCurveScene::removeAll(), and SeExprEdColorCurve().
Referenced by SeExprEdColorCurve().
void SeExprEdColorCurve::selPosChanged () [slot]
Definition at line 494 of file SeExprEdColorCurve.cpp.
References _selPosEdit, SeExpr::clamp(), and selPosChangedSignal().
Referenced by SeExprEdColorCurve().
void SeExprEdColorCurve::selPosChangedSignal (double pos) [signal]
Referenced by SeExprEdColorCurve(), and selPosChanged().
void SeExprEdColorCurve::selValChangedSignal (SeVec3d val) [signal]
Referenced by SeExprEdColorCurve().
void SeExprEdColorCurve::setSwatchColor (QColor color)
Definition at line 506 of file SeExprEdColorCurve.cpp.
References _scene, _selValEdit, CCurveScene::selValChanged(), and SeExprEdCSwatchFrame::setValue().
Referenced by SeExprEdCCurveControl::setColor().
void SeExprEdColorCurve::swatchChanged (QColor color) [signal]
Referenced by cvSelectedSlot(), internalSwatchChanged(), and SeExprEdColorCurve().
Member Data Documentation
QComboBox* SeExprEdColorCurve::_interpComboBox [private]
Definition at line 172 of file SeExprEdColorCurve.h.
Referenced by cvSelectedSlot(), and SeExprEdColorCurve().
CCurveScene* SeExprEdColorCurve::_scene
Definition at line 154 of file SeExprEdColorCurve.h.
Referenced by addPoint(), SeExprEdCCurveControl::curveChanged(), openDetail(), SeExprEdCCurveControl::SeExprEdCCurveControl(), SeExprEdColorCurve(), and setSwatchColor().
QLineEdit* SeExprEdColorCurve::_selPosEdit [private]
Definition at line 170 of file SeExprEdColorCurve.h.
Referenced by cvSelectedSlot(), SeExprEdColorCurve(), and selPosChanged().
SeExprEdCSwatchFrame* SeExprEdColorCurve::_selValEdit [private]
Definition at line 171 of file SeExprEdColorCurve.h.
Referenced by cvSelectedSlot(), getSwatchColor(), SeExprEdColorCurve(), and setSwatchColor().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdColorCurve.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdColorCurve.cpp