SeExpr: SeExprEdCurve Class Reference
SeExprEdCurve Class Reference
#include <SeExprEdCurve.h>
Public Slots
void cvSelectedSlot (double pos, double val, T_INTERP interp)
void selPosChanged ()
void selValChanged ()
void openDetail ()
Signals
void selPosChangedSignal (double pos)
void selValChangedSignal (double val)
Public Member Functions
SeExprEdCurve (QWidget *parent=0, QString pLabel="", QString vLabel="", QString iLabel="", bool expandable=true)
~SeExprEdCurve ()
void addPoint (const double x, const double y, const T_INTERP interp, bool select=false)
Public Attributes
CurveScene * _scene
Private Types
typedef SeExpr::SeCurve< double > T_CURVE
typedef T_CURVE::InterpType T_INTERP
Private Attributes
QLineEdit * _selPosEdit
QLineEdit * _selValEdit
QComboBox * _interpComboBox
Detailed Description
Definition at line 111 of file SeExprEdCurve.h.
Member Typedef Documentation
typedef SeExpr::SeCurve<double> SeExprEdCurve::T_CURVE [private]
Definition at line 115 of file SeExprEdCurve.h.
typedef T_CURVE::InterpType SeExprEdCurve::T_INTERP [private]
Definition at line 116 of file SeExprEdCurve.h.
Constructor & Destructor Documentation
SeExprEdCurve::SeExprEdCurve (QWidget * parent = 0, QString pLabel = "", QString vLabel = "", QString iLabel = "", bool expandable = true)
Definition at line 274 of file SeExprEdCurve.cpp.
References _interpComboBox, _scene, _selPosEdit, _selValEdit, cvSelectedSlot(), openDetail(), selPosChanged(), selPosChangedSignal(), selValChanged(), and selValChangedSignal().
Referenced by openDetail().
SeExprEdCurve::~SeExprEdCurve () [inline]
Definition at line 121 of file SeExprEdCurve.h.
Member Function Documentation
void SeExprEdCurve::addPoint (const double x, const double y, const T_INTERP interp, bool select = false)
Definition at line 470 of file SeExprEdCurve.cpp.
References _scene, and CurveScene::addPoint().
Referenced by openDetail(), and SeExprEdCurveControl::SeExprEdCurveControl().
void SeExprEdCurve::cvSelectedSlot (double pos, double val, T_INTERP interp) [slot]
Definition at line 396 of file SeExprEdCurve.cpp.
References _interpComboBox, _selPosEdit, and _selValEdit.
Referenced by SeExprEdCurve().
void SeExprEdCurve::openDetail () [slot]
Definition at line 426 of file SeExprEdCurve.cpp.
References CurveScene::_cvs, _scene, addPoint(), SeExpr::curve, CurveScene::emitCurveChanged(), CurveScene::removeAll(), and SeExprEdCurve().
Referenced by SeExprEdCurve().
void SeExprEdCurve::selPosChanged () [slot]
Definition at line 409 of file SeExprEdCurve.cpp.
References _selPosEdit, and selPosChangedSignal().
Referenced by SeExprEdCurve().
void SeExprEdCurve::selPosChangedSignal (double pos) [signal]
Referenced by SeExprEdCurve(), and selPosChanged().
void SeExprEdCurve::selValChanged () [slot]
Definition at line 418 of file SeExprEdCurve.cpp.
References _selValEdit, SeExpr::clamp(), and selValChangedSignal().
Referenced by SeExprEdCurve().
void SeExprEdCurve::selValChangedSignal (double val) [signal]
Referenced by SeExprEdCurve(), and selValChanged().
Member Data Documentation
QComboBox* SeExprEdCurve::_interpComboBox [private]
Definition at line 141 of file SeExprEdCurve.h.
Referenced by cvSelectedSlot(), and SeExprEdCurve().
CurveScene* SeExprEdCurve::_scene
Definition at line 126 of file SeExprEdCurve.h.
Referenced by addPoint(), SeExprEdCurveControl::curveChanged(), openDetail(), SeExprEdCurve(), and SeExprEdCurveControl::SeExprEdCurveControl().
QLineEdit* SeExprEdCurve::_selPosEdit [private]
Definition at line 139 of file SeExprEdCurve.h.
Referenced by cvSelectedSlot(), SeExprEdCurve(), and selPosChanged().
QLineEdit* SeExprEdCurve::_selValEdit [private]
Definition at line 140 of file SeExprEdCurve.h.
Referenced by cvSelectedSlot(), SeExprEdCurve(), and selValChanged().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdCurve.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdCurve.cpp