SeExpr: SeExprSubscriptNode Class Reference
SeExprSubscriptNode Class Reference
Node that evaluates a component of a vector.
#include <SeExprNode.h>
Public Member Functions
SeExprSubscriptNode (const SeExpression *expr, SeExprNode *a, SeExprNode *b)
virtual bool prep (bool wantVec)
virtual void eval (SeVec3d &result) const
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Detailed Description
Node that evaluates a component of a vector.
Definition at line 210 of file SeExprNode.h.
Constructor & Destructor Documentation
SeExprSubscriptNode::SeExprSubscriptNode (const SeExpression * expr, SeExprNode * a, SeExprNode * b) [inline]
Definition at line 213 of file SeExprNode.h.
Member Function Documentation
void SeExprSubscriptNode::eval (SeVec3d & v) const [virtual]
Evaluation method. Note: v[1] and v[2] are undefined if !isVec.
Reimplemented from SeExprNode.
Definition at line 341 of file SeExprNode.cpp.
References a, b, SeExprNode::child(), SeExprNode::eval(), index(), and SeExprNode::isVec().
bool SeExprSubscriptNode::prep (bool wantVec) [virtual]
Prepare the node (for parser use only). See the discussion at the start of SeExprNode.cpp for more info.
Reimplemented from SeExprNode.
Definition at line 328 of file SeExprNode.cpp.
References SeExprNode::_isVec, and SeExprNode::child().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExpr/SeExprNode.cpp