SeExpr: SeExprEdCSwatchFrame Class Reference
SeExprEdCSwatchFrame Class Reference
#include <SeExprEdColorCurve.h>
Signals
void selValChangedSignal (SeVec3d value)
void swatchChanged (QColor color)
Public Member Functions
SeExprEdCSwatchFrame (SeVec3d value, QWidget *parent=0)
~SeExprEdCSwatchFrame ()
void setValue (const SeVec3d &value)
SeVec3d getValue () const
Protected Member Functions
virtual void paintEvent (QPaintEvent *event)
virtual void mousePressEvent (QMouseEvent *event)
Private Attributes
SeVec3d _value
QColor _color
Detailed Description
Definition at line 113 of file SeExprEdColorCurve.h.
Constructor & Destructor Documentation
SeExprEdCSwatchFrame::SeExprEdCSwatchFrame (SeVec3d value, QWidget * parent = 0)
Definition at line 323 of file SeExprEdColorCurve.cpp.
References _color, and _value.
SeExprEdCSwatchFrame::~SeExprEdCSwatchFrame () [inline]
Definition at line 118 of file SeExprEdColorCurve.h.
Member Function Documentation
SeVec3d SeExprEdCSwatchFrame::getValue () const
Definition at line 337 of file SeExprEdColorCurve.cpp.
References _value.
Referenced by SeExprEdColorCurve::getSwatchColor(), and SeExprEdVectorControl::swatchChanged().
void SeExprEdCSwatchFrame::mousePressEvent (QMouseEvent * event) [protected, virtual]
Definition at line 343 of file SeExprEdColorCurve.cpp.
References _color, _value, selValChangedSignal(), and swatchChanged().
void SeExprEdCSwatchFrame::paintEvent (QPaintEvent * event) [protected, virtual]
Definition at line 315 of file SeExprEdColorCurve.cpp.
References _color, and p.
void SeExprEdCSwatchFrame::selValChangedSignal (SeVec3d value) [signal]
Referenced by mousePressEvent().
void SeExprEdCSwatchFrame::setValue (const SeVec3d & value)
Definition at line 329 of file SeExprEdColorCurve.cpp.
References _color, and _value.
Referenced by SeExprEdColorCurve::cvSelectedSlot(), SeExprEdColorCurve::setSwatchColor(), and SeExprEdVectorControl::setValue().
void SeExprEdCSwatchFrame::swatchChanged (QColor color) [signal]
Referenced by mousePressEvent().
Member Data Documentation
QColor SeExprEdCSwatchFrame::_color [private]
Definition at line 133 of file SeExprEdColorCurve.h.
Referenced by mousePressEvent(), paintEvent(), SeExprEdCSwatchFrame(), and setValue().
SeVec3d SeExprEdCSwatchFrame::_value [private]
Definition at line 132 of file SeExprEdColorCurve.h.
Referenced by getValue(), mousePressEvent(), SeExprEdCSwatchFrame(), and setValue().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdColorCurve.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdColorCurve.cpp