SeExpr: SeExprEdCCurveControl Class Reference
SeExprEdCCurveControl Class Reference
Control for editing a color ramp curve.
#include <SeExprEdControl.h>
Public Member Functions
SeExprEdCCurveControl (int id, SeExprEdColorCurveEditable *stringEditable)
QColor getColor ()
Interface for getting the color (used for linked color picking).
void setColor (QColor color)
Interface for setting the color (used for linked color picking).
Private Slots
void curveChanged ()
Private Attributes
SeExprEdColorCurveEditable * _curveEditable
color curve model
SeExprEdColorCurve * _curve
color curve widget
Detailed Description
Control for editing a color ramp curve.
Definition at line 239 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdCCurveControl::SeExprEdCCurveControl (int id, SeExprEdColorCurveEditable * stringEditable)
Definition at line 574 of file SeExprEdControl.cpp.
References _curve, _curveEditable, SeExpr::SeCurve< T >::CV::_interp, SeExpr::SeCurve< T >::CV::_pos, SeExprEdColorCurve::_scene, SeExpr::SeCurve< T >::CV::_val, SeExprEdColorCurve::addPoint(), curveChanged(), SeExprEdGenericCurveEditable< TVAL >::cvs, and SeExprEdControl::hbox.
Member Function Documentation
void SeExprEdCCurveControl::curveChanged () [private, slot]
Definition at line 590 of file SeExprEdControl.cpp.
References _curve, _curveEditable, CCurveScene::_cvs, SeExprEdControl::_id, SeExprEdColorCurve::_scene, SeExprEdControl::controlChanged(), and SeExprEdGenericCurveEditable< TVAL >::cvs.
Referenced by SeExprEdCCurveControl().
QColor SeExprEdCCurveControl::getColor () [virtual]
Interface for getting the color (used for linked color picking).
Reimplemented from SeExprEdControl.
Definition at line 600 of file SeExprEdControl.cpp.
References _curve, and SeExprEdColorCurve::getSwatchColor().
void SeExprEdCCurveControl::setColor (QColor color) [virtual]
Interface for setting the color (used for linked color picking).
Reimplemented from SeExprEdControl.
Definition at line 605 of file SeExprEdControl.cpp.
References _curve, and SeExprEdColorCurve::setSwatchColor().
Member Data Documentation
SeExprEdColorCurve* SeExprEdCCurveControl::_curve [private]
color curve widget
Definition at line 246 of file SeExprEdControl.h.
Referenced by curveChanged(), getColor(), SeExprEdCCurveControl(), and setColor().
SeExprEdColorCurveEditable* SeExprEdCCurveControl::_curveEditable [private]
color curve model
Definition at line 244 of file SeExprEdControl.h.
Referenced by curveChanged(), and SeExprEdCCurveControl().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp