SeExpr: SeExprEdTreeModel Class Reference
SeExprEdTreeModel Class Reference
Public Member Functions
SeExprEdTreeModel ()
~SeExprEdTreeModel ()
void update ()
void clear ()
void addPath (const char *label, const char *path)
QModelIndex parent (const QModelIndex &index) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
int columnCount (const QModelIndex &parent) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
QModelIndex find (QString path)
Private Attributes
SeExprEdTreeItem * root
Detailed Description
Definition at line 133 of file SeExprEdBrowser.cpp.
Constructor & Destructor Documentation
SeExprEdTreeModel::SeExprEdTreeModel () [inline]
Definition at line 137 of file SeExprEdBrowser.cpp.
SeExprEdTreeModel::~SeExprEdTreeModel () [inline]
Definition at line 141 of file SeExprEdBrowser.cpp.
References root.
Member Function Documentation
void SeExprEdTreeModel::addPath (const char * label, const char * path) [inline]
Definition at line 157 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::addChild(), and root.
Referenced by SeExprEdBrowser::addPath().
void SeExprEdTreeModel::clear () [inline]
Definition at line 151 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::clear(), root, and update().
Referenced by SeExprEdBrowser::clear().
int SeExprEdTreeModel::columnCount (const QModelIndex & parent) const [inline]
Definition at line 182 of file SeExprEdBrowser.cpp.
QVariant SeExprEdTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const [inline]
Definition at line 195 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::label.
QModelIndex SeExprEdTreeModel::find (QString path) [inline]
Definition at line 204 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::find(), SeExprEdTreeItem::regen(), root, and SeExprEdTreeItem::row.
Referenced by SeExprEdBrowser::selectPath().
QModelIndex SeExprEdTreeModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const [inline]
Definition at line 171 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::getChild(), parent(), and root.
QModelIndex SeExprEdTreeModel::parent (const QModelIndex & index) const [inline]
Definition at line 162 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::parent, root, and SeExprEdTreeItem::row.
Referenced by index(), and rowCount().
int SeExprEdTreeModel::rowCount (const QModelIndex & parent = QModelIndex()) const [inline]
Definition at line 185 of file SeExprEdBrowser.cpp.
References SeExprEdTreeItem::getChildCount(), parent(), and root.
void SeExprEdTreeModel::update () [inline]
Definition at line 146 of file SeExprEdBrowser.cpp.
Referenced by clear(), and SeExprEdBrowser::update().
Member Data Documentation
SeExprEdTreeItem* SeExprEdTreeModel::root [private]
Definition at line 135 of file SeExprEdBrowser.cpp.
Referenced by addPath(), clear(), find(), index(), parent(), rowCount(), and ~SeExprEdTreeModel().
The documentation for this class was generated from the following file:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdBrowser.cpp