SeExpr: SeExprEdShortEdit Class Reference
SeExprEdShortEdit Class Reference
#include <SeExprEdShortEdit.h>
Signals
void exprChanged ()
Public Member Functions
SeExprEdShortEdit (QWidget *parent, bool expanded=true)
virtual ~SeExprEdShortEdit ()
std::string getExpressionString () const
QString getExpression () const
void setExpressionString (const std::string &expression)
void clearExtraCompleters ()
void registerExtraFunction (const std::string &name, const std::string &docString)
void registerExtraVariable (const std::string &name, const std::string &docString)
void updateCompleter ()
void setSimple (bool enabled)
void setDetailsMenu (QMenu *menu)
void setSearchPath (const QString &context, const QString &path)
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy policy)
int showDetails (int idx)
virtual QSize sizeHint () const
virtual void hideErrors (bool hidden, const std::string &err)
Public Attributes
QToolButton * expandButton
SeExprEdShortTextEdit * edit
Protected Slots
virtual void detailPressed ()
virtual void expandPressed ()
virtual void textFinished ()
virtual void handleTextEdited ()
virtual void controlChanged (int id)
virtual void rebuildControls ()
Protected Member Functions
void checkErrors ()
Protected Attributes
QTimer * controlRebuildTimer
QToolButton * editDetail
SeExprEdControlCollection * controls
QVBoxLayout * vboxlayout
QHBoxLayout * hboxlayout
QLabel * error
std::string _context
std::string _searchPath
Detailed Description
Definition at line 38 of file SeExprEdShortEdit.h.
Constructor & Destructor Documentation
SeExprEdShortEdit::SeExprEdShortEdit (QWidget * parent, bool expanded = true)
Definition at line 88 of file SeExprEdShortEdit.cpp.
References controlRebuildTimer, controls, detailPressed(), edit, editDetail, error, expandButton, expandPressed(), hboxlayout, rebuildControls(), stop_xpm, sum_xpm, textFinished(), and vboxlayout.
SeExprEdShortEdit::~SeExprEdShortEdit () [virtual]
Definition at line 137 of file SeExprEdShortEdit.cpp.
References controlRebuildTimer.
Member Function Documentation
void SeExprEdShortEdit::checkErrors () [protected]
Definition at line 277 of file SeExprEdShortEdit.cpp.
References expr(), getExpressionString(), hideErrors(), SeExpression::isValid(), and SeExpression::parseError().
Referenced by controlChanged(), setExpressionString(), and textFinished().
void SeExprEdShortEdit::clearExtraCompleters ()
Definition at line 252 of file SeExprEdShortEdit.cpp.
References SeExprEdCompletionModel::clearFunctions(), SeExprEdCompletionModel::clearVariables(), SeExprEdShortTextEdit::completionModel, and edit.
void SeExprEdShortEdit::controlChanged (int id) [protected, virtual, slot]
Definition at line 240 of file SeExprEdShortEdit.cpp.
References checkErrors(), controls, edit, exprChanged(), getExpression(), and SeExprEdControlCollection::updateText().
Referenced by expandPressed().
void SeExprEdShortEdit::detailPressed () [protected, virtual, slot]
Definition at line 148 of file SeExprEdShortEdit.cpp.
References showDetails().
Referenced by SeExprEdShortEdit().
void SeExprEdShortEdit::expandPressed () [protected, virtual, slot]
Definition at line 192 of file SeExprEdShortEdit.cpp.
References controlChanged(), controlRebuildTimer, controls, and expandButton.
Referenced by SeExprEdShortEdit().
void SeExprEdShortEdit::exprChanged () [signal]
Referenced by controlChanged(), setExpressionString(), and textFinished().
QString SeExprEdShortEdit::getExpression () const
Definition at line 230 of file SeExprEdShortEdit.cpp.
References edit.
Referenced by controlChanged(), getExpressionString(), and rebuildControls().
std::string SeExprEdShortEdit::getExpressionString () const
Definition at line 235 of file SeExprEdShortEdit.cpp.
References getExpression().
Referenced by checkErrors(), and showDetails().
void SeExprEdShortEdit::handleTextEdited () [protected, virtual, slot]
Definition at line 209 of file SeExprEdShortEdit.cpp.
void SeExprEdShortEdit::hideErrors (bool hidden, const std::string & err) [virtual]
Definition at line 289 of file SeExprEdShortEdit.cpp.
References error.
Referenced by checkErrors().
void SeExprEdShortEdit::rebuildControls () [protected, virtual, slot]
Definition at line 174 of file SeExprEdShortEdit.cpp.
References SeExprEdShortTextEdit::completer, SeExprEdShortTextEdit::completionModel, controls, edit, expandButton, getExpression(), SeExprEdCompletionModel::local_variables, SeExprEdControlCollection::numControls(), SeExprEdControlCollection::rebuildControls(), and vboxlayout.
Referenced by SeExprEdShortEdit().
void SeExprEdShortEdit::registerExtraFunction (const std::string & name, const std::string & docString)
Definition at line 259 of file SeExprEdShortEdit.cpp.
References SeExprEdCompletionModel::addFunction(), SeExprEdShortTextEdit::completionModel, and edit.
void SeExprEdShortEdit::registerExtraVariable (const std::string & name, const std::string & docString)
Definition at line 265 of file SeExprEdShortEdit.cpp.
References SeExprEdCompletionModel::addVariable(), SeExprEdShortTextEdit::completionModel, and edit.
void SeExprEdShortEdit::setDetailsMenu (QMenu * menu)
Definition at line 305 of file SeExprEdShortEdit.cpp.
References editDetail.
void SeExprEdShortEdit::setExpressionString (const std::string & expression)
Definition at line 220 of file SeExprEdShortEdit.cpp.
References checkErrors(), controlRebuildTimer, edit, and exprChanged().
Referenced by showDetails().
void SeExprEdShortEdit::setSearchPath (const QString & context, const QString & path)
Definition at line 142 of file SeExprEdShortEdit.cpp.
References _context, and _searchPath.
void SeExprEdShortEdit::setSimple (bool enabled)
Definition at line 298 of file SeExprEdShortEdit.cpp.
References edit, editDetail, and expandButton.
void SeExprEdShortEdit::setVerticalScrollBarPolicy (Qt::ScrollBarPolicy policy)
Definition at line 310 of file SeExprEdShortEdit.cpp.
References edit.
int SeExprEdShortEdit::showDetails (int idx)
Definition at line 153 of file SeExprEdShortEdit.cpp.
References _context, _searchPath, SeExprEdDialog::browser, SeExprEdShortTextEdit::completionModel, edit, SeExprEdDialog::editor, SeExprEdDialog::exec(), SeExprEdBrowser::expandAll(), SeExprEdDialog::getExpressionString(), getExpressionString(), SeExprEditor::replaceExtras(), setExpressionString(), SeExprEdDialog::setExpressionString(), SeExprEdBrowser::setSearchPath(), and SeExprEdDialog::showEditor().
Referenced by detailPressed().
virtual QSize SeExprEdShortEdit::sizeHint () const [inline, virtual]
Definition at line 81 of file SeExprEdShortEdit.h.
void SeExprEdShortEdit::textFinished () [protected, virtual, slot]
Definition at line 212 of file SeExprEdShortEdit.cpp.
References checkErrors(), controlRebuildTimer, and exprChanged().
Referenced by SeExprEdShortEdit().
void SeExprEdShortEdit::updateCompleter ()
Definition at line 271 of file SeExprEdShortEdit.cpp.
References SeExprEdShortTextEdit::completer, SeExprEdShortTextEdit::completionModel, and edit.
Member Data Documentation
std::string SeExprEdShortEdit::_context [protected]
Definition at line 49 of file SeExprEdShortEdit.h.
Referenced by setSearchPath(), and showDetails().
std::string SeExprEdShortEdit::_searchPath [protected]
Definition at line 50 of file SeExprEdShortEdit.h.
Referenced by setSearchPath(), and showDetails().
QTimer* SeExprEdShortEdit::controlRebuildTimer [protected]
Definition at line 43 of file SeExprEdShortEdit.h.
Referenced by expandPressed(), SeExprEdShortEdit(), setExpressionString(), textFinished(), and ~SeExprEdShortEdit().
SeExprEdControlCollection* SeExprEdShortEdit::controls [protected]
Definition at line 45 of file SeExprEdShortEdit.h.
Referenced by controlChanged(), expandPressed(), rebuildControls(), and SeExprEdShortEdit().
SeExprEdShortTextEdit* SeExprEdShortEdit::edit
Definition at line 86 of file SeExprEdShortEdit.h.
Referenced by clearExtraCompleters(), controlChanged(), getExpression(), rebuildControls(), registerExtraFunction(), registerExtraVariable(), SeExprEdShortEdit(), setExpressionString(), setSimple(), setVerticalScrollBarPolicy(), showDetails(), and updateCompleter().
QToolButton* SeExprEdShortEdit::editDetail [protected]
Definition at line 44 of file SeExprEdShortEdit.h.
Referenced by SeExprEdShortEdit(), setDetailsMenu(), and setSimple().
QLabel* SeExprEdShortEdit::error [protected]
Definition at line 48 of file SeExprEdShortEdit.h.
Referenced by hideErrors(), and SeExprEdShortEdit().
QToolButton* SeExprEdShortEdit::expandButton
Definition at line 85 of file SeExprEdShortEdit.h.
Referenced by expandPressed(), rebuildControls(), SeExprEdShortEdit(), and setSimple().
QHBoxLayout* SeExprEdShortEdit::hboxlayout [protected]
Definition at line 47 of file SeExprEdShortEdit.h.
Referenced by SeExprEdShortEdit().
QVBoxLayout* SeExprEdShortEdit::vboxlayout [protected]
Definition at line 46 of file SeExprEdShortEdit.h.
Referenced by rebuildControls(), and SeExprEdShortEdit().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdShortEdit.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdShortEdit.cpp