SeExpr: SeExprEdSlider Class Reference
SeExprEdSlider Class Reference
Generic Slider (used for int and float sliders).
#include <SeExprEdControl.h>
Public Member Functions
SeExprEdSlider (QWidget *parent=0)
SeExprEdSlider (Qt::Orientation orientation, QWidget *parent=0)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void paintEvent (QPaintEvent *e)
virtual void leaveEvent (QEvent *event)
virtual void enterEvent (QEvent *event)
virtual void wheelEvent (QWheelEvent *e)
Detailed Description
Generic Slider (used for int and float sliders).
Definition at line 114 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdSlider::SeExprEdSlider (QWidget * parent = 0) [inline]
Definition at line 118 of file SeExprEdControl.h.
SeExprEdSlider::SeExprEdSlider (Qt::Orientation orientation, QWidget * parent = 0) [inline]
Definition at line 119 of file SeExprEdControl.h.
Member Function Documentation
virtual void SeExprEdSlider::enterEvent (QEvent * event) [inline, virtual]
Definition at line 125 of file SeExprEdControl.h.
virtual void SeExprEdSlider::leaveEvent (QEvent * event) [inline, virtual]
Definition at line 124 of file SeExprEdControl.h.
void SeExprEdSlider::mouseMoveEvent (QMouseEvent * e) [virtual]
Definition at line 171 of file SeExprEdControl.cpp.
References SeExpr::max(), and SeExpr::min().
Referenced by mousePressEvent().
void SeExprEdSlider::mousePressEvent (QMouseEvent * e) [virtual]
Definition at line 166 of file SeExprEdControl.cpp.
References mouseMoveEvent().
void SeExprEdSlider::paintEvent (QPaintEvent * e) [virtual]
Definition at line 179 of file SeExprEdControl.cpp.
References p, and value().
virtual void SeExprEdSlider::wheelEvent (QWheelEvent * e) [inline, virtual]
Definition at line 126 of file SeExprEdControl.h.
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp