SeExpr: SeExprEdCurveControl Class Reference
SeExprEdCurveControl Class Reference
Control for editing a normal curve ramp.
#include <SeExprEdControl.h>
Public Member Functions
SeExprEdCurveControl (int id, SeExprEdCurveEditable *stringEditable)
Private Slots
void curveChanged ()
Private Attributes
SeExprEdCurveEditable * _curveEditable
curve model
SeExprEdCurve * _curve
curve edit widget
Detailed Description
Control for editing a normal curve ramp.
Definition at line 224 of file SeExprEdControl.h.
Constructor & Destructor Documentation
SeExprEdCurveControl::SeExprEdCurveControl (int id, SeExprEdCurveEditable * stringEditable)
Definition at line 550 of file SeExprEdControl.cpp.
References _curve, _curveEditable, SeExpr::SeCurve< T >::CV::_interp, SeExpr::SeCurve< T >::CV::_pos, SeExprEdCurve::_scene, SeExpr::SeCurve< T >::CV::_val, SeExprEdCurve::addPoint(), curveChanged(), SeExprEdGenericCurveEditable< TVAL >::cvs, and SeExprEdControl::hbox.
Member Function Documentation
void SeExprEdCurveControl::curveChanged () [private, slot]
Definition at line 566 of file SeExprEdControl.cpp.
References _curve, _curveEditable, CurveScene::_cvs, SeExprEdControl::_id, SeExprEdCurve::_scene, SeExprEdControl::controlChanged(), and SeExprEdGenericCurveEditable< TVAL >::cvs.
Referenced by SeExprEdCurveControl().
Member Data Documentation
SeExprEdCurve* SeExprEdCurveControl::_curve [private]
curve edit widget
Definition at line 231 of file SeExprEdControl.h.
Referenced by curveChanged(), and SeExprEdCurveControl().
SeExprEdCurveEditable* SeExprEdCurveControl::_curveEditable [private]
curve model
Definition at line 229 of file SeExprEdControl.h.
Referenced by curveChanged(), and SeExprEdCurveControl().
The documentation for this class was generated from the following files:
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.h
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdControl.cpp