SeExpr: /disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdFileDialog.cpp File Reference
/disk1/scratch/aselle/projects/seexpr/SeExpr/src/SeExprEditor/SeExprEdFileDialog.cpp File Reference
#include "SeExprEdFileDialog.h"
#include <QtGui/QToolButton>
#include <QtGui/QPalette>
#include <QtGui/QMenu>
#include <QtCore/QTimer>
#include <QtCore/QUrl>
#include <iostream>
Functions
static QStringList makeFiltersList (const QString &filter)
Variables
static const char * folder_fav []
Function Documentation
static QStringList makeFiltersList (const QString & filter) [static]
Definition at line 255 of file SeExprEdFileDialog.cpp.
Referenced by SeExprEdFileDialog::getExistingDirectory(), SeExprEdFileDialog::getOpenFileName(), SeExprEdFileDialog::getOpenFileNames(), and SeExprEdFileDialog::getSaveFileName().
Variable Documentation
const char* folder_fav[] [static]
Initial value:
{
    "17 16 4 1",
    "# c #000000",
    ". c None",
    "a c #ffff98",
    "b c #cc0000",
    ".................",
    ".................",
    "...#####.........",
    "..#aaaaa#........",
    ".###############.",
    ".#aaaaaaaaaaaaa#.",
    ".#aaaa##a##aaaa#.",
    ".#aaa#bb#bb#aaa#.",
    ".#aaa#bbbbb#aaa#.",
    ".#aaa#bbbbb#aaa#.",
    ".#aaaa#bbb#aaaa#.",
    ".#aaaaa#b#aaaaa#.",
    ".#aaaaaa#aaaaaa#.",
    ".#aaaaaaaaaaaaa#.",
    ".###############.",
    "................."}
Definition at line 26 of file SeExprEdFileDialog.cpp.
Referenced by SeExprEdFileDialog::addFavoritesButton().